
# CABLE paper-ready experiment — lean 10-run protocol

## Final design

**CABLE = Context-Aware Boundary and Local Evidence**

The CABLE architecture is frozen:

\[
Y = X + \Delta_{\rm local} + \alpha\,\Delta_{\rm context},
\]

with:

- frozen H4-K3 MHTM-Local as the full-resolution local-evidence branch;
- 16×16 coarse global self-attention as the context branch;
- 4 context heads;
- learned context scale \(\alpha\), initialized to 0.1;
- original SwiftMSeg LGL blocks at encoder Stages 2–4;
- ordinary cross-entropy training only.

No architecture or loss tuning is performed in this notebook.

---

## Why this notebook trains only CABLE

The authoritative SwiftMSeg-LGL and MHTM-Local experiments are already complete:

- **BUS-BRA:** use the clean checkpoint-only audit generated from the saved best-validation-Dice checkpoints;
- **BUS-UCLM:** use the completed supervised patient-disjoint five-fold experiment.

Those two baselines therefore remain exactly as previously frozen.

This notebook performs only:

> **5 BUS-BRA CABLE trainings + 5 BUS-UCLM CABLE trainings = 10 new trainings.**

For every CABLE fold, the same 50-epoch trajectory saves **two validation-selected checkpoints**:

1. **CABLE-Dice** — maximum validation foreground Dice.  
   This is the fair architecture-comparison operating point because Swift-LGL and MHTM
   were also frozen by validation Dice.

2. **CABLE-Boundary** — among epochs within **0.005 absolute Dice** of the maximum,
   select the minimum validation HD95; ties are resolved by higher Boundary-IoU,
   then higher Dice, then earlier epoch.

The held-out outer test fold is accessed only after both checkpoints have been frozen.

### Paper-facing interpretation

- **Main architecture table:** Swift-LGL vs MHTM-Local vs **CABLE-Dice**.
- **Secondary ultrasound operating-point analysis:** **CABLE-Dice vs CABLE-Boundary**.

This prevents CABLE from receiving an unfair checkpoint-selection advantage while still
testing the medically motivated boundary-aware operating point.


## Dataset protocol

### BUS-BRA
The dataset-supplied official 5-fold partition is the outer patient-disjoint test split.
For each outer fold, the inner validation split is reproduced from the remaining patients
using the same frozen seed as the previous final experiment.

### BUS-UCLM
The same geometry audit is retained: 13 incompatible HESN image-mask pairs are excluded,
leaving 670 aligned images from 37 patients. The **exact previously saved outer-fold
assignment** is loaded from the completed BUS-UCLM experiment rather than regenerated.

The primary supervised task remains lesion segmentation. Normal images are excluded from
training and checkpoint selection and are evaluated only as a held-out false-positive
control.

In [1]:

# ============================================================
# 0. INSTALL + IMPORTS
# ============================================================

import sys
import subprocess
import importlib.util

packages = {
    "transformers": "transformers>=4.45",
    "albumentations": "albumentations>=1.4",
    "cv2": "opencv-python-headless",
    "sklearn": "scikit-learn",
    "requests": "requests",
    "tqdm": "tqdm",
}

for module, package in packages.items():
    if importlib.util.find_spec(module) is None:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", package]
        )

import os
import gc
import json
import time
import math
import random
import zipfile
import warnings
import hashlib
import shutil
import datetime
import tempfile

from dataclasses import dataclass, asdict
from pathlib import Path

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

from scipy.ndimage import binary_erosion, distance_transform_edt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import StratifiedGroupKFold

import albumentations as A
from albumentations.pytorch import ToTensorV2

from transformers import SegformerModel
from IPython.display import display

warnings.filterwarnings("ignore")

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("PyTorch:", torch.__version__)
print("Device :", DEVICE)

if DEVICE.type == "cuda":
    print("GPU    :", torch.cuda.get_device_name(0))

PyTorch: 2.11.0+cu128
Device : cuda
GPU    : Tesla T4

In [36]:

# ============================================================
# 1. FINAL FROZEN CONFIGURATION
# ============================================================

from dataclasses import dataclass, asdict

@dataclass
class CFG:
    image_size: int = 256
    batch_size: int = 8
    eval_batch_size: int = 8

    busbra_num_workers: int = 4
    uclm_num_workers: int = 2

    num_classes: int = 2

    epochs: int = 50
    lr: float = 1e-3
    weight_decay: float = 1e-2
    scheduler_factor: float = 0.5
    scheduler_patience: int = 3

    pretrained_backbone: str = "nvidia/mit-b0"
    lgl_heads: int = 4

    mhtm_heads: int = 4
    mhtm_kernel: int = 3

    cable_context_hw: int = 16
    cable_context_heads: int = 4
    cable_context_scale_init: float = 0.1

    train_seed: int = 42

    busbra_inner_val_seed: int = 2026
    uclm_inner_val_seed: int = 3026

    use_amp: bool = False

    # Boundary-aware operating point:
    dice_tolerance: float = 0.005
    hd95_tie_tolerance: float = 1e-12
    boundary_iou_tie_tolerance: float = 1e-12


cfg = CFG()

BASELINE_VARIANTS = (
    "swift_lgl",
    "mhtm_hybrid_final",
)

CABLE_VARIANT = "cable_s1"

ARCHITECTURE_VARIANTS = (
    "swift_lgl",
    "mhtm_hybrid_final",
    "cable_s1",
)

OUTER_FOLDS = (
    1,
    2,
    3,
    4,
    5,
)

RUN_BUSBRA = True
RUN_BUSUCLM = True

FORCE_RERUN = False

print(json.dumps(asdict(cfg), indent=2))
print("Baseline variants reused :", BASELINE_VARIANTS)
print("Only trained variant     :", CABLE_VARIANT)
print("Outer folds              :", OUTER_FOLDS)
print("Total new trainings      :", len(OUTER_FOLDS) * 2)

{
  "image_size": 256,
  "batch_size": 8,
  "eval_batch_size": 8,
  "busbra_num_workers": 4,
  "uclm_num_workers": 2,
  "num_classes": 2,
  "epochs": 50,
  "lr": 0.001,
  "weight_decay": 0.01,
  "scheduler_factor": 0.5,
  "scheduler_patience": 3,
  "pretrained_backbone": "nvidia/mit-b0",
  "lgl_heads": 4,
  "mhtm_heads": 4,
  "mhtm_kernel": 3,
  "cable_context_hw": 16,
  "cable_context_heads": 4,
  "cable_context_scale_init": 0.1,
  "train_seed": 42,
  "busbra_inner_val_seed": 2026,
  "uclm_inner_val_seed": 3026,
  "use_amp": false,
  "dice_tolerance": 0.005,
  "hd95_tie_tolerance": 1e-12,
  "boundary_iou_tie_tolerance": 1e-12
}
Baseline variants reused : ('swift_lgl', 'mhtm_hybrid_final')
Only trained variant     : cable_s1
Outer folds              : (1, 2, 3, 4, 5)
Total new trainings      : 10

In [37]:

# ============================================================
# 2. REPRODUCIBILITY
# ============================================================

def set_seed(seed: int):
    os.environ["PYTHONHASHSEED"] = str(seed)

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    try:
        torch.use_deterministic_algorithms(
            True,
            warn_only=True,
        )
    except Exception:
        pass


def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % (2**32)
    np.random.seed(worker_seed)
    random.seed(worker_seed)


set_seed(cfg.train_seed)

In [38]:

# ============================================================
# 3. GOOGLE DRIVE + AUTHORITATIVE ROOTS
# ============================================================

IN_COLAB = False

try:
    import google.colab
    IN_COLAB = True
except Exception:
    pass


if IN_COLAB:
    from google.colab import drive

    drive.mount(
        "/content/drive",
        force_remount=False,
    )

    DRIVE_ROOT = Path(
        "/content/drive/MyDrive/MHTM_MEDICAL"
    )

    LOCAL_ROOT = Path(
        "/content/MHTM_MEDICAL"
    )

else:
    DRIVE_ROOT = Path("./MHTM_MEDICAL")
    LOCAL_ROOT = Path("./MHTM_MEDICAL_LOCAL")


DRIVE_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

LOCAL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# AUTHORITATIVE EXISTING BASELINES — NEVER MODIFIED HERE
# ------------------------------------------------------------

# BUS-BRA authoritative metrics after the clean checkpoint audit.
OLD_BRA_AUDIT_ROOT = (
    DRIVE_ROOT
    / "SWIFT_MHTM_FINAL_OFFICIALCV_CLEAN_AUDIT_V1"
)

# Original BUS-BRA training root is kept only for checkpoint provenance /
# optional future qualitative regeneration. It is NOT retrained here.
OLD_BRA_TRAIN_ROOT = (
    DRIVE_ROOT
    / "SWIFT_MHTM_FINAL_OFFICIALCV_V1"
)

# BUS-UCLM completed supervised CV root.
OLD_UCLM_ROOT = (
    DRIVE_ROOT
    / "SWIFT_MHTM_BUSUCLM_SUPERVISED_CV_V1"
)


# ------------------------------------------------------------
# NEW CABLE-ONLY OUTPUT
# ------------------------------------------------------------

FINAL_ROOT = (
    DRIVE_ROOT
    / "CABLE_PAPER_READY_LEAN10_V1"
)

FINAL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

BUSBRA_FINAL_ROOT = (
    FINAL_ROOT
    / "BUS_BRA"
)

UCLM_FINAL_ROOT = (
    FINAL_ROOT
    / "BUS_UCLM"
)

BUSBRA_FINAL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

UCLM_FINAL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


print("BUS-BRA clean baseline root :", OLD_BRA_AUDIT_ROOT)
print("BUS-UCLM baseline root      :", OLD_UCLM_ROOT)
print("New CABLE output root       :", FINAL_ROOT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
BUS-BRA clean baseline root : /content/drive/MyDrive/MHTM_MEDICAL/SWIFT_MHTM_FINAL_OFFICIALCV_CLEAN_AUDIT_V1
BUS-UCLM baseline root      : /content/drive/MyDrive/MHTM_MEDICAL/SWIFT_MHTM_BUSUCLM_SUPERVISED_CV_V1
New CABLE output root       : /content/drive/MyDrive/MHTM_MEDICAL/CABLE_PAPER_READY_LEAN10_V1

In [39]:

# ============================================================
# 4. SHARED MODEL: SWIFT-LGL / MHTM / CABLE
# ============================================================

class LGLBlock(nn.Module):
    def __init__(
        self,
        dim,
        num_heads=4,
    ):
        super().__init__()

        self.local1 = nn.Conv2d(
            dim,
            dim,
            kernel_size=3,
            padding=1,
            groups=dim,
        )

        self.norm1 = nn.LayerNorm(
            dim
        )

        self.attn = nn.MultiheadAttention(
            embed_dim=dim,
            num_heads=num_heads,
            batch_first=True,
        )

        self.norm2 = nn.LayerNorm(
            dim
        )

        self.local2 = nn.Conv2d(
            dim,
            dim,
            kernel_size=3,
            padding=1,
            groups=dim,
        )

    def forward(
        self,
        x,
    ):
        B, C, H, W = x.shape

        x_local = self.local1(
            x
        )

        x_flat = (
            x_local
            .permute(0, 2, 3, 1)
            .reshape(B, H * W, C)
        )

        x_norm = self.norm1(
            x_flat
        )

        attn_out, _ = self.attn(
            x_norm,
            x_norm,
            x_norm,
            need_weights=False,
        )

        x_attn = self.norm2(
            x_norm
            + attn_out
        )

        x_attn = (
            x_attn
            .reshape(B, H, W, C)
            .permute(0, 3, 1, 2)
        )

        return self.local2(
            x_attn
        )


class CanonicalMHTMLocal2D(nn.Module):
    def __init__(
        self,
        channels,
        num_heads=4,
        kernel_size=3,
    ):
        super().__init__()

        if channels % num_heads != 0:
            raise ValueError(
                "channels must be divisible by num_heads"
            )

        self.local_mix = nn.Conv2d(
            channels,
            channels,
            kernel_size=kernel_size,
            padding=kernel_size // 2,
            groups=channels,
            bias=False,
        )

        self.head_proj = nn.Conv2d(
            channels,
            channels,
            kernel_size=1,
            groups=num_heads,
            bias=False,
        )

        self.out_proj = nn.Conv2d(
            channels,
            channels,
            kernel_size=1,
            bias=False,
        )

    def forward(
        self,
        x,
    ):
        y = self.local_mix(
            x
        )

        y = self.head_proj(
            y
        )

        y = self.out_proj(
            y
        )

        return x + y


class CABLEBlock(nn.Module):
    """
    Context-Aware Boundary and Local Evidence.

    Fusion:
        x + local_delta + alpha * coarse_context_delta
    """

    def __init__(
        self,
        channels,
        local_heads=4,
        local_kernel=3,
        context_hw=16,
        context_heads=4,
        context_scale_init=0.1,
    ):
        super().__init__()

        if channels % local_heads != 0:
            raise ValueError(
                "channels must be divisible by local_heads"
            )

        if channels % context_heads != 0:
            raise ValueError(
                "channels must be divisible by context_heads"
            )

        self.channels = int(
            channels
        )

        self.context_hw = int(
            context_hw
        )

        self.local_mix = nn.Conv2d(
            channels,
            channels,
            kernel_size=local_kernel,
            padding=local_kernel // 2,
            groups=channels,
            bias=False,
        )

        self.local_head_proj = nn.Conv2d(
            channels,
            channels,
            kernel_size=1,
            groups=local_heads,
            bias=False,
        )

        self.local_out_proj = nn.Conv2d(
            channels,
            channels,
            kernel_size=1,
            bias=False,
        )

        self.context_norm1 = nn.LayerNorm(
            channels
        )

        self.context_attn = nn.MultiheadAttention(
            embed_dim=channels,
            num_heads=context_heads,
            batch_first=True,
        )

        self.context_norm2 = nn.LayerNorm(
            channels
        )

        self.context_proj = nn.Conv2d(
            channels,
            channels,
            kernel_size=1,
            bias=False,
        )

        self.context_scale = nn.Parameter(
            torch.tensor(
                float(
                    context_scale_init
                )
            )
        )

    def forward(
        self,
        x,
    ):
        B, C, H, W = x.shape

        local_delta = self.local_mix(
            x
        )

        local_delta = self.local_head_proj(
            local_delta
        )

        local_delta = self.local_out_proj(
            local_delta
        )

        ctx = F.adaptive_avg_pool2d(
            x,
            output_size=(
                self.context_hw,
                self.context_hw,
            ),
        )

        h = self.context_hw
        w = self.context_hw

        tokens = (
            ctx
            .permute(0, 2, 3, 1)
            .reshape(B, h * w, C)
        )

        tokens_norm = self.context_norm1(
            tokens
        )

        attn_out, _ = self.context_attn(
            tokens_norm,
            tokens_norm,
            tokens_norm,
            need_weights=False,
        )

        tokens = self.context_norm2(
            tokens_norm
            + attn_out
        )

        ctx = (
            tokens
            .reshape(B, h, w, C)
            .permute(0, 3, 1, 2)
        )

        ctx = self.context_proj(
            ctx
        )

        context_delta = F.interpolate(
            ctx,
            size=(H, W),
            mode="bilinear",
            align_corners=False,
        )

        return (
            x
            + local_delta
            + self.context_scale
            * context_delta
        )


def make_aggregator(
    name,
    channels,
):
    if name == "swift_lgl":
        return LGLBlock(
            channels,
            num_heads=cfg.lgl_heads,
        )

    if name == "mhtm_local":
        return CanonicalMHTMLocal2D(
            channels,
            num_heads=cfg.mhtm_heads,
            kernel_size=cfg.mhtm_kernel,
        )

    if name == "cable":
        return CABLEBlock(
            channels,
            local_heads=cfg.mhtm_heads,
            local_kernel=cfg.mhtm_kernel,
            context_hw=cfg.cable_context_hw,
            context_heads=cfg.cable_context_heads,
            context_scale_init=cfg.cable_context_scale_init,
        )

    raise ValueError(
        name
    )


class SwiftMSegFamily(nn.Module):
    CHANNELS = (
        32,
        64,
        160,
        256,
    )

    def __init__(
        self,
        variant,
        num_classes=2,
    ):
        super().__init__()

        self.backbone = (
            SegformerModel
            .from_pretrained(
                cfg.pretrained_backbone,
                output_hidden_states=True,
            )
        )

        # Shared decoder constructed before variant-specific modules.
        self.up3 = nn.ConvTranspose2d(
            256,
            160,
            2,
            stride=2,
        )

        self.dec3 = nn.Conv2d(
            160 + 160,
            160,
            3,
            padding=1,
        )

        self.up2 = nn.ConvTranspose2d(
            160,
            64,
            2,
            stride=2,
        )

        self.dec2 = nn.Conv2d(
            64 + 64,
            64,
            3,
            padding=1,
        )

        self.up1 = nn.ConvTranspose2d(
            64,
            32,
            2,
            stride=2,
        )

        self.dec1 = nn.Conv2d(
            32 + 32,
            32,
            3,
            padding=1,
        )

        self.final = nn.Conv2d(
            32,
            num_classes,
            kernel_size=1,
        )

        if variant == "swift_lgl":
            stage_names = (
                "swift_lgl",
                "swift_lgl",
                "swift_lgl",
                "swift_lgl",
            )

        elif variant == "mhtm_hybrid_final":
            stage_names = (
                "mhtm_local",
                "swift_lgl",
                "swift_lgl",
                "swift_lgl",
            )

        elif variant == "cable_s1":
            stage_names = (
                "cable",
                "swift_lgl",
                "swift_lgl",
                "swift_lgl",
            )

        else:
            raise ValueError(
                variant
            )

        self.aggregators = nn.ModuleList([
            make_aggregator(
                name,
                channels,
            )
            for name, channels
            in zip(
                stage_names,
                self.CHANNELS,
            )
        ])

        self.variant = variant
        self.stage_names = stage_names

    def forward(
        self,
        x,
    ):
        outputs = self.backbone(
            pixel_values=x,
            output_hidden_states=True,
            return_dict=True,
        )

        feats = outputs.hidden_states

        if len(feats) != 4:
            raise RuntimeError(
                f"Expected 4 encoder stages, got {len(feats)}"
            )

        e1, e2, e3, e4 = [
            agg(feat)
            for agg, feat
            in zip(
                self.aggregators,
                feats,
            )
        ]

        d3 = self.up3(
            e4
        )

        d3 = torch.cat(
            [d3, e3],
            dim=1,
        )

        d3 = F.relu(
            self.dec3(d3),
            inplace=False,
        )

        d2 = self.up2(
            d3
        )

        d2 = torch.cat(
            [d2, e2],
            dim=1,
        )

        d2 = F.relu(
            self.dec2(d2),
            inplace=False,
        )

        d1 = self.up1(
            d2
        )

        d1 = torch.cat(
            [d1, e1],
            dim=1,
        )

        d1 = F.relu(
            self.dec1(d1),
            inplace=False,
        )

        out = self.final(
            d1
        )

        return F.interpolate(
            out,
            size=x.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

In [40]:

# ============================================================
# 5. MODEL / COMPLEXITY AUDIT
# ============================================================

def count_trainable_params(
    model,
):
    return sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )


def aggregator_params(
    model,
):
    return sum(
        p.numel()
        for p in model.aggregators.parameters()
        if p.requires_grad
    )


STAGES = [
    (64, 64, 32),
    (32, 32, 64),
    (16, 16, 160),
    (8, 8, 256),
]


def lgl_macs(
    H,
    W,
    C,
    k=3,
):
    N = H * W

    return (
        2 * N * C * k * k
        + 4 * N * C * C
        + 2 * N * N * C
    )


def mhtm_macs(
    H,
    W,
    C,
    k=3,
    heads=4,
):
    N = H * W

    return (
        N * C * k * k
        + N * C * C / heads
        + N * C * C
    )


def coarse_context_macs(
    context_hw,
    C,
):
    N = context_hw * context_hw

    # QKV + output projection + context_proj + QK + AV.
    return (
        5 * N * C * C
        + 2 * N * N * C
    )


lgl_costs = [
    lgl_macs(
        *stage
    )
    for stage
    in STAGES
]

swift_cost = sum(
    lgl_costs
)

mhtm_cost = (
    mhtm_macs(
        *STAGES[0],
        k=cfg.mhtm_kernel,
        heads=cfg.mhtm_heads,
    )
    + sum(
        lgl_costs[1:]
    )
)

cable_cost = (
    mhtm_cost
    + coarse_context_macs(
        cfg.cable_context_hw,
        STAGES[0][2],
    )
)


complexity_lookup = {
    "swift_lgl": swift_cost / 1e9,
    "mhtm_hybrid_final": mhtm_cost / 1e9,
    "cable_s1": cable_cost / 1e9,
}


audit_rows = []
shared_reference = None

for variant in ARCHITECTURE_VARIANTS:
    set_seed(
        777
    )

    model = SwiftMSegFamily(
        variant=variant,
        num_classes=cfg.num_classes,
    ).to(
        DEVICE
    )

    shared = {
        k: v.detach().cpu()
        for k, v
        in model.state_dict().items()
        if not k.startswith(
            "aggregators."
        )
    }

    if shared_reference is None:
        shared_reference = {
            k: v.clone()
            for k, v
            in shared.items()
        }

    shared_exact = all(
        torch.equal(
            shared_reference[k],
            shared[k],
        )
        for k
        in shared_reference
    )

    dummy = torch.zeros(
        1,
        3,
        cfg.image_size,
        cfg.image_size,
        device=DEVICE,
    )

    with torch.inference_mode():
        output = model(
            dummy
        )

    audit_rows.append({
        "variant": variant,
        "params_M": count_trainable_params(
            model
        ) / 1e6,
        "aggregator_params_M": aggregator_params(
            model
        ) / 1e6,
        "aggregator_GMACs": complexity_lookup[
            variant
        ],
        "shared_initialization_exact": shared_exact,
        "output_shape": tuple(
            output.shape
        ),
    })

    del model
    gc.collect()

    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()


architecture_audit = pd.DataFrame(
    audit_rows
)

display(
    architecture_audit
)

assert architecture_audit[
    "shared_initialization_exact"
].all()

print("CABLE aggregation reduction vs Swift-LGL:",
      1.0 - cable_cost / swift_cost)

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,variant,params_M,aggregator_params_M,aggregator_GMACs,shared_initialization_exact,output_shape
0,swift_lgl,4.485282,0.399360,1.312145,True,"(1, 2, 256, 256)"
1,mhtm_hybrid_final,4.481858,0.395936,0.225690,True,"(1, 2, 256, 256)"
2,cable_s1,4.487235,0.401313,0.231195,True,"(1, 2, 256, 256)"

CABLE aggregation reduction vs Swift-LGL: 0.823804113027083

In [41]:

# ============================================================
# 6. SHARED SEGMENTATION METRICS
# ============================================================

criterion = nn.CrossEntropyLoss()


def confusion_counts(
    pred_fg,
    target_fg,
):
    pred_fg = np.asarray(
        pred_fg,
        dtype=bool,
    )

    target_fg = np.asarray(
        target_fg,
        dtype=bool,
    )

    tp = int(
        np.logical_and(
            pred_fg,
            target_fg,
        ).sum()
    )

    tn = int(
        np.logical_and(
            ~pred_fg,
            ~target_fg,
        ).sum()
    )

    fp = int(
        np.logical_and(
            pred_fg,
            ~target_fg,
        ).sum()
    )

    fn = int(
        np.logical_and(
            ~pred_fg,
            target_fg,
        ).sum()
    )

    return tp, tn, fp, fn


def dice_iou(
    tp,
    fp,
    fn,
):
    union_den = tp + fp + fn
    dice_den = 2 * tp + fp + fn

    if union_den == 0:
        return 1.0, 1.0

    return (
        float(
            2 * tp / dice_den
        ),
        float(
            tp / union_den
        ),
    )


def hd95_binary(
    pred_fg,
    target_fg,
):
    pred_fg = np.asarray(
        pred_fg,
        dtype=bool,
    )

    target_fg = np.asarray(
        target_fg,
        dtype=bool,
    )

    if (
        not pred_fg.any()
        and not target_fg.any()
    ):
        return 0.0

    if (
        pred_fg.any()
        != target_fg.any()
    ):
        H, W = pred_fg.shape

        return float(
            np.sqrt(
                H * H
                + W * W
            )
        )

    pred_boundary = np.logical_xor(
        pred_fg,
        binary_erosion(
            pred_fg
        ),
    )

    target_boundary = np.logical_xor(
        target_fg,
        binary_erosion(
            target_fg
        ),
    )

    if not pred_boundary.any():
        pred_boundary = pred_fg

    if not target_boundary.any():
        target_boundary = target_fg

    dist_to_target = distance_transform_edt(
        ~target_boundary
    )

    dist_to_pred = distance_transform_edt(
        ~pred_boundary
    )

    distances = np.concatenate([
        dist_to_target[
            pred_boundary
        ],
        dist_to_pred[
            target_boundary
        ],
    ])

    return float(
        np.percentile(
            distances,
            95,
        )
    )


def boundary_iou(
    pred_fg,
    target_fg,
    width=3,
):
    pred_fg = np.asarray(
        pred_fg,
        dtype=bool,
    )

    target_fg = np.asarray(
        target_fg,
        dtype=bool,
    )

    structure = np.ones(
        (
            2 * width + 1,
            2 * width + 1,
        ),
        dtype=bool,
    )

    pred_eroded = binary_erosion(
        pred_fg,
        structure=structure,
        border_value=0,
    )

    target_eroded = binary_erosion(
        target_fg,
        structure=structure,
        border_value=0,
    )

    pred_b = np.logical_and(
        pred_fg,
        ~pred_eroded,
    )

    target_b = np.logical_and(
        target_fg,
        ~target_eroded,
    )

    inter = int(
        np.logical_and(
            pred_b,
            target_b,
        ).sum()
    )

    union = int(
        np.logical_or(
            pred_b,
            target_b,
        ).sum()
    )

    if union == 0:
        return 1.0

    return float(
        inter / union
    )


def summarize_lesion_rows(
    details,
):
    expected_dice = (
        2
        * details["iou"].to_numpy()
        / (
            1
            + details["iou"].to_numpy()
        )
    )

    identity_error = float(
        np.max(
            np.abs(
                details["dice"].to_numpy()
                - expected_dice
            )
        )
    )

    assert identity_error < 1e-10

    return {
        "dice": float(
            details["dice"].mean()
        ),
        "iou": float(
            details["iou"].mean()
        ),
        "hd95": float(
            details["hd95"].mean()
        ),
        "boundary_iou": float(
            details["boundary_iou"].mean()
        ),
        "n_images": int(
            len(details)
        ),
        "n_patients": int(
            details["patient"].nunique()
        ),
        "dice_iou_identity_error": identity_error,
    }


@torch.inference_mode()
def evaluate_lesion_loader(
    model,
    loader,
    save_masks_path=None,
):
    model.eval()

    losses = []
    rows = []
    pred_masks = []
    pred_ids = []

    for images, masks, meta in loader:
        images = images.to(
            DEVICE,
            non_blocking=True,
        )

        masks_gpu = masks.to(
            DEVICE,
            non_blocking=True,
        )

        logits = model(
            images
        )

        loss = criterion(
            logits,
            masks_gpu,
        )

        losses.append(
            loss.item()
        )

        preds = (
            logits.argmax(dim=1)
            .cpu()
            .numpy()
            .astype(np.uint8)
        )

        targets = (
            masks.numpy()
            .astype(np.uint8)
        )

        for i in range(
            len(preds)
        ):
            p = preds[i] == 1
            t = targets[i] == 1

            tp, tn, fp, fn = confusion_counts(
                p,
                t,
            )

            d, j = dice_iou(
                tp,
                fp,
                fn,
            )

            rows.append({
                "id": str(
                    meta["id"][i]
                ),
                "patient": str(
                    meta["patient"][i]
                ),
                "pathology": str(
                    meta["pathology"][i]
                ),
                "tp": tp,
                "tn": tn,
                "fp": fp,
                "fn": fn,
                "dice": d,
                "iou": j,
                "hd95": hd95_binary(
                    p,
                    t,
                ),
                "boundary_iou": boundary_iou(
                    p,
                    t,
                ),
                "gt_area_fraction": float(
                    t.mean()
                ),
                "pred_area_fraction": float(
                    p.mean()
                ),
            })

            if save_masks_path is not None:
                pred_masks.append(
                    preds[i]
                )
                pred_ids.append(
                    str(
                        meta["id"][i]
                    )
                )

    details = pd.DataFrame(
        rows
    )

    summary = summarize_lesion_rows(
        details
    )

    summary["loss"] = float(
        np.mean(
            losses
        )
    )

    if save_masks_path is not None:
        save_masks_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        np.savez_compressed(
            save_masks_path,
            ids=np.asarray(
                pred_ids,
                dtype=str,
            ),
            masks=np.stack(
                pred_masks,
                axis=0,
            ),
        )

    return summary, details


@torch.inference_mode()
def evaluate_normal_loader(
    model,
    loader,
    save_masks_path=None,
):
    model.eval()

    rows = []
    pred_masks = []
    pred_ids = []

    for images, masks, meta in loader:
        assert int(
            masks.sum()
        ) == 0

        images = images.to(
            DEVICE,
            non_blocking=True,
        )

        logits = model(
            images
        )

        preds = (
            logits.argmax(dim=1)
            .cpu()
            .numpy()
            .astype(np.uint8)
        )

        for i in range(
            len(preds)
        ):
            p = preds[i] == 1

            rows.append({
                "id": str(
                    meta["id"][i]
                ),
                "patient": str(
                    meta["patient"][i]
                ),
                "pathology": "normal",
                "pred_area_fraction": float(
                    p.mean()
                ),
                "any_predicted_lesion": int(
                    p.any()
                ),
            })

            if save_masks_path is not None:
                pred_masks.append(
                    preds[i]
                )
                pred_ids.append(
                    str(
                        meta["id"][i]
                    )
                )

    details = pd.DataFrame(
        rows
    )

    summary = {
        "normal_fp_area_mean": float(
            details[
                "pred_area_fraction"
            ].mean()
        ),
        "normal_fp_area_median": float(
            details[
                "pred_area_fraction"
            ].median()
        ),
        "normal_any_lesion_rate": float(
            details[
                "any_predicted_lesion"
            ].mean()
        ),
        "n_normal_images": int(
            len(details)
        ),
        "n_normal_patients": int(
            details[
                "patient"
            ].nunique()
        ),
    }

    if save_masks_path is not None:
        save_masks_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        np.savez_compressed(
            save_masks_path,
            ids=np.asarray(
                pred_ids,
                dtype=str,
            ),
            masks=np.stack(
                pred_masks,
                axis=0,
            ),
        )

    return summary, details


## Two checkpoint policies from one training trajectory

For CABLE, the ordinary architecture-comparison checkpoint is

\[
e_{\rm Dice}=\arg\max_e D_e.
\]

The boundary-aware operating point first defines the Dice-preserving candidate set

\[
\mathcal C=
\{e : D_e\ge D_{\max}-0.005\},
\]

then selects

\[
e_{\rm Boundary}=
\arg\min_{e\in\mathcal C} H_{95,e}.
\]

Boundary-IoU, Dice, and earlier epoch are deterministic tie-breakers.

**Neither rule uses the test set.**

In [42]:

# ============================================================
# 7. FINAL DICE-CONSTRAINED BOUNDARY SELECTOR
# ============================================================

def select_boundary_checkpoint(
    history_df,
):
    required = {
        "epoch",
        "val_dice",
        "val_hd95",
        "val_boundary_iou",
    }

    missing = required - set(
        history_df.columns
    )

    assert not missing, (
        f"History missing selector columns: {missing}"
    )

    max_dice = float(
        history_df[
            "val_dice"
        ].max()
    )

    threshold = (
        max_dice
        - cfg.dice_tolerance
    )

    candidates = (
        history_df[
            history_df[
                "val_dice"
            ]
            >= threshold
        ]
        .copy()
        .reset_index(drop=True)
    )

    assert len(
        candidates
    ) > 0

    # Primary: minimum HD95.
    best_hd95 = float(
        candidates[
            "val_hd95"
        ].min()
    )

    candidates = candidates[
        candidates[
            "val_hd95"
        ]
        <= (
            best_hd95
            + cfg.hd95_tie_tolerance
        )
    ].copy()

    # Tie-break 1: maximum Boundary IoU.
    best_biou = float(
        candidates[
            "val_boundary_iou"
        ].max()
    )

    candidates = candidates[
        candidates[
            "val_boundary_iou"
        ]
        >= (
            best_biou
            - cfg.boundary_iou_tie_tolerance
        )
    ].copy()

    # Tie-break 2: higher Dice.
    best_dice = float(
        candidates[
            "val_dice"
        ].max()
    )

    candidates = candidates[
        candidates[
            "val_dice"
        ]
        >= (
            best_dice
            - 1e-12
        )
    ].copy()

    # Tie-break 3: earlier epoch.
    selected = (
        candidates
        .sort_values(
            "epoch",
            ascending=True,
        )
        .iloc[
            0
        ]
    )

    return {
        "max_val_dice": max_dice,
        "dice_threshold": threshold,
        "selected_epoch": int(
            selected[
                "epoch"
            ]
        ),
        "selected_val_dice": float(
            selected[
                "val_dice"
            ]
        ),
        "selected_val_iou": float(
            selected[
                "val_iou"
            ]
        ),
        "selected_val_hd95": float(
            selected[
                "val_hd95"
            ]
        ),
        "selected_val_boundary_iou": float(
            selected[
                "val_boundary_iou"
            ]
        ),
        "candidate_count": int(
            (
                history_df[
                    "val_dice"
                ]
                >= threshold
            ).sum()
        ),
    }


# Synthetic selector sanity check:
_selector_test = pd.DataFrame({
    "epoch": [1, 2, 3],
    "val_dice": [0.8479, 0.8472, 0.8420],
    "val_iou": [0.76, 0.76, 0.75],
    "val_hd95": [18.39, 17.75, 17.00],
    "val_boundary_iou": [0.3143, 0.3140, 0.3130],
})

_selector_out = select_boundary_checkpoint(
    _selector_test
)

assert _selector_out[
    "selected_epoch"
] == 2

print(
    "PASS: selector prefers the lower-HD95 checkpoint "
    "when Dice remains within 0.005."
)

PASS: selector prefers the lower-HD95 checkpoint when Dice remains within 0.005.

In [43]:

# ============================================================
# 8. CABLE TRAINING ENGINE — SAVE BOTH CHECKPOINTS
# ============================================================

criterion = nn.CrossEntropyLoss()


def build_optimizer(
    model,
):
    return torch.optim.AdamW(
        model.parameters(),
        lr=cfg.lr,
        weight_decay=cfg.weight_decay,
    )


def build_scheduler(
    optimizer,
):
    return (
        torch.optim
        .lr_scheduler
        .ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=cfg.scheduler_factor,
            patience=cfg.scheduler_patience,
        )
    )


def train_one_epoch(
    model,
    loader,
    optimizer,
    scaler,
):
    model.train()

    losses = []

    for batch_idx, (
        images,
        masks,
        _,
    ) in enumerate(
        loader
    ):
        images = images.to(
            DEVICE,
            non_blocking=True,
        )

        masks = masks.to(
            DEVICE,
            non_blocking=True,
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        with torch.cuda.amp.autocast(
            enabled=(
                cfg.use_amp
                and DEVICE.type
                == "cuda"
            )
        ):
            logits = model(
                images
            )

            loss = criterion(
                logits,
                masks,
            )

        scaler.scale(
            loss
        ).backward()

        scaler.step(
            optimizer
        )

        scaler.update()

        losses.append(
            loss.item()
        )

        if batch_idx % 100 == 0:
            print(
                f"    batch {batch_idx:4d}/{len(loader)} "
                f"loss={loss.item():.4f}",
                flush=True,
            )

    return float(
        np.mean(
            losses
        )
    )


def train_cable_save_two_checkpoints(
    model,
    train_loader,
    val_loader,
    out_dir,
    run_metadata,
):
    """
    One 50-epoch CE training trajectory.

    Saves:
      1) best_val_dice.pt
      2) selected_dice_constrained_boundary.pt

    Test data are not touched here.
    """

    out_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    best_dice_path = (
        out_dir
        / "best_val_dice.pt"
    )

    boundary_path = (
        out_dir
        / "selected_dice_constrained_boundary.pt"
    )

    history_path = (
        out_dir
        / "history.csv"
    )

    optimizer = build_optimizer(
        model
    )

    scheduler = build_scheduler(
        optimizer
    )

    scaler = torch.cuda.amp.GradScaler(
        enabled=(
            cfg.use_amp
            and DEVICE.type == "cuda"
        )
    )

    history = []
    running_max_dice = -np.inf
    best_dice_epoch = -1

    # Candidate checkpoints remain local during the run.
    # Only the two final checkpoints are copied to Drive.
    temp_dir = Path(
        tempfile.mkdtemp(
            prefix="cable_boundary_candidates_"
        )
    )

    candidate_paths = {}

    start_time = time.time()

    try:
        for epoch in range(
            1,
            cfg.epochs + 1,
        ):
            train_loss = train_one_epoch(
                model,
                train_loader,
                optimizer,
                scaler,
            )

            val_summary, _ = evaluate_lesion_loader(
                model,
                val_loader,
            )

            row = {
                "epoch": int(
                    epoch
                ),
                "lr": float(
                    optimizer.param_groups[
                        0
                    ][
                        "lr"
                    ]
                ),
                "train_loss": float(
                    train_loss
                ),
                "val_loss": float(
                    val_summary[
                        "loss"
                    ]
                ),
                "val_dice": float(
                    val_summary[
                        "dice"
                    ]
                ),
                "val_iou": float(
                    val_summary[
                        "iou"
                    ]
                ),
                "val_hd95": float(
                    val_summary[
                        "hd95"
                    ]
                ),
                "val_boundary_iou": float(
                    val_summary[
                        "boundary_iou"
                    ]
                ),
            }

            history.append(
                row
            )

            # ------------------------------------------------
            # Ordinary best-Dice checkpoint — persisted to Drive
            # ------------------------------------------------
            if row[
                "val_dice"
            ] > running_max_dice:
                running_max_dice = row[
                    "val_dice"
                ]

                best_dice_epoch = int(
                    epoch
                )

                torch.save(
                    {
                        "model_state": model.state_dict(),
                        "epoch": int(
                            epoch
                        ),
                        "selection_policy": "max_validation_dice",
                        **run_metadata,
                    },
                    best_dice_path,
                )

            # ------------------------------------------------
            # Boundary-selection candidate checkpoint bookkeeping
            # ------------------------------------------------
            current_threshold = (
                running_max_dice
                - cfg.dice_tolerance
            )

            # Any checkpoint already below the current window can never
            # re-enter the final window because running_max_dice cannot decrease.
            stale_epochs = [
                ep
                for ep, meta
                in candidate_paths.items()
                if meta[
                    "val_dice"
                ]
                < current_threshold
            ]

            for ep in stale_epochs:
                p = candidate_paths[
                    ep
                ][
                    "path"
                ]

                if p.exists():
                    p.unlink()

                del candidate_paths[
                    ep
                ]

            if row[
                "val_dice"
            ] >= current_threshold:
                candidate_path = (
                    temp_dir
                    / f"epoch_{epoch:03d}.pt"
                )

                torch.save(
                    {
                        "model_state": model.state_dict(),
                        "epoch": int(
                            epoch
                        ),
                        "selection_policy": (
                            "dice_constrained_boundary_candidate"
                        ),
                        **run_metadata,
                    },
                    candidate_path,
                )

                candidate_paths[
                    int(
                        epoch
                    )
                ] = {
                    "path": candidate_path,
                    "val_dice": row[
                        "val_dice"
                    ],
                }

            # Persist the history after every epoch so the complete
            # validation trajectory is auditable even if Colab later fails.
            pd.DataFrame(
                history
            ).to_csv(
                history_path,
                index=False,
            )

            print(
                f"Epoch {epoch:02d}/{cfg.epochs} | "
                f"train={train_loss:.4f} | "
                f"Dice={row['val_dice']:.4f} | "
                f"IoU={row['val_iou']:.4f} | "
                f"HD95={row['val_hd95']:.2f} | "
                f"B-IoU={row['val_boundary_iou']:.4f}"
            )

            scheduler.step(
                row[
                    "val_loss"
                ]
            )

        history_df = pd.DataFrame(
            history
        )

        selection = select_boundary_checkpoint(
            history_df
        )

        boundary_epoch = int(
            selection[
                "selected_epoch"
            ]
        )

        assert best_dice_epoch == int(
            history_df.loc[
                history_df[
                    "val_dice"
                ].idxmax(),
                "epoch",
            ]
        )

        assert boundary_epoch in candidate_paths

        shutil.copy2(
            candidate_paths[
                boundary_epoch
            ][
                "path"
            ],
            boundary_path,
        )

        best_row = (
            history_df[
                history_df.epoch
                == best_dice_epoch
            ]
            .iloc[
                0
            ]
        )

        selection.update({
            "best_dice_epoch": int(
                best_dice_epoch
            ),
            "best_dice_val_dice": float(
                best_row.val_dice
            ),
            "best_dice_val_iou": float(
                best_row.val_iou
            ),
            "best_dice_val_hd95": float(
                best_row.val_hd95
            ),
            "best_dice_val_boundary_iou": float(
                best_row.val_boundary_iou
            ),
            "selected_differs_from_best_dice": bool(
                boundary_epoch
                != best_dice_epoch
            ),
            "train_seconds": float(
                time.time()
                - start_time
            ),
        })

        assert best_dice_path.exists()
        assert boundary_path.exists()

        return (
            history_df,
            selection,
            best_dice_path,
            boundary_path,
        )

    finally:
        shutil.rmtree(
            temp_dir,
            ignore_errors=True,
        )

In [44]:

# ============================================================
# 9. FRESH INFERENCE EFFICIENCY BENCHMARK
# ============================================================

@torch.inference_mode()
def benchmark_efficiency(
    model,
    warmup=30,
    runs=100,
    repeats=3,
):
    model.eval()

    row = {
        "latency_ms_median": np.nan,
        "latency_ms_q25": np.nan,
        "latency_ms_q75": np.nan,
        "peak_inference_memory_mb": np.nan,
    }

    if DEVICE.type != "cuda":
        return row

    x = torch.zeros(
        1,
        3,
        cfg.image_size,
        cfg.image_size,
        device=DEVICE,
    )

    for _ in range(
        warmup
    ):
        _ = model(
            x
        )

    torch.cuda.synchronize()
    torch.cuda.reset_peak_memory_stats()

    times = []

    for _ in range(
        repeats
    ):
        for _ in range(
            runs
        ):
            start = torch.cuda.Event(
                enable_timing=True
            )

            end = torch.cuda.Event(
                enable_timing=True
            )

            start.record()
            _ = model(
                x
            )
            end.record()

            torch.cuda.synchronize()

            times.append(
                start.elapsed_time(
                    end
                )
            )

    row.update({
        "latency_ms_median": float(
            np.median(
                times
            )
        ),
        "latency_ms_q25": float(
            np.percentile(
                times,
                25,
            )
        ),
        "latency_ms_q75": float(
            np.percentile(
                times,
                75,
            )
        ),
        "peak_inference_memory_mb": float(
            torch.cuda.max_memory_allocated()
            / (1024 ** 2)
        ),
    })

    return row


efficiency_rows = []

for variant in ARCHITECTURE_VARIANTS:
    set_seed(
        12345
    )

    model = SwiftMSegFamily(
        variant=variant,
        num_classes=cfg.num_classes,
    ).to(
        DEVICE
    )

    efficiency_rows.append({
        "variant": variant,
        "params_M": count_trainable_params(
            model
        ) / 1e6,
        "aggregator_params_M": aggregator_params(
            model
        ) / 1e6,
        "aggregator_GMACs": complexity_lookup[
            variant
        ],
        **benchmark_efficiency(
            model
        ),
    })

    del model
    gc.collect()

    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()


efficiency_df = pd.DataFrame(
    efficiency_rows
)

display(
    efficiency_df
)

efficiency_df.to_csv(
    FINAL_ROOT
    / "EFFICIENCY_FINAL.csv",
    index=False,
)

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,variant,params_M,aggregator_params_M,aggregator_GMACs,latency_ms_median,latency_ms_q25,latency_ms_q75,peak_inference_memory_mb
0,swift_lgl,4.485282,0.399360,1.312145,13.921840,12.009272,23.103505,47.674805
1,mhtm_hybrid_final,4.481858,0.395936,0.225690,13.944832,13.453712,15.849600,47.658691
2,cable_s1,4.487235,0.401313,0.231195,12.685904,12.395936,13.171128,47.681641

In [45]:

# ============================================================
# 10. AUTHORITATIVE BASELINE ARTIFACT AUDIT
# ============================================================

def bra_baseline_dir(
    fold,
    variant,
):
    return (
        OLD_BRA_AUDIT_ROOT
        / "official_cv"
        / f"fold_{fold}"
        / f"seed_{cfg.train_seed}"
        / variant
    )


def uclm_baseline_dir(
    fold,
    variant,
):
    return (
        OLD_UCLM_ROOT
        / "official_cv"
        / f"fold_{fold}"
        / f"seed_{cfg.train_seed}"
        / variant
    )


artifact_rows = []
missing_required = []


for fold in OUTER_FOLDS:
    for variant in BASELINE_VARIANTS:
        # BUS-BRA authoritative CLEAN audit.
        bra_dir = bra_baseline_dir(
            fold,
            variant,
        )

        bra_result = (
            bra_dir
            / "result_clean.json"
        )

        bra_per_image = (
            bra_dir
            / "per_image_test_clean.csv"
        )

        for kind, path in [
            (
                "BUS-BRA result_clean",
                bra_result,
            ),
            (
                "BUS-BRA per_image_test_clean",
                bra_per_image,
            ),
        ]:
            artifact_rows.append({
                "dataset": "BUS-BRA",
                "fold": fold,
                "variant": variant,
                "artifact": kind,
                "exists": path.exists(),
                "path": str(
                    path
                ),
            })

            if not path.exists():
                missing_required.append(
                    str(
                        path
                    )
                )

        # BUS-UCLM completed supervised experiment.
        uclm_dir = uclm_baseline_dir(
            fold,
            variant,
        )

        uclm_result = (
            uclm_dir
            / "result.json"
        )

        uclm_lesion = (
            uclm_dir
            / "per_image_test_lesion.csv"
        )

        uclm_normal = (
            uclm_dir
            / "per_image_test_normal.csv"
        )

        for kind, path in [
            (
                "BUS-UCLM result",
                uclm_result,
            ),
            (
                "BUS-UCLM lesion OOF",
                uclm_lesion,
            ),
            (
                "BUS-UCLM normal OOF",
                uclm_normal,
            ),
        ]:
            artifact_rows.append({
                "dataset": "BUS-UCLM",
                "fold": fold,
                "variant": variant,
                "artifact": kind,
                "exists": path.exists(),
                "path": str(
                    path
                ),
            })

            if not path.exists():
                missing_required.append(
                    str(
                        path
                    )
                )


artifact_audit = pd.DataFrame(
    artifact_rows
)

display(
    artifact_audit.groupby(
        [
            "dataset",
            "artifact",
        ]
    )[
        "exists"
    ].agg(
        [
            "sum",
            "count",
        ]
    )
)


if missing_required:
    print(
        "\nMissing authoritative baseline artifacts:"
    )

    for p in missing_required:
        print(
            " -",
            p,
        )

    raise FileNotFoundError(
        "Authoritative Swift/MHTM baseline artifacts are incomplete. "
        "This lean notebook intentionally will NOT retrain them."
    )


print(
    "\nPASS: all authoritative Swift-LGL and MHTM result/per-image "
    "artifacts required for the paper are present."
)


# Exact saved BUS-UCLM outer assignment is also required.
OLD_UCLM_ASSIGNMENT = (
    OLD_UCLM_ROOT
    / "BUSUCLM_OUTER_FOLD_ASSIGNMENT.csv"
)

assert OLD_UCLM_ASSIGNMENT.exists(), (
    "Missing exact previous BUS-UCLM outer-fold assignment:\n"
    f"{OLD_UCLM_ASSIGNMENT}"
)

print(
    "PASS: exact previous BUS-UCLM outer-fold assignment is available."
)

                                       sum  count
dataset  artifact
BUS-BRA  BUS-BRA per_image_test_clean   10     10
         BUS-BRA result_clean           10     10
BUS-UCLM BUS-UCLM lesion OOF            10     10
         BUS-UCLM normal OOF            10     10
         BUS-UCLM result                10     10

PASS: all authoritative Swift-LGL and MHTM result/per-image artifacts required for the paper are present.
PASS: exact previous BUS-UCLM outer-fold assignment is available.

# Part A — BUS-BRA: five new CABLE trainings

In [46]:

# ============================================================
# 11. BUS-BRA DATA
# ============================================================

BUSBRA_ZIP = (
    DRIVE_ROOT
    / "BUSBRA.zip"
)

BUSBRA_LOCAL = (
    LOCAL_ROOT
    / "BUSBRA_DATA"
)

BUSBRA_URL = (
    "https://zenodo.org/records/8231412/"
    "files/BUSBRA.zip?download=1"
)


def download_busbra(
    url,
    dest,
):
    import requests
    from tqdm.auto import tqdm

    if (
        dest.exists()
        and dest.stat().st_size
        > 10_000_000
    ):
        print(
            "Using cached BUS-BRA ZIP:",
            dest,
        )
        return

    print(
        "Downloading BUS-BRA..."
    )

    with requests.get(
        url,
        stream=True,
        timeout=90,
    ) as r:
        r.raise_for_status()

        total = int(
            r.headers.get(
                "content-length",
                0,
            )
        )

        with open(
            dest,
            "wb",
        ) as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=dest.name,
        ) as pbar:
            for chunk in r.iter_content(
                chunk_size=1024 * 1024
            ):
                if chunk:
                    f.write(
                        chunk
                    )

                    pbar.update(
                        len(
                            chunk
                        )
                    )


if RUN_BUSBRA:
    try:
        download_busbra(
            BUSBRA_URL,
            BUSBRA_ZIP,
        )

    except Exception as e:
        raise RuntimeError(
            "Automatic BUS-BRA download failed. "
            "Place BUSBRA.zip at:\n"
            f"{BUSBRA_ZIP}\n"
            f"Original error: {e}"
        )


    if not BUSBRA_LOCAL.exists():
        BUSBRA_LOCAL.mkdir(
            parents=True,
            exist_ok=True,
        )

        with zipfile.ZipFile(
            BUSBRA_ZIP,
            "r",
        ) as zf:
            zf.extractall(
                BUSBRA_LOCAL
            )


EXTRACT_ROOT = BUSBRA_LOCAL

Using cached BUS-BRA ZIP: /content/drive/MyDrive/MHTM_MEDICAL/BUSBRA.zip

In [47]:

# ============================================================
# 12. BUS-BRA OFFICIAL DATA AUDIT
# ============================================================

def find_named(
    root: Path,
    names,
    want_dir=False,
):
    names = {
        x.lower()
        for x in names
    }

    hits = []

    for p in root.rglob("*"):
        if p.name.lower() in names:
            if want_dir and p.is_dir():
                hits.append(p)

            elif (
                (not want_dir)
                and p.is_file()
            ):
                hits.append(p)

    if not hits:
        raise FileNotFoundError(
            f"Could not find {names} under {root}"
        )

    return sorted(
        hits,
        key=lambda p: len(p.parts),
    )[0]


IMAGES_DIR = find_named(
    EXTRACT_ROOT,
    ["Images"],
    want_dir=True,
)

MASKS_DIR = find_named(
    EXTRACT_ROOT,
    ["Masks", "Mask"],
    want_dir=True,
)

FOLDS_CSV = find_named(
    EXTRACT_ROOT,
    ["5-fold-cv.csv"],
    want_dir=False,
)


meta_df = pd.read_csv(
    FOLDS_CSV
)

required = {
    "ID",
    "Pathology",
    "kFold",
}

missing = required - set(
    meta_df.columns
)

assert not missing, (
    f"Missing columns: {missing}"
)


meta_df["Case"] = (
    meta_df["ID"]
    .str.extract(
        r"^(bus_\d+)"
    )[0]
)

assert (
    meta_df["Case"]
    .notna()
    .all()
)


meta_df["kFold"] = pd.to_numeric(
    meta_df["kFold"],
    errors="raise",
).astype(int)


def image_path(sample_id):
    candidates = [
        IMAGES_DIR / f"{sample_id}.png",
        IMAGES_DIR / f"{sample_id}.jpg",
        IMAGES_DIR / f"{sample_id}.jpeg",
    ]

    for p in candidates:
        if p.exists():
            return p

    raise FileNotFoundError(
        sample_id
    )


def mask_path(sample_id):
    suffix = sample_id.replace(
        "bus_",
        "",
    )

    candidates = [
        MASKS_DIR / f"mask_{suffix}.png",
        MASKS_DIR / f"{sample_id}_mask.png",
    ]

    for p in candidates:
        if p.exists():
            return p

    raise FileNotFoundError(
        sample_id
    )


assert len(meta_df) == 1875
assert meta_df["Case"].nunique() == 1064

assert sorted(
    meta_df["kFold"]
    .unique()
    .tolist()
) == [1, 2, 3, 4, 5]


# Verify every image-mask pair before training.
for sid in meta_df["ID"]:
    _ = image_path(sid)
    _ = mask_path(sid)


print("Images   :", len(meta_df))
print(
    "Patients :",
    meta_df["Case"].nunique(),
)
print("Images dir:", IMAGES_DIR)
print("Masks dir :", MASKS_DIR)

display(
    meta_df.head()
)

Images   : 1875
Patients : 1064
Images dir: /content/MHTM_MEDICAL/BUSBRA_DATA/BUSBRA/Images
Masks dir : /content/MHTM_MEDICAL/BUSBRA_DATA/BUSBRA/Masks

,ID,Pathology,kFold,valid_1,valid_2,valid_3,valid_4,valid_5,Case
0,bus_0001-l,malignant,3,1.0,1.0,NaN,1.0,1.0,bus_0001
1,bus_0001-r,malignant,3,1.0,1.0,NaN,1.0,1.0,bus_0001
2,bus_0002-l,benign,5,1.0,1.0,1.0,1.0,NaN,bus_0002
3,bus_0002-r,benign,5,1.0,1.0,0.0,1.0,NaN,bus_0002
4,bus_0003-l,malignant,4,0.0,1.0,0.0,NaN,1.0,bus_0003

In [48]:

# ============================================================
# 13. BUS-BRA OFFICIAL-FOLD SPLIT BUILDER
# ============================================================

# First verify that the supplied official folds themselves are patient-disjoint.
case_fold_count = (
    meta_df
    .groupby("Case")["kFold"]
    .nunique()
)

assert (
    case_fold_count.max() == 1
), (
    "Official BUS-BRA kFold assignment is not "
    "patient-disjoint under the parsed patient IDs."
)

print(
    "PASS: official BUS-BRA outer folds are patient-disjoint."
)


def make_official_cv_split(
    full_df,
    outer_fold,
    inner_seed,
):
    outer_fold = int(
        outer_fold
    )

    test_df = (
        full_df[
            full_df["kFold"]
            == outer_fold
        ]
        .copy()
        .reset_index(drop=True)
    )

    pool_df = (
        full_df[
            full_df["kFold"]
            != outer_fold
        ]
        .copy()
        .reset_index(drop=True)
    )

    inner = StratifiedGroupKFold(
        n_splits=5,
        shuffle=True,
        random_state=(
            inner_seed
            + outer_fold
        ),
    )

    train_idx, val_idx = next(
        inner.split(
            X=pool_df,
            y=pool_df["Pathology"],
            groups=pool_df["Case"],
        )
    )

    train_df = (
        pool_df
        .iloc[train_idx]
        .copy()
        .reset_index(drop=True)
    )

    val_df = (
        pool_df
        .iloc[val_idx]
        .copy()
        .reset_index(drop=True)
    )

    tr = set(train_df.Case)
    va = set(val_df.Case)
    te = set(test_df.Case)

    assert tr.isdisjoint(va)
    assert tr.isdisjoint(te)
    assert va.isdisjoint(te)

    assert (
        len(train_df)
        + len(val_df)
        + len(test_df)
        == len(full_df)
    )

    return (
        train_df,
        val_df,
        test_df,
    )


print("\nOfficial outer folds:")

display(
    meta_df
    .groupby("kFold")
    .agg(
        images=("ID", "size"),
        patients=("Case", "nunique"),
        malignant=(
            "Pathology",
            lambda s: (
                s.astype(str)
                .str.lower()
                == "malignant"
            ).sum(),
        ),
        benign=(
            "Pathology",
            lambda s: (
                s.astype(str)
                .str.lower()
                == "benign"
            ).sum(),
        ),
    )
)


print("\nFull strict split audit:")

split_audit_rows = []

for fold in OUTER_FOLDS:
    tr, va, te = make_official_cv_split(
        meta_df,
        fold,
        cfg.busbra_inner_val_seed,
    )

    row = {
        "fold": fold,
        "train_images": len(tr),
        "val_images": len(va),
        "test_images": len(te),
        "train_patients": tr.Case.nunique(),
        "val_patients": va.Case.nunique(),
        "test_patients": te.Case.nunique(),
    }

    split_audit_rows.append(
        row
    )

    print(
        f"Fold {fold}: "
        f"train={len(tr)} ({tr.Case.nunique()} patients) | "
        f"val={len(va)} ({va.Case.nunique()} patients) | "
        f"test={len(te)} ({te.Case.nunique()} patients)"
    )


split_audit_df = pd.DataFrame(
    split_audit_rows
)

display(
    split_audit_df
)

PASS: official BUS-BRA outer folds are patient-disjoint.

Official outer folds:

       images  patients  malignant  benign
kFold
1         376       212        122     254
2         385       213        125     260
3         366       213        120     246
4         365       214        119     246
5         383       212        121     262

Full strict split audit:
Fold 1: train=1200 (682 patients) | val=299 (170 patients) | test=376 (212 patients)
Fold 2: train=1196 (681 patients) | val=294 (170 patients) | test=385 (213 patients)
Fold 3: train=1206 (681 patients) | val=303 (170 patients) | test=366 (213 patients)
Fold 4: train=1210 (680 patients) | val=300 (170 patients) | test=365 (214 patients)
Fold 5: train=1194 (681 patients) | val=298 (171 patients) | test=383 (212 patients)

,fold,train_images,val_images,test_images,train_patients,val_patients,test_patients
0,1,1200,299,376,682,170,212
1,2,1196,294,385,681,170,213
2,3,1206,303,366,681,170,213
3,4,1210,300,365,680,170,214
4,5,1194,298,383,681,171,212

In [49]:

# ============================================================
# 14. BUS-BRA DATASET + TRANSFORMS
# ============================================================

def get_transforms(train=False):
    ops = [
        A.Resize(
            cfg.image_size,
            cfg.image_size,
        ),
    ]

    if train:
        ops += [
            A.HorizontalFlip(
                p=0.5
            ),
            A.RandomRotate90(
                p=0.5
            ),
        ]

    ops += [
        A.Normalize(
            mean=(
                0.485,
                0.456,
                0.406,
            ),
            std=(
                0.229,
                0.224,
                0.225,
            ),
        ),
        ToTensorV2(),
    ]

    return A.Compose(
        ops
    )


TRAIN_TRANSFORM = get_transforms(
    train=True
)

EVAL_TRANSFORM = get_transforms(
    train=False
)


class BUSBRADataset(Dataset):
    def __init__(
        self,
        df,
        train=False,
    ):
        self.df = (
            df
            .reset_index(drop=True)
        )

        self.transform = (
            TRAIN_TRANSFORM
            if train
            else EVAL_TRANSFORM
        )

    def __len__(self):
        return len(
            self.df
        )

    def __getitem__(self, idx):
        row = self.df.iloc[
            idx
        ]

        image = cv2.imread(
            str(image_path(row.ID)),
            cv2.IMREAD_COLOR,
        )

        if image is None:
            raise RuntimeError(
                f"Could not read image: {row.ID}"
            )

        image = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB,
        )

        mask = cv2.imread(
            str(mask_path(row.ID)),
            cv2.IMREAD_GRAYSCALE,
        )

        if mask is None:
            raise RuntimeError(
                f"Could not read mask: {row.ID}"
            )

        # Encoding adapter only.
        mask = (
            mask > 0
        ).astype(
            np.uint8
        )

        aug = self.transform(
            image=image,
            mask=mask,
        )

        image = (
            aug["image"]
            .float()
        )

        mask = (
            aug["mask"]
            .long()
        )

        meta = {
            "id": str(row.ID),
            "patient": str(row.Case),
            "pathology": str(row.Pathology).lower(),
        }

        return (
            image,
            mask,
            meta,
        )


def make_loaders(
    train_df,
    val_df,
    test_df,
    run_seed,
):
    train_ds = BUSBRADataset(
        train_df,
        train=True,
    )

    val_ds = BUSBRADataset(
        val_df,
        train=False,
    )

    test_ds = BUSBRADataset(
        test_df,
        train=False,
    )

    g = torch.Generator()
    g.manual_seed(
        run_seed
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=cfg.busbra_num_workers,
        pin_memory=(
            DEVICE.type == "cuda"
        ),
        drop_last=True,
        generator=g,
        worker_init_fn=seed_worker,
    )

    eval_kwargs = dict(
        batch_size=cfg.eval_batch_size,
        shuffle=False,
        num_workers=cfg.busbra_num_workers,
        pin_memory=(
            DEVICE.type == "cuda"
        ),
        drop_last=False,
        worker_init_fn=seed_worker,
    )

    val_loader = DataLoader(
        val_ds,
        **eval_kwargs,
    )

    test_loader = DataLoader(
        test_ds,
        **eval_kwargs,
    )

    return (
        train_loader,
        val_loader,
        test_loader,
    )

In [16]:

# ============================================================
# 14B. BUS-BRA PRE-FLIGHT INTERFACE CHECK
# ============================================================

_pre_tr, _pre_va, _pre_te = make_official_cv_split(
    meta_df,
    OUTER_FOLDS[0],
    cfg.busbra_inner_val_seed,
)

(
    _pre_train_loader,
    _pre_val_loader,
    _pre_test_loader,
) = make_loaders(
    _pre_tr,
    _pre_va,
    _pre_te,
    cfg.train_seed,
)

_pre_images, _pre_masks, _pre_meta = next(
    iter(
        _pre_val_loader
    )
)

assert _pre_images.ndim == 4
assert _pre_images.shape[1] == 3
assert _pre_masks.ndim == 3

assert set(
    _pre_meta.keys()
) == {
    "id",
    "patient",
    "pathology",
}, _pre_meta.keys()

assert len(
    _pre_meta["id"]
) == _pre_images.shape[0]

assert len(
    _pre_meta["patient"]
) == _pre_images.shape[0]

print(
    "PASS: BUS-BRA loader/evaluator interface is consistent."
)

print(
    "Example metadata:",
    {
        key: _pre_meta[key][0]
        for key in _pre_meta
    },
)

del (
    _pre_train_loader,
    _pre_val_loader,
    _pre_test_loader,
    _pre_images,
    _pre_masks,
    _pre_meta,
)

PASS: BUS-BRA loader/evaluator interface is consistent.
Example metadata: {'id': 'bus_0002-l', 'patient': 'bus_0002', 'pathology': 'benign'}

In [51]:

# ============================================================
# 15. BUS-BRA CABLE-ONLY FINAL RUN
# ============================================================

def busbra_cable_run_dir(
    fold,
):
    return (
        BUSBRA_FINAL_ROOT
        / f"fold_{fold}"
        / f"seed_{cfg.train_seed}"
        / CABLE_VARIANT
    )


def load_model_checkpoint(
    model,
    checkpoint_path,
):
    try:
        payload = torch.load(
            checkpoint_path,
            map_location=DEVICE,
            weights_only=False,
        )

    except TypeError:
        payload = torch.load(
            checkpoint_path,
            map_location=DEVICE,
        )

    incompatible = model.load_state_dict(
        payload[
            "model_state"
        ],
        strict=True,
    )

    assert len(
        incompatible.missing_keys
    ) == 0

    assert len(
        incompatible.unexpected_keys
    ) == 0

    return payload


def run_busbra_cable_fold(
    fold,
):
    out_dir = busbra_cable_run_dir(
        fold
    )

    out_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    result_path = (
        out_dir
        / "result_two_operating_points.json"
    )

    history_path = (
        out_dir
        / "history.csv"
    )

    selection_path = (
        out_dir
        / "selection.json"
    )

    best_dice_ckpt = (
        out_dir
        / "best_val_dice.pt"
    )

    boundary_ckpt = (
        out_dir
        / "selected_dice_constrained_boundary.pt"
    )

    dice_detail_path = (
        out_dir
        / "per_image_test_dice.csv"
    )

    boundary_detail_path = (
        out_dir
        / "per_image_test_boundary.csv"
    )

    dice_mask_path = (
        out_dir
        / "pred_masks_test_dice_256.npz"
    )

    boundary_mask_path = (
        out_dir
        / "pred_masks_test_boundary_256.npz"
    )

    complete = all(
        p.exists()
        for p in [
            result_path,
            history_path,
            selection_path,
            best_dice_ckpt,
            boundary_ckpt,
            dice_detail_path,
            boundary_detail_path,
            dice_mask_path,
            boundary_mask_path,
        ]
    )

    if (
        complete
        and not FORCE_RERUN
    ):
        print(
            f"REUSE BUS-BRA CABLE | fold={fold}"
        )

        with open(
            result_path,
            "r",
        ) as f:
            return json.load(
                f
            )


    train_df, val_df, test_df = make_official_cv_split(
        meta_df,
        fold,
        cfg.busbra_inner_val_seed,
    )

    set_seed(
        cfg.train_seed
    )

    (
        train_loader,
        val_loader,
        test_loader,
    ) = make_loaders(
        train_df,
        val_df,
        test_df,
        cfg.train_seed,
    )

    model = SwiftMSegFamily(
        variant=CABLE_VARIANT,
        num_classes=cfg.num_classes,
    ).to(
        DEVICE
    )

    run_metadata = {
        "dataset": "BUS-BRA",
        "outer_fold": int(
            fold
        ),
        "variant": CABLE_VARIANT,
        "train_seed": int(
            cfg.train_seed
        ),
    }

    print(
        "\n"
        + "=" * 100
    )

    print(
        f"TRAIN CABLE ONLY | BUS-BRA | fold={fold}"
    )

    print(
        "=" * 100
    )

    (
        history_df,
        selection,
        best_dice_path,
        boundary_path,
    ) = train_cable_save_two_checkpoints(
        model,
        train_loader,
        val_loader,
        out_dir,
        run_metadata,
    )

    history_df.to_csv(
        history_path,
        index=False,
    )

    with open(
        selection_path,
        "w",
    ) as f:
        json.dump(
            selection,
            f,
            indent=2,
        )


    # --------------------------------------------------------
    # 1) FAIR MAIN-TABLE OPERATING POINT: maximum validation Dice
    # --------------------------------------------------------
    payload_dice = load_model_checkpoint(
        model,
        best_dice_path,
    )

    dice_summary, dice_details = evaluate_lesion_loader(
        model,
        test_loader,
        save_masks_path=dice_mask_path,
    )

    dice_details = dice_details.assign(
        dataset="BUS-BRA",
        fold=int(
            fold
        ),
        train_seed=int(
            cfg.train_seed
        ),
        variant=CABLE_VARIANT,
        operating_point="dice",
    )

    dice_details.to_csv(
        dice_detail_path,
        index=False,
    )


    # --------------------------------------------------------
    # 2) ULTRASOUND BOUNDARY-AWARE OPERATING POINT
    # --------------------------------------------------------
    payload_boundary = load_model_checkpoint(
        model,
        boundary_path,
    )

    boundary_summary, boundary_details = evaluate_lesion_loader(
        model,
        test_loader,
        save_masks_path=boundary_mask_path,
    )

    boundary_details = boundary_details.assign(
        dataset="BUS-BRA",
        fold=int(
            fold
        ),
        train_seed=int(
            cfg.train_seed
        ),
        variant=CABLE_VARIANT,
        operating_point="boundary",
    )

    boundary_details.to_csv(
        boundary_detail_path,
        index=False,
    )


    result = {
        "dataset": "BUS-BRA",
        "fold": int(
            fold
        ),
        "variant": CABLE_VARIANT,
        "train_seed": int(
            cfg.train_seed
        ),

        "n_train_images": int(
            len(
                train_df
            )
        ),
        "n_val_images": int(
            len(
                val_df
            )
        ),
        "n_test_images": int(
            len(
                test_df
            )
        ),

        **selection,

        "dice_checkpoint_epoch": int(
            payload_dice[
                "epoch"
            ]
        ),

        "boundary_checkpoint_epoch": int(
            payload_boundary[
                "epoch"
            ]
        ),

        "dice_test_dice": dice_summary[
            "dice"
        ],
        "dice_test_iou": dice_summary[
            "iou"
        ],
        "dice_test_hd95": dice_summary[
            "hd95"
        ],
        "dice_test_boundary_iou": dice_summary[
            "boundary_iou"
        ],

        "boundary_test_dice": boundary_summary[
            "dice"
        ],
        "boundary_test_iou": boundary_summary[
            "iou"
        ],
        "boundary_test_hd95": boundary_summary[
            "hd95"
        ],
        "boundary_test_boundary_iou": boundary_summary[
            "boundary_iou"
        ],

        "params_M": float(
            architecture_audit.loc[
                architecture_audit.variant
                == CABLE_VARIANT,
                "params_M",
            ].iloc[
                0
            ]
        ),

        "aggregator_GMACs": float(
            complexity_lookup[
                CABLE_VARIANT
            ]
        ),

        "context_scale_dice_checkpoint": float(
            model.aggregators[
                0
            ].context_scale.detach().cpu()
        ),

        "best_dice_checkpoint": str(
            best_dice_path
        ),

        "boundary_checkpoint": str(
            boundary_path
        ),
    }


    with open(
        result_path,
        "w",
    ) as f:
        json.dump(
            result,
            f,
            indent=2,
        )


    print(
        json.dumps(
            {
                "fold": fold,
                "Dice checkpoint epoch": result[
                    "dice_checkpoint_epoch"
                ],
                "Boundary checkpoint epoch": result[
                    "boundary_checkpoint_epoch"
                ],
                "CABLE-Dice test Dice": result[
                    "dice_test_dice"
                ],
                "CABLE-Dice test HD95": result[
                    "dice_test_hd95"
                ],
                "CABLE-Boundary test Dice": result[
                    "boundary_test_dice"
                ],
                "CABLE-Boundary test HD95": result[
                    "boundary_test_hd95"
                ],
            },
            indent=2,
        )
    )


    del (
        model,
        train_loader,
        val_loader,
        test_loader,
        payload_dice,
        payload_boundary,
    )

    gc.collect()

    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()


    return result

In [18]:

# ============================================================
# 16. RUN THE FIVE BUS-BRA CABLE FOLDS
# ============================================================

busbra_cable_results = []

if RUN_BUSBRA:
    for fold in OUTER_FOLDS:
        busbra_cable_results.append(
            run_busbra_cable_fold(
                fold
            )
        )

    busbra_cable_results_df = (
        pd.DataFrame(
            busbra_cable_results
        )
        .sort_values(
            "fold"
        )
        .reset_index(
            drop=True
        )
    )

    assert len(
        busbra_cable_results_df
    ) == 5

    busbra_cable_results_df.to_csv(
        BUSBRA_FINAL_ROOT
        / "CABLE_ALL_FOLD_RESULTS.csv",
        index=False,
    )

    display(
        busbra_cable_results_df[
            [
                "fold",
                "dice_checkpoint_epoch",
                "boundary_checkpoint_epoch",
                "selected_differs_from_best_dice",
                "dice_test_dice",
                "dice_test_hd95",
                "boundary_test_dice",
                "boundary_test_hd95",
            ]
        ]
    )

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

====================================================================================================
TRAIN CABLE ONLY | BUS-BRA | fold=1
====================================================================================================
    batch    0/600 loss=0.6981
    batch  100/600 loss=0.2226
    batch  200/600 loss=0.2680
    batch  300/600 loss=0.2906
    batch  400/600 loss=0.1800
    batch  500/600 loss=0.0926
Epoch 01/50 | train=0.2403 | Dice=0.0069 | IoU=0.0038 | HD95=309.71 | B-IoU=0.0003
    batch    0/600 loss=0.1743
    batch  100/600 loss=0.1507
    batch  200/600 loss=0.2342
    batch  300/600 loss=0.1413
    batch  400/600 loss=0.1416
    batch  500/600 loss=0.1285
Epoch 02/50 | train=0.1990 | Dice=0.2552 | IoU=0.1878 | HD95=118.25 | B-IoU=0.0500
    batch    0/600 loss=0.1532
    batch  100/600 loss=0.3042
    batch  200/600 loss=0.3022
    batch  300/600 loss=0.0859
    batch  400/600 loss=0.1154
    batch  500/600 loss=0.0499
Epoch 03/50 | train=0.1706 | Dice=0.6447 | IoU=0.5174 | HD95=41.07 | B-IoU=0.1391
    batch    0/600 loss=0.0924
    batch  100/600 loss=0.2118
    batch  200/600 loss=0.1238
    batch  300/600 loss=0.0622
    batch  400/600 loss=0.0597
    batch  500/600 loss=0.1113
Epoch 04/50 | train=0.1453 | Dice=0.5001 | IoU=0.3794 | HD95=47.22 | B-IoU=0.0931
    batch    0/600 loss=0.1005
    batch  100/600 loss=0.0544
    batch  200/600 loss=0.1190
    batch  300/600 loss=0.2029
    batch  400/600 loss=0.3246
    batch  500/600 loss=0.1040
Epoch 05/50 | train=0.1393 | Dice=0.6659 | IoU=0.5481 | HD95=35.13 | B-IoU=0.1679
    batch    0/600 loss=0.1054
    batch  100/600 loss=0.1264
    batch  200/600 loss=0.0779
    batch  300/600 loss=0.1013
    batch  400/600 loss=0.0504
    batch  500/600 loss=0.0966
Epoch 06/50 | train=0.1229 | Dice=0.7090 | IoU=0.5933 | HD95=31.43 | B-IoU=0.1738
    batch    0/600 loss=0.0910
    batch  100/600 loss=0.0789
    batch  200/600 loss=0.0467
    batch  300/600 loss=0.0767
    batch  400/600 loss=0.0705
    batch  500/600 loss=0.1127
Epoch 07/50 | train=0.1141 | Dice=0.7255 | IoU=0.6077 | HD95=47.68 | B-IoU=0.1946
    batch    0/600 loss=0.0358
    batch  100/600 loss=0.0889
    batch  200/600 loss=0.1260
    batch  300/600 loss=0.2041
    batch  400/600 loss=0.1291
    batch  500/600 loss=0.0814
Epoch 08/50 | train=0.1095 | Dice=0.7485 | IoU=0.6419 | HD95=29.91 | B-IoU=0.2285
    batch    0/600 loss=0.0249
    batch  100/600 loss=0.4073
    batch  200/600 loss=0.0478
    batch  300/600 loss=0.0762
    batch  400/600 loss=0.0743
    batch  500/600 loss=0.0416
Epoch 09/50 | train=0.1091 | Dice=0.7515 | IoU=0.6329 | HD95=36.41 | B-IoU=0.1967
    batch    0/600 loss=0.0620
    batch  100/600 loss=0.0646
    batch  200/600 loss=0.1034
    batch  300/600 loss=0.0439
    batch  400/600 loss=0.0359
    batch  500/600 loss=0.0378
Epoch 10/50 | train=0.1052 | Dice=0.7666 | IoU=0.6577 | HD95=31.56 | B-IoU=0.2279
    batch    0/600 loss=0.0688
    batch  100/600 loss=0.0691
    batch  200/600 loss=0.0853
    batch  300/600 loss=0.0807
    batch  400/600 loss=0.0883
    batch  500/600 loss=0.0644
Epoch 11/50 | train=0.1011 | Dice=0.7859 | IoU=0.6841 | HD95=26.08 | B-IoU=0.2530
    batch    0/600 loss=0.0399
    batch  100/600 loss=0.0840
    batch  200/600 loss=0.3743
    batch  300/600 loss=0.0390
    batch  400/600 loss=0.0395
    batch  500/600 loss=0.0561
Epoch 12/50 | train=0.0974 | Dice=0.6909 | IoU=0.5768 | HD95=30.73 | B-IoU=0.1793
    batch    0/600 loss=0.0596
    batch  100/600 loss=0.0553
    batch  200/600 loss=0.2221
    batch  300/600 loss=0.0222
    batch  400/600 loss=0.0470
    batch  500/600 loss=0.0955
Epoch 13/50 | train=0.0945 | Dice=0.7981 | IoU=0.6982 | HD95=25.15 | B-IoU=0.2634
    batch    0/600 loss=0.0176
    batch  100/600 loss=0.0802
    batch  200/600 loss=0.0641
    batch  300/600 loss=0.0792
    batch  400/600 loss=0.2974
    batch  500/600 loss=0.0480
Epoch 14/50 | train=0.0945 | Dice=0.7808 | IoU=0.6772 | HD95=25.35 | B-IoU=0.2448
    batch    0/600 loss=0.0642
    batch  100/600 loss=0.1441
    batch  200/600 loss=0.0380
    batch  300/600 loss=0.0768
    batch  400/600 loss=0.0898
    batch  500/600 loss=0.0660
Epoch 15/50 | train=0.0884 | Dice=0.8019 | IoU=0.7040 | HD95=25.47 | B-IoU=0.2727
    batch    0/600 loss=0.0475
    batch  100/600 loss=0.0725
    batch  200/600 loss=0.0345
    batch  300/600 loss=0.1286
    batch  400/600 loss=0.0364
    batch  500/600 loss=0.0799
Epoch 16/50 | train=0.0908 | Dice=0.7970 | IoU=0.6960 | HD95=29.42 | B-IoU=0.2578
    batch    0/600 loss=0.1638
    batch  100/600 loss=0.0332
    batch  200/600 loss=0.1518
    batch  300/600 loss=0.0509
    batch  400/600 loss=0.0359
    batch  500/600 loss=0.0365
Epoch 17/50 | train=0.0893 | Dice=0.7305 | IoU=0.6206 | HD95=28.77 | B-IoU=0.2110
    batch    0/600 loss=0.0160
    batch  100/600 loss=0.3914
    batch  200/600 loss=0.0342
    batch  300/600 loss=0.0304
    batch  400/600 loss=0.1957
    batch  500/600 loss=0.1029
Epoch 18/50 | train=0.0883 | Dice=0.7557 | IoU=0.6491 | HD95=27.42 | B-IoU=0.2331
    batch    0/600 loss=0.0478
    batch  100/600 loss=0.1657
    batch  200/600 loss=0.0728
    batch  300/600 loss=0.0201
    batch  400/600 loss=0.0170
    batch  500/600 loss=0.0321
Epoch 19/50 | train=0.0830 | Dice=0.7948 | IoU=0.6913 | HD95=26.81 | B-IoU=0.2585
    batch    0/600 loss=0.0441
    batch  100/600 loss=0.3097
    batch  200/600 loss=0.0864
    batch  300/600 loss=0.0593
    batch  400/600 loss=0.0545
    batch  500/600 loss=0.0371
Epoch 20/50 | train=0.0843 | Dice=0.7573 | IoU=0.6543 | HD95=23.99 | B-IoU=0.2347
    batch    0/600 loss=0.1114
    batch  100/600 loss=0.0570
    batch  200/600 loss=0.3054
    batch  300/600 loss=0.1102
    batch  400/600 loss=0.0618
    batch  500/600 loss=0.0370
Epoch 21/50 | train=0.0814 | Dice=0.8083 | IoU=0.7103 | HD95=26.89 | B-IoU=0.2728
    batch    0/600 loss=0.0423
    batch  100/600 loss=0.0331
    batch  200/600 loss=0.1835
    batch  300/600 loss=0.0391
    batch  400/600 loss=0.1137
    batch  500/600 loss=0.0289
Epoch 22/50 | train=0.0844 | Dice=0.8143 | IoU=0.7172 | HD95=24.38 | B-IoU=0.2783
    batch    0/600 loss=0.0752
    batch  100/600 loss=0.0312
    batch  200/600 loss=0.0400
    batch  300/600 loss=0.0451
    batch  400/600 loss=0.0530
    batch  500/600 loss=0.1587
Epoch 23/50 | train=0.0783 | Dice=0.8320 | IoU=0.7392 | HD95=22.69 | B-IoU=0.2869
    batch    0/600 loss=0.0220
    batch  100/600 loss=0.0161
    batch  200/600 loss=0.0345
    batch  300/600 loss=0.0623
    batch  400/600 loss=0.0274
    batch  500/600 loss=0.0837
Epoch 24/50 | train=0.0790 | Dice=0.7953 | IoU=0.6960 | HD95=23.66 | B-IoU=0.2664
    batch    0/600 loss=0.1310
    batch  100/600 loss=0.0890
    batch  200/600 loss=0.0441
    batch  300/600 loss=0.0277
    batch  400/600 loss=0.0229
    batch  500/600 loss=0.0264
Epoch 25/50 | train=0.0797 | Dice=0.8036 | IoU=0.7066 | HD95=22.59 | B-IoU=0.2752
    batch    0/600 loss=0.0157
    batch  100/600 loss=0.0403
    batch  200/600 loss=0.5338
    batch  300/600 loss=0.0507
    batch  400/600 loss=0.0403
    batch  500/600 loss=0.1373
Epoch 26/50 | train=0.0794 | Dice=0.8291 | IoU=0.7378 | HD95=21.75 | B-IoU=0.2938
    batch    0/600 loss=0.0766
    batch  100/600 loss=0.0963
    batch  200/600 loss=0.0328
    batch  300/600 loss=0.0326
    batch  400/600 loss=0.0620
    batch  500/600 loss=0.0471
Epoch 27/50 | train=0.0766 | Dice=0.7834 | IoU=0.6808 | HD95=24.19 | B-IoU=0.2401
    batch    0/600 loss=0.0462
    batch  100/600 loss=0.2303
    batch  200/600 loss=0.0663
    batch  300/600 loss=0.0529
    batch  400/600 loss=0.0297
    batch  500/600 loss=0.2799
Epoch 28/50 | train=0.0636 | Dice=0.8329 | IoU=0.7441 | HD95=22.50 | B-IoU=0.2972
    batch    0/600 loss=0.0219
    batch  100/600 loss=0.0312
    batch  200/600 loss=0.0574
    batch  300/600 loss=0.0598
    batch  400/600 loss=0.0354
    batch  500/600 loss=0.1014
Epoch 29/50 | train=0.0630 | Dice=0.8389 | IoU=0.7503 | HD95=21.21 | B-IoU=0.3009
    batch    0/600 loss=0.0463
    batch  100/600 loss=0.0683
    batch  200/600 loss=0.0895
    batch  300/600 loss=0.0663
    batch  400/600 loss=0.0394
    batch  500/600 loss=0.0079
Epoch 30/50 | train=0.0600 | Dice=0.8210 | IoU=0.7285 | HD95=21.77 | B-IoU=0.2825
    batch    0/600 loss=0.0428
    batch  100/600 loss=0.0183
    batch  200/600 loss=0.0552
    batch  300/600 loss=0.1175
    batch  400/600 loss=0.0426
    batch  500/600 loss=0.0285
Epoch 31/50 | train=0.0611 | Dice=0.8232 | IoU=0.7312 | HD95=20.02 | B-IoU=0.2904
    batch    0/600 loss=0.0285
    batch  100/600 loss=0.0634
    batch  200/600 loss=0.0132
    batch  300/600 loss=0.0428
    batch  400/600 loss=0.0105
    batch  500/600 loss=0.0174
Epoch 32/50 | train=0.0617 | Dice=0.8378 | IoU=0.7513 | HD95=19.43 | B-IoU=0.3058
    batch    0/600 loss=0.0868
    batch  100/600 loss=0.0524
    batch  200/600 loss=0.0538
    batch  300/600 loss=0.1346
    batch  400/600 loss=0.0350
    batch  500/600 loss=0.0173
Epoch 33/50 | train=0.0596 | Dice=0.8401 | IoU=0.7511 | HD95=21.28 | B-IoU=0.2970
    batch    0/600 loss=0.0451
    batch  100/600 loss=0.0549
    batch  200/600 loss=0.0928
    batch  300/600 loss=0.0202
    batch  400/600 loss=0.0270
    batch  500/600 loss=0.0471
Epoch 34/50 | train=0.0598 | Dice=0.8316 | IoU=0.7393 | HD95=23.92 | B-IoU=0.2835
    batch    0/600 loss=0.0610
    batch  100/600 loss=0.0375
    batch  200/600 loss=0.2968
    batch  300/600 loss=0.0245
    batch  400/600 loss=0.0360
    batch  500/600 loss=0.0370
Epoch 35/50 | train=0.0588 | Dice=0.8353 | IoU=0.7463 | HD95=19.36 | B-IoU=0.3008
    batch    0/600 loss=0.0461
    batch  100/600 loss=0.0914
    batch  200/600 loss=0.0320
    batch  300/600 loss=0.0267
    batch  400/600 loss=0.0273
    batch  500/600 loss=0.0308
Epoch 36/50 | train=0.0578 | Dice=0.8335 | IoU=0.7443 | HD95=21.12 | B-IoU=0.3007
    batch    0/600 loss=0.0280
    batch  100/600 loss=0.1012
    batch  200/600 loss=0.0205
    batch  300/600 loss=0.0771
    batch  400/600 loss=0.0156
    batch  500/600 loss=0.0872
Epoch 37/50 | train=0.0578 | Dice=0.8292 | IoU=0.7379 | HD95=19.67 | B-IoU=0.2942
    batch    0/600 loss=0.0213
    batch  100/600 loss=0.0174
    batch  200/600 loss=0.0645
    batch  300/600 loss=0.0497
    batch  400/600 loss=0.0698
    batch  500/600 loss=0.0416
Epoch 38/50 | train=0.0518 | Dice=0.8445 | IoU=0.7587 | HD95=18.67 | B-IoU=0.3067
    batch    0/600 loss=0.0244
    batch  100/600 loss=0.0093
    batch  200/600 loss=0.0656
    batch  300/600 loss=0.1152
    batch  400/600 loss=0.1587
    batch  500/600 loss=0.0377
Epoch 39/50 | train=0.0518 | Dice=0.8456 | IoU=0.7594 | HD95=19.03 | B-IoU=0.3137
    batch    0/600 loss=0.0335
    batch  100/600 loss=0.0294
    batch  200/600 loss=0.0456
    batch  300/600 loss=0.0560
    batch  400/600 loss=0.0247
    batch  500/600 loss=0.1156
Epoch 40/50 | train=0.0504 | Dice=0.8465 | IoU=0.7610 | HD95=20.29 | B-IoU=0.3105
    batch    0/600 loss=0.0512
    batch  100/600 loss=0.0290
    batch  200/600 loss=0.2194
    batch  300/600 loss=0.0293
    batch  400/600 loss=0.0357
    batch  500/600 loss=0.0796
Epoch 41/50 | train=0.0496 | Dice=0.8470 | IoU=0.7608 | HD95=20.14 | B-IoU=0.3111
    batch    0/600 loss=0.0162
    batch  100/600 loss=0.0353
    batch  200/600 loss=0.0090
    batch  300/600 loss=0.0188
    batch  400/600 loss=0.0322
    batch  500/600 loss=0.0573
Epoch 42/50 | train=0.0467 | Dice=0.8438 | IoU=0.7577 | HD95=18.89 | B-IoU=0.3105
    batch    0/600 loss=0.0904
    batch  100/600 loss=0.0263
    batch  200/600 loss=0.0234
    batch  300/600 loss=0.0537
    batch  400/600 loss=0.0253
    batch  500/600 loss=0.0352
Epoch 43/50 | train=0.0463 | Dice=0.8497 | IoU=0.7649 | HD95=18.46 | B-IoU=0.3150
    batch    0/600 loss=0.0212
    batch  100/600 loss=0.0212
    batch  200/600 loss=0.0081
    batch  300/600 loss=0.0252
    batch  400/600 loss=0.0548
    batch  500/600 loss=0.1317
Epoch 44/50 | train=0.0455 | Dice=0.8476 | IoU=0.7632 | HD95=18.59 | B-IoU=0.3158
    batch    0/600 loss=0.0369
    batch  100/600 loss=0.0601
    batch  200/600 loss=0.0462
    batch  300/600 loss=0.0556
    batch  400/600 loss=0.0191
    batch  500/600 loss=0.0134
Epoch 45/50 | train=0.0484 | Dice=0.8507 | IoU=0.7664 | HD95=18.77 | B-IoU=0.3175
    batch    0/600 loss=0.0484
    batch  100/600 loss=0.1593
    batch  200/600 loss=0.0497
    batch  300/600 loss=0.0849
    batch  400/600 loss=0.0069
    batch  500/600 loss=0.0144
Epoch 46/50 | train=0.0430 | Dice=0.8491 | IoU=0.7651 | HD95=19.09 | B-IoU=0.3171
    batch    0/600 loss=0.0150
    batch  100/600 loss=0.0467
    batch  200/600 loss=0.0305
    batch  300/600 loss=0.0160
    batch  400/600 loss=0.0650
    batch  500/600 loss=0.0176
Epoch 47/50 | train=0.0437 | Dice=0.8483 | IoU=0.7638 | HD95=18.38 | B-IoU=0.3150
    batch    0/600 loss=0.0183
    batch  100/600 loss=0.0168
    batch  200/600 loss=0.0566
    batch  300/600 loss=0.0255
    batch  400/600 loss=0.0503
    batch  500/600 loss=0.0086
Epoch 48/50 | train=0.0445 | Dice=0.8481 | IoU=0.7638 | HD95=18.00 | B-IoU=0.3171
    batch    0/600 loss=0.0057
    batch  100/600 loss=0.0203
    batch  200/600 loss=0.0606
    batch  300/600 loss=0.0643
    batch  400/600 loss=0.0163
    batch  500/600 loss=0.0307
Epoch 49/50 | train=0.0449 | Dice=0.8493 | IoU=0.7648 | HD95=18.89 | B-IoU=0.3162
    batch    0/600 loss=0.0309
    batch  100/600 loss=0.0112
    batch  200/600 loss=0.0247
    batch  300/600 loss=0.0980
    batch  400/600 loss=0.0194
    batch  500/600 loss=0.0275
Epoch 50/50 | train=0.0404 | Dice=0.8503 | IoU=0.7666 | HD95=19.30 | B-IoU=0.3191
{
  "fold": 1,
  "Dice checkpoint epoch": 45,
  "Boundary checkpoint epoch": 48,
  "CABLE-Dice test Dice": 0.8550434361671339,
  "CABLE-Dice test HD95": 17.635295104773203,
  "CABLE-Boundary test Dice": 0.8577810916701958,
  "CABLE-Boundary test HD95": 16.108929683351786
}

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

====================================================================================================
TRAIN CABLE ONLY | BUS-BRA | fold=2
====================================================================================================
    batch    0/598 loss=0.6990
    batch  100/598 loss=0.1218
    batch  200/598 loss=0.2146
    batch  300/598 loss=0.2358
    batch  400/598 loss=0.1834
    batch  500/598 loss=0.1862
Epoch 01/50 | train=0.2442 | Dice=0.4489 | IoU=0.3189 | HD95=66.38 | B-IoU=0.0650
    batch    0/598 loss=0.1414
    batch  100/598 loss=0.2518
    batch  200/598 loss=0.1652
    batch  300/598 loss=0.1668
    batch  400/598 loss=0.1495
    batch  500/598 loss=0.4664
Epoch 02/50 | train=0.2081 | Dice=0.3719 | IoU=0.2604 | HD95=46.13 | B-IoU=0.0408
    batch    0/598 loss=0.0996
    batch  100/598 loss=0.0843
    batch  200/598 loss=0.1092
    batch  300/598 loss=0.2490
    batch  400/598 loss=0.1620
    batch  500/598 loss=0.1389
Epoch 03/50 | train=0.1918 | Dice=0.6425 | IoU=0.5024 | HD95=68.78 | B-IoU=0.1194
    batch    0/598 loss=0.2411
    batch  100/598 loss=0.1351
    batch  200/598 loss=0.1530
    batch  300/598 loss=0.0950
    batch  400/598 loss=0.2261
    batch  500/598 loss=0.0567
Epoch 04/50 | train=0.1602 | Dice=0.6945 | IoU=0.5580 | HD95=58.43 | B-IoU=0.1328
    batch    0/598 loss=0.1704
    batch  100/598 loss=0.1779
    batch  200/598 loss=0.0543
    batch  300/598 loss=0.1407
    batch  400/598 loss=0.1397
    batch  500/598 loss=0.1362
Epoch 05/50 | train=0.1737 | Dice=0.6145 | IoU=0.4837 | HD95=54.51 | B-IoU=0.1155
    batch    0/598 loss=0.1702
    batch  100/598 loss=0.0932
    batch  200/598 loss=0.1285
    batch  300/598 loss=0.0694
    batch  400/598 loss=0.3240
    batch  500/598 loss=0.2897
Epoch 06/50 | train=0.1497 | Dice=0.6573 | IoU=0.5358 | HD95=32.72 | B-IoU=0.1634
    batch    0/598 loss=0.0451
    batch  100/598 loss=0.0440
    batch  200/598 loss=0.1077
    batch  300/598 loss=0.0694
    batch  400/598 loss=0.0706
    batch  500/598 loss=0.2054
Epoch 07/50 | train=0.1315 | Dice=0.7555 | IoU=0.6331 | HD95=43.10 | B-IoU=0.1945
    batch    0/598 loss=0.1288
    batch  100/598 loss=0.1397
    batch  200/598 loss=0.1118
    batch  300/598 loss=0.0906
    batch  400/598 loss=0.0503
    batch  500/598 loss=0.0177
Epoch 08/50 | train=0.1225 | Dice=0.7647 | IoU=0.6536 | HD95=25.26 | B-IoU=0.2042
    batch    0/598 loss=0.0295
    batch  100/598 loss=0.0354
    batch  200/598 loss=0.1475
    batch  300/598 loss=0.0714
    batch  400/598 loss=0.0992
    batch  500/598 loss=0.1012
Epoch 09/50 | train=0.1176 | Dice=0.8069 | IoU=0.6973 | HD95=27.67 | B-IoU=0.2239
    batch    0/598 loss=0.0429
    batch  100/598 loss=0.0673
    batch  200/598 loss=0.1322
    batch  300/598 loss=0.1612
    batch  400/598 loss=0.0870
    batch  500/598 loss=0.0583
Epoch 10/50 | train=0.1205 | Dice=0.7243 | IoU=0.6107 | HD95=28.96 | B-IoU=0.2068
    batch    0/598 loss=0.0776
    batch  100/598 loss=0.0267
    batch  200/598 loss=0.1620
    batch  300/598 loss=0.0681
    batch  400/598 loss=0.0340
    batch  500/598 loss=0.0638
Epoch 11/50 | train=0.1114 | Dice=0.7785 | IoU=0.6636 | HD95=35.93 | B-IoU=0.2123
    batch    0/598 loss=0.0579
    batch  100/598 loss=0.0231
    batch  200/598 loss=0.0275
    batch  300/598 loss=0.0918
    batch  400/598 loss=0.1244
    batch  500/598 loss=0.0484
Epoch 12/50 | train=0.1061 | Dice=0.7998 | IoU=0.6920 | HD95=32.40 | B-IoU=0.2360
    batch    0/598 loss=0.0495
    batch  100/598 loss=0.0418
    batch  200/598 loss=0.4560
    batch  300/598 loss=0.0906
    batch  400/598 loss=0.0219
    batch  500/598 loss=0.0624
Epoch 13/50 | train=0.1022 | Dice=0.7831 | IoU=0.6757 | HD95=34.33 | B-IoU=0.2261
    batch    0/598 loss=0.0404
    batch  100/598 loss=0.0813
    batch  200/598 loss=0.1289
    batch  300/598 loss=0.0398
    batch  400/598 loss=0.1448
    batch  500/598 loss=0.0645
Epoch 14/50 | train=0.0950 | Dice=0.7340 | IoU=0.6237 | HD95=27.85 | B-IoU=0.2308
    batch    0/598 loss=0.1456
    batch  100/598 loss=0.0475
    batch  200/598 loss=0.0331
    batch  300/598 loss=0.0805
    batch  400/598 loss=0.0949
    batch  500/598 loss=0.0220
Epoch 15/50 | train=0.0868 | Dice=0.8241 | IoU=0.7255 | HD95=23.40 | B-IoU=0.2724
    batch    0/598 loss=0.0384
    batch  100/598 loss=0.0378
    batch  200/598 loss=0.0264
    batch  300/598 loss=0.0933
    batch  400/598 loss=0.0480
    batch  500/598 loss=0.0735
Epoch 16/50 | train=0.0850 | Dice=0.8246 | IoU=0.7235 | HD95=26.59 | B-IoU=0.2609
    batch    0/598 loss=0.0628
    batch  100/598 loss=0.0628
    batch  200/598 loss=0.1220
    batch  300/598 loss=0.0430
    batch  400/598 loss=0.0768
    batch  500/598 loss=0.0967
Epoch 17/50 | train=0.0830 | Dice=0.8293 | IoU=0.7343 | HD95=21.45 | B-IoU=0.2780
    batch    0/598 loss=0.0190
    batch  100/598 loss=0.1382
    batch  200/598 loss=0.0370
    batch  300/598 loss=0.0551
    batch  400/598 loss=0.0590
    batch  500/598 loss=0.0453
Epoch 18/50 | train=0.0803 | Dice=0.8250 | IoU=0.7243 | HD95=23.22 | B-IoU=0.2718
    batch    0/598 loss=0.0545
    batch  100/598 loss=0.0154
    batch  200/598 loss=0.1376
    batch  300/598 loss=0.1445
    batch  400/598 loss=0.1474
    batch  500/598 loss=0.1198
Epoch 19/50 | train=0.0830 | Dice=0.8375 | IoU=0.7420 | HD95=21.22 | B-IoU=0.2843
    batch    0/598 loss=0.0333
    batch  100/598 loss=0.0982
    batch  200/598 loss=0.0154
    batch  300/598 loss=0.0431
    batch  400/598 loss=0.0549
    batch  500/598 loss=0.0244
Epoch 20/50 | train=0.0778 | Dice=0.8029 | IoU=0.7029 | HD95=20.68 | B-IoU=0.2672
    batch    0/598 loss=0.0136
    batch  100/598 loss=0.0604
    batch  200/598 loss=0.0434
    batch  300/598 loss=0.0359
    batch  400/598 loss=0.2348
    batch  500/598 loss=0.0383
Epoch 21/50 | train=0.0780 | Dice=0.8280 | IoU=0.7329 | HD95=22.55 | B-IoU=0.2715
    batch    0/598 loss=0.1068
    batch  100/598 loss=0.0279
    batch  200/598 loss=0.0389
    batch  300/598 loss=0.0653
    batch  400/598 loss=0.0341
    batch  500/598 loss=0.0333
Epoch 22/50 | train=0.0761 | Dice=0.8402 | IoU=0.7468 | HD95=23.49 | B-IoU=0.2922
    batch    0/598 loss=0.0343
    batch  100/598 loss=0.0649
    batch  200/598 loss=0.1222
    batch  300/598 loss=0.0234
    batch  400/598 loss=0.0440
    batch  500/598 loss=0.0481
Epoch 23/50 | train=0.0744 | Dice=0.8321 | IoU=0.7383 | HD95=21.09 | B-IoU=0.2855
    batch    0/598 loss=0.1252
    batch  100/598 loss=0.0292
    batch  200/598 loss=0.0439
    batch  300/598 loss=0.1992
    batch  400/598 loss=0.0184
    batch  500/598 loss=0.0347
Epoch 24/50 | train=0.0772 | Dice=0.8410 | IoU=0.7490 | HD95=20.15 | B-IoU=0.2885
    batch    0/598 loss=0.0684
    batch  100/598 loss=0.0154
    batch  200/598 loss=0.0280
    batch  300/598 loss=0.1220
    batch  400/598 loss=0.0771
    batch  500/598 loss=0.0490
Epoch 25/50 | train=0.0720 | Dice=0.8352 | IoU=0.7442 | HD95=21.41 | B-IoU=0.2924
    batch    0/598 loss=0.0372
    batch  100/598 loss=0.0583
    batch  200/598 loss=0.2233
    batch  300/598 loss=0.0236
    batch  400/598 loss=0.0473
    batch  500/598 loss=0.1187
Epoch 26/50 | train=0.0716 | Dice=0.8378 | IoU=0.7442 | HD95=20.39 | B-IoU=0.2901
    batch    0/598 loss=0.1916
    batch  100/598 loss=0.0179
    batch  200/598 loss=0.1515
    batch  300/598 loss=0.1922
    batch  400/598 loss=0.2976
    batch  500/598 loss=0.1442
Epoch 27/50 | train=0.0708 | Dice=0.8312 | IoU=0.7390 | HD95=18.34 | B-IoU=0.2907
    batch    0/598 loss=0.0369
    batch  100/598 loss=0.0451
    batch  200/598 loss=0.0614
    batch  300/598 loss=0.1030
    batch  400/598 loss=0.0601
    batch  500/598 loss=0.0175
Epoch 28/50 | train=0.0726 | Dice=0.8288 | IoU=0.7349 | HD95=21.73 | B-IoU=0.2930
    batch    0/598 loss=0.1297
    batch  100/598 loss=0.1267
    batch  200/598 loss=0.1269
    batch  300/598 loss=0.1748
    batch  400/598 loss=0.0402
    batch  500/598 loss=0.0874
Epoch 29/50 | train=0.0726 | Dice=0.8317 | IoU=0.7387 | HD95=19.88 | B-IoU=0.2855
    batch    0/598 loss=0.0391
    batch  100/598 loss=0.1242
    batch  200/598 loss=0.0892
    batch  300/598 loss=0.0195
    batch  400/598 loss=0.0354
    batch  500/598 loss=0.0435
Epoch 30/50 | train=0.0633 | Dice=0.8433 | IoU=0.7503 | HD95=21.33 | B-IoU=0.2905
    batch    0/598 loss=0.0729
    batch  100/598 loss=0.0479
    batch  200/598 loss=0.0165
    batch  300/598 loss=0.0729
    batch  400/598 loss=0.0661
    batch  500/598 loss=0.0374
Epoch 31/50 | train=0.0597 | Dice=0.8500 | IoU=0.7584 | HD95=19.62 | B-IoU=0.2963
    batch    0/598 loss=0.1124
    batch  100/598 loss=0.0315
    batch  200/598 loss=0.0659
    batch  300/598 loss=0.0087
    batch  400/598 loss=0.0399
    batch  500/598 loss=0.0621
Epoch 32/50 | train=0.0631 | Dice=0.8446 | IoU=0.7541 | HD95=19.40 | B-IoU=0.2996
    batch    0/598 loss=0.0343
    batch  100/598 loss=0.1168
    batch  200/598 loss=0.0339
    batch  300/598 loss=0.0165
    batch  400/598 loss=0.0411
    batch  500/598 loss=0.0484
Epoch 33/50 | train=0.0587 | Dice=0.8541 | IoU=0.7657 | HD95=19.73 | B-IoU=0.3048
    batch    0/598 loss=0.0332
    batch  100/598 loss=0.0556
    batch  200/598 loss=0.0603
    batch  300/598 loss=0.0338
    batch  400/598 loss=0.0197
    batch  500/598 loss=0.0477
Epoch 34/50 | train=0.0606 | Dice=0.8482 | IoU=0.7576 | HD95=18.47 | B-IoU=0.2988
    batch    0/598 loss=0.0716
    batch  100/598 loss=0.0242
    batch  200/598 loss=0.0349
    batch  300/598 loss=0.0211
    batch  400/598 loss=0.0695
    batch  500/598 loss=0.0755
Epoch 35/50 | train=0.0593 | Dice=0.8527 | IoU=0.7626 | HD95=19.12 | B-IoU=0.2981
    batch    0/598 loss=0.0265
    batch  100/598 loss=0.0821
    batch  200/598 loss=0.0803
    batch  300/598 loss=0.0571
    batch  400/598 loss=0.0322
    batch  500/598 loss=0.0468
Epoch 36/50 | train=0.0579 | Dice=0.8595 | IoU=0.7717 | HD95=19.08 | B-IoU=0.3093
    batch    0/598 loss=0.0623
    batch  100/598 loss=0.0387
    batch  200/598 loss=0.0351
    batch  300/598 loss=0.0163
    batch  400/598 loss=0.0513
    batch  500/598 loss=0.1698
Epoch 37/50 | train=0.0564 | Dice=0.8483 | IoU=0.7596 | HD95=19.04 | B-IoU=0.3024
    batch    0/598 loss=0.0704
    batch  100/598 loss=0.0584
    batch  200/598 loss=0.0296
    batch  300/598 loss=0.2349
    batch  400/598 loss=0.0507
    batch  500/598 loss=0.0249
Epoch 38/50 | train=0.0575 | Dice=0.8533 | IoU=0.7652 | HD95=17.63 | B-IoU=0.3091
    batch    0/598 loss=0.0337
    batch  100/598 loss=0.0150
    batch  200/598 loss=0.0305
    batch  300/598 loss=0.0217
    batch  400/598 loss=0.0267
    batch  500/598 loss=0.1340
Epoch 39/50 | train=0.0559 | Dice=0.8620 | IoU=0.7757 | HD95=17.37 | B-IoU=0.3123
    batch    0/598 loss=0.0545
    batch  100/598 loss=0.0313
    batch  200/598 loss=0.0490
    batch  300/598 loss=0.1454
    batch  400/598 loss=0.0785
    batch  500/598 loss=0.0327
Epoch 40/50 | train=0.0554 | Dice=0.8486 | IoU=0.7609 | HD95=17.00 | B-IoU=0.3047
    batch    0/598 loss=0.0186
    batch  100/598 loss=0.0335
    batch  200/598 loss=0.1232
    batch  300/598 loss=0.1336
    batch  400/598 loss=0.0285
    batch  500/598 loss=0.0245
Epoch 41/50 | train=0.0563 | Dice=0.8602 | IoU=0.7743 | HD95=18.86 | B-IoU=0.3157
    batch    0/598 loss=0.0421
    batch  100/598 loss=0.0524
    batch  200/598 loss=0.0387
    batch  300/598 loss=0.0326
    batch  400/598 loss=0.0581
    batch  500/598 loss=0.0216
Epoch 42/50 | train=0.0551 | Dice=0.8522 | IoU=0.7634 | HD95=18.00 | B-IoU=0.3074
    batch    0/598 loss=0.1094
    batch  100/598 loss=0.0693
    batch  200/598 loss=0.0362
    batch  300/598 loss=0.0388
    batch  400/598 loss=0.0720
    batch  500/598 loss=0.0327
Epoch 43/50 | train=0.0555 | Dice=0.8516 | IoU=0.7623 | HD95=17.61 | B-IoU=0.3038
    batch    0/598 loss=0.0647
    batch  100/598 loss=0.0162
    batch  200/598 loss=0.0215
    batch  300/598 loss=0.0567
    batch  400/598 loss=0.0391
    batch  500/598 loss=0.1114
Epoch 44/50 | train=0.0578 | Dice=0.8491 | IoU=0.7615 | HD95=16.93 | B-IoU=0.3042
    batch    0/598 loss=0.0734
    batch  100/598 loss=0.0209
    batch  200/598 loss=0.0995
    batch  300/598 loss=0.0135
    batch  400/598 loss=0.0619
    batch  500/598 loss=0.0209
Epoch 45/50 | train=0.0545 | Dice=0.8518 | IoU=0.7637 | HD95=22.14 | B-IoU=0.3001
    batch    0/598 loss=0.0421
    batch  100/598 loss=0.0193
    batch  200/598 loss=0.0210
    batch  300/598 loss=0.0337
    batch  400/598 loss=0.1010
    batch  500/598 loss=0.0071
Epoch 46/50 | train=0.0509 | Dice=0.8595 | IoU=0.7740 | HD95=17.96 | B-IoU=0.3155
    batch    0/598 loss=0.0193
    batch  100/598 loss=0.0796
    batch  200/598 loss=0.1130
    batch  300/598 loss=0.0961
    batch  400/598 loss=0.0147
    batch  500/598 loss=0.0352
Epoch 47/50 | train=0.0494 | Dice=0.8585 | IoU=0.7729 | HD95=16.81 | B-IoU=0.3142
    batch    0/598 loss=0.0473
    batch  100/598 loss=0.0600
    batch  200/598 loss=0.0205
    batch  300/598 loss=0.2386
    batch  400/598 loss=0.0301
    batch  500/598 loss=0.0214
Epoch 48/50 | train=0.0519 | Dice=0.8604 | IoU=0.7747 | HD95=16.70 | B-IoU=0.3178
    batch    0/598 loss=0.0223
    batch  100/598 loss=0.0340
    batch  200/598 loss=0.0120
    batch  300/598 loss=0.1081
    batch  400/598 loss=0.0198
    batch  500/598 loss=0.0377
Epoch 49/50 | train=0.0484 | Dice=0.8607 | IoU=0.7748 | HD95=16.51 | B-IoU=0.3186
    batch    0/598 loss=0.0119
    batch  100/598 loss=0.0758
    batch  200/598 loss=0.0128
    batch  300/598 loss=0.0302
    batch  400/598 loss=0.0544
    batch  500/598 loss=0.0230
Epoch 50/50 | train=0.0495 | Dice=0.8615 | IoU=0.7768 | HD95=16.97 | B-IoU=0.3189
{
  "fold": 2,
  "Dice checkpoint epoch": 39,
  "Boundary checkpoint epoch": 49,
  "CABLE-Dice test Dice": 0.8381747648158931,
  "CABLE-Dice test HD95": 20.05113773284125,
  "CABLE-Boundary test Dice": 0.8402213273534448,
  "CABLE-Boundary test HD95": 20.301025547661258
}

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

====================================================================================================
TRAIN CABLE ONLY | BUS-BRA | fold=3
====================================================================================================
    batch    0/603 loss=0.6959
    batch  100/603 loss=0.1923
    batch  200/603 loss=0.1000
    batch  300/603 loss=0.3499
    batch  400/603 loss=0.1681
    batch  500/603 loss=0.2274
    batch  600/603 loss=0.3236
Epoch 01/50 | train=0.2481 | Dice=0.0006 | IoU=0.0003 | HD95=353.34 | B-IoU=0.0001
    batch    0/603 loss=0.1869
    batch  100/603 loss=0.3675
    batch  200/603 loss=0.1417
    batch  300/603 loss=0.1714
    batch  400/603 loss=0.1037
    batch  500/603 loss=0.0851
    batch  600/603 loss=0.2346
Epoch 02/50 | train=0.2059 | Dice=0.4317 | IoU=0.3154 | HD95=61.52 | B-IoU=0.0622
    batch    0/603 loss=0.2629
    batch  100/603 loss=0.1097
    batch  200/603 loss=0.1065
    batch  300/603 loss=0.3226
    batch  400/603 loss=0.0660
    batch  500/603 loss=0.1123
    batch  600/603 loss=0.1060
Epoch 03/50 | train=0.1722 | Dice=0.6895 | IoU=0.5569 | HD95=55.53 | B-IoU=0.1505
    batch    0/603 loss=0.1527
    batch  100/603 loss=0.0832
    batch  200/603 loss=0.1602
    batch  300/603 loss=0.2684
    batch  400/603 loss=0.1788
    batch  500/603 loss=0.0942
    batch  600/603 loss=0.1809
Epoch 04/50 | train=0.1488 | Dice=0.6821 | IoU=0.5473 | HD95=58.14 | B-IoU=0.1477
    batch    0/603 loss=0.1020
    batch  100/603 loss=0.1270
    batch  200/603 loss=0.1795
    batch  300/603 loss=0.0905
    batch  400/603 loss=0.0727
    batch  500/603 loss=0.2457
    batch  600/603 loss=0.0690
Epoch 05/50 | train=0.1435 | Dice=0.6961 | IoU=0.5738 | HD95=34.66 | B-IoU=0.1683
    batch    0/603 loss=0.0813
    batch  100/603 loss=0.1099
    batch  200/603 loss=0.1525
    batch  300/603 loss=0.0499
    batch  400/603 loss=0.0756
    batch  500/603 loss=0.1374
    batch  600/603 loss=0.1463
Epoch 06/50 | train=0.1506 | Dice=0.7070 | IoU=0.5877 | HD95=38.39 | B-IoU=0.1718
    batch    0/603 loss=0.0487
    batch  100/603 loss=0.1216
    batch  200/603 loss=0.0541
    batch  300/603 loss=0.1312
    batch  400/603 loss=0.0416
    batch  500/603 loss=0.1266
    batch  600/603 loss=0.2185
Epoch 07/50 | train=0.1273 | Dice=0.7455 | IoU=0.6304 | HD95=30.83 | B-IoU=0.2014
    batch    0/603 loss=0.1490
    batch  100/603 loss=0.1343
    batch  200/603 loss=0.1620
    batch  300/603 loss=0.0412
    batch  400/603 loss=0.0617
    batch  500/603 loss=0.0523
    batch  600/603 loss=0.2848
Epoch 08/50 | train=0.1185 | Dice=0.7511 | IoU=0.6361 | HD95=41.68 | B-IoU=0.1969
    batch    0/603 loss=0.2088
    batch  100/603 loss=0.0347
    batch  200/603 loss=0.0860
    batch  300/603 loss=0.0626
    batch  400/603 loss=0.0883
    batch  500/603 loss=0.1772
    batch  600/603 loss=0.0359
Epoch 09/50 | train=0.1123 | Dice=0.7892 | IoU=0.6791 | HD95=33.37 | B-IoU=0.2209
    batch    0/603 loss=0.2560
    batch  100/603 loss=0.0638
    batch  200/603 loss=0.1996
    batch  300/603 loss=0.2004
    batch  400/603 loss=0.1141
    batch  500/603 loss=0.0418
    batch  600/603 loss=0.1814
Epoch 10/50 | train=0.1152 | Dice=0.7671 | IoU=0.6540 | HD95=37.14 | B-IoU=0.2263
    batch    0/603 loss=0.0693
    batch  100/603 loss=0.0501
    batch  200/603 loss=0.3055
    batch  300/603 loss=0.0705
    batch  400/603 loss=0.0304
    batch  500/603 loss=0.0466
    batch  600/603 loss=0.0794
Epoch 11/50 | train=0.1045 | Dice=0.7640 | IoU=0.6507 | HD95=41.58 | B-IoU=0.2100
    batch    0/603 loss=0.1585
    batch  100/603 loss=0.0466
    batch  200/603 loss=0.1670
    batch  300/603 loss=0.0719
    batch  400/603 loss=0.0741
    batch  500/603 loss=0.0146
    batch  600/603 loss=0.1147
Epoch 12/50 | train=0.1033 | Dice=0.7961 | IoU=0.6933 | HD95=30.51 | B-IoU=0.2436
    batch    0/603 loss=0.0645
    batch  100/603 loss=0.0716
    batch  200/603 loss=0.0469
    batch  300/603 loss=0.0521
    batch  400/603 loss=0.0501
    batch  500/603 loss=0.2075
    batch  600/603 loss=0.0659
Epoch 13/50 | train=0.0975 | Dice=0.8014 | IoU=0.6979 | HD95=25.81 | B-IoU=0.2514
    batch    0/603 loss=0.0590
    batch  100/603 loss=0.0971
    batch  200/603 loss=0.0672
    batch  300/603 loss=0.1114
    batch  400/603 loss=0.0817
    batch  500/603 loss=0.0290
    batch  600/603 loss=0.0992
Epoch 14/50 | train=0.0982 | Dice=0.8003 | IoU=0.6961 | HD95=31.70 | B-IoU=0.2579
    batch    0/603 loss=0.1546
    batch  100/603 loss=0.1153
    batch  200/603 loss=0.0544
    batch  300/603 loss=0.1392
    batch  400/603 loss=0.1920
    batch  500/603 loss=0.0545
    batch  600/603 loss=0.0605
Epoch 15/50 | train=0.0946 | Dice=0.7858 | IoU=0.6829 | HD95=27.13 | B-IoU=0.2446
    batch    0/603 loss=0.0675
    batch  100/603 loss=0.0979
    batch  200/603 loss=0.2476
    batch  300/603 loss=0.1039
    batch  400/603 loss=0.0603
    batch  500/603 loss=0.0173
    batch  600/603 loss=0.0510
Epoch 16/50 | train=0.0924 | Dice=0.7941 | IoU=0.6924 | HD95=25.40 | B-IoU=0.2463
    batch    0/603 loss=0.0534
    batch  100/603 loss=0.0180
    batch  200/603 loss=0.0728
    batch  300/603 loss=0.0763
    batch  400/603 loss=0.0776
    batch  500/603 loss=0.0299
    batch  600/603 loss=0.0904
Epoch 17/50 | train=0.0948 | Dice=0.7579 | IoU=0.6435 | HD95=43.07 | B-IoU=0.1973
    batch    0/603 loss=0.0541
    batch  100/603 loss=0.0763
    batch  200/603 loss=0.0238
    batch  300/603 loss=0.0273
    batch  400/603 loss=0.1376
    batch  500/603 loss=0.0638
    batch  600/603 loss=0.0879
Epoch 18/50 | train=0.0914 | Dice=0.7526 | IoU=0.6505 | HD95=25.56 | B-IoU=0.2305
    batch    0/603 loss=0.1823
    batch  100/603 loss=0.0420
    batch  200/603 loss=0.0212
    batch  300/603 loss=0.1275
    batch  400/603 loss=0.1579
    batch  500/603 loss=0.0239
    batch  600/603 loss=0.0477
Epoch 19/50 | train=0.0900 | Dice=0.8148 | IoU=0.7124 | HD95=24.83 | B-IoU=0.2628
    batch    0/603 loss=0.0417
    batch  100/603 loss=0.0718
    batch  200/603 loss=0.0853
    batch  300/603 loss=0.1120
    batch  400/603 loss=0.0897
    batch  500/603 loss=0.0681
    batch  600/603 loss=0.1495
Epoch 20/50 | train=0.0896 | Dice=0.7877 | IoU=0.6860 | HD95=24.98 | B-IoU=0.2603
    batch    0/603 loss=0.0673
    batch  100/603 loss=0.0562
    batch  200/603 loss=0.0820
    batch  300/603 loss=0.0528
    batch  400/603 loss=0.0498
    batch  500/603 loss=0.1465
    batch  600/603 loss=0.0245
Epoch 21/50 | train=0.0833 | Dice=0.8186 | IoU=0.7191 | HD95=25.26 | B-IoU=0.2656
    batch    0/603 loss=0.0426
    batch  100/603 loss=0.0544
    batch  200/603 loss=0.0119
    batch  300/603 loss=0.1047
    batch  400/603 loss=0.0540
    batch  500/603 loss=0.0676
    batch  600/603 loss=0.1487
Epoch 22/50 | train=0.0817 | Dice=0.8197 | IoU=0.7205 | HD95=26.17 | B-IoU=0.2747
    batch    0/603 loss=0.0168
    batch  100/603 loss=0.1950
    batch  200/603 loss=0.2230
    batch  300/603 loss=0.0747
    batch  400/603 loss=0.0341
    batch  500/603 loss=0.0901
    batch  600/603 loss=0.0343
Epoch 23/50 | train=0.0838 | Dice=0.7707 | IoU=0.6715 | HD95=25.52 | B-IoU=0.2529
    batch    0/603 loss=0.0414
    batch  100/603 loss=0.0374
    batch  200/603 loss=0.0440
    batch  300/603 loss=0.1132
    batch  400/603 loss=0.0410
    batch  500/603 loss=0.1201
    batch  600/603 loss=0.0838
Epoch 24/50 | train=0.0808 | Dice=0.8245 | IoU=0.7268 | HD95=24.35 | B-IoU=0.2702
    batch    0/603 loss=0.1009
    batch  100/603 loss=0.0453
    batch  200/603 loss=0.0281
    batch  300/603 loss=0.1170
    batch  400/603 loss=0.0354
    batch  500/603 loss=0.2939
    batch  600/603 loss=0.1102
Epoch 25/50 | train=0.0849 | Dice=0.7542 | IoU=0.6473 | HD95=32.22 | B-IoU=0.2229
    batch    0/603 loss=0.0687
    batch  100/603 loss=0.0721
    batch  200/603 loss=0.0538
    batch  300/603 loss=0.0579
    batch  400/603 loss=0.0494
    batch  500/603 loss=0.0215
    batch  600/603 loss=0.0968
Epoch 26/50 | train=0.0830 | Dice=0.8196 | IoU=0.7213 | HD95=28.21 | B-IoU=0.2734
    batch    0/603 loss=0.0470
    batch  100/603 loss=0.0424
    batch  200/603 loss=0.0852
    batch  300/603 loss=0.1461
    batch  400/603 loss=0.0308
    batch  500/603 loss=0.0476
    batch  600/603 loss=0.0313
Epoch 27/50 | train=0.0771 | Dice=0.8222 | IoU=0.7231 | HD95=23.96 | B-IoU=0.2675
    batch    0/603 loss=0.1283
    batch  100/603 loss=0.0493
    batch  200/603 loss=0.0226
    batch  300/603 loss=0.1439
    batch  400/603 loss=0.1206
    batch  500/603 loss=0.0762
    batch  600/603 loss=0.0521
Epoch 28/50 | train=0.0760 | Dice=0.7871 | IoU=0.6797 | HD95=22.18 | B-IoU=0.2334
    batch    0/603 loss=0.0267
    batch  100/603 loss=0.0597
    batch  200/603 loss=0.0599
    batch  300/603 loss=0.0721
    batch  400/603 loss=0.0487
    batch  500/603 loss=0.0440
    batch  600/603 loss=0.0412
Epoch 29/50 | train=0.0751 | Dice=0.8173 | IoU=0.7180 | HD95=23.06 | B-IoU=0.2665
    batch    0/603 loss=0.0228
    batch  100/603 loss=0.0782
    batch  200/603 loss=0.0249
    batch  300/603 loss=0.0200
    batch  400/603 loss=0.0383
    batch  500/603 loss=0.0505
    batch  600/603 loss=0.0481
Epoch 30/50 | train=0.0775 | Dice=0.7783 | IoU=0.6769 | HD95=22.65 | B-IoU=0.2490
    batch    0/603 loss=0.0589
    batch  100/603 loss=0.0389
    batch  200/603 loss=0.0276
    batch  300/603 loss=0.0504
    batch  400/603 loss=0.1515
    batch  500/603 loss=0.0180
    batch  600/603 loss=0.1343
Epoch 31/50 | train=0.0776 | Dice=0.8273 | IoU=0.7325 | HD95=23.53 | B-IoU=0.2795
    batch    0/603 loss=0.0678
    batch  100/603 loss=0.0715
    batch  200/603 loss=0.0548
    batch  300/603 loss=0.0708
    batch  400/603 loss=0.0676
    batch  500/603 loss=0.0615
    batch  600/603 loss=0.0267
Epoch 32/50 | train=0.0731 | Dice=0.8362 | IoU=0.7434 | HD95=21.61 | B-IoU=0.2913
    batch    0/603 loss=0.0229
    batch  100/603 loss=0.0350
    batch  200/603 loss=0.0453
    batch  300/603 loss=0.0430
    batch  400/603 loss=0.0505
    batch  500/603 loss=0.1499
    batch  600/603 loss=0.7388
Epoch 33/50 | train=0.0759 | Dice=0.7963 | IoU=0.6949 | HD95=28.67 | B-IoU=0.2631
    batch    0/603 loss=0.0793
    batch  100/603 loss=0.0625
    batch  200/603 loss=0.0424
    batch  300/603 loss=0.0493
    batch  400/603 loss=0.0157
    batch  500/603 loss=0.0215
    batch  600/603 loss=0.1640
Epoch 34/50 | train=0.0725 | Dice=0.8094 | IoU=0.7101 | HD95=28.63 | B-IoU=0.2694
    batch    0/603 loss=0.0874
    batch  100/603 loss=0.0289
    batch  200/603 loss=0.0931
    batch  300/603 loss=0.0916
    batch  400/603 loss=0.0400
    batch  500/603 loss=0.0208
    batch  600/603 loss=0.0449
Epoch 35/50 | train=0.0711 | Dice=0.8269 | IoU=0.7299 | HD95=23.74 | B-IoU=0.2843
    batch    0/603 loss=0.0541
    batch  100/603 loss=0.0600
    batch  200/603 loss=0.0613
    batch  300/603 loss=0.0562
    batch  400/603 loss=0.0173
    batch  500/603 loss=0.0339
    batch  600/603 loss=0.0609
Epoch 36/50 | train=0.0635 | Dice=0.8355 | IoU=0.7433 | HD95=20.32 | B-IoU=0.2967
    batch    0/603 loss=0.0354
    batch  100/603 loss=0.0769
    batch  200/603 loss=0.0369
    batch  300/603 loss=0.0635
    batch  400/603 loss=0.0377
    batch  500/603 loss=0.0209
    batch  600/603 loss=0.0375
Epoch 37/50 | train=0.0601 | Dice=0.8360 | IoU=0.7424 | HD95=22.09 | B-IoU=0.2917
    batch    0/603 loss=0.0401
    batch  100/603 loss=0.1205
    batch  200/603 loss=0.0667
    batch  300/603 loss=0.0336
    batch  400/603 loss=0.0668
    batch  500/603 loss=0.0430
    batch  600/603 loss=0.0265
Epoch 38/50 | train=0.0603 | Dice=0.8370 | IoU=0.7454 | HD95=20.91 | B-IoU=0.3005
    batch    0/603 loss=0.0257
    batch  100/603 loss=0.0526
    batch  200/603 loss=0.2541
    batch  300/603 loss=0.0282
    batch  400/603 loss=0.0521
    batch  500/603 loss=0.1063
    batch  600/603 loss=0.0231
Epoch 39/50 | train=0.0609 | Dice=0.8358 | IoU=0.7451 | HD95=20.51 | B-IoU=0.2964
    batch    0/603 loss=0.0231
    batch  100/603 loss=0.0358
    batch  200/603 loss=0.0662
    batch  300/603 loss=0.0606
    batch  400/603 loss=0.0611
    batch  500/603 loss=0.1128
    batch  600/603 loss=0.0476
Epoch 40/50 | train=0.0569 | Dice=0.8359 | IoU=0.7434 | HD95=22.93 | B-IoU=0.2935
    batch    0/603 loss=0.0222
    batch  100/603 loss=0.0469
    batch  200/603 loss=0.0439
    batch  300/603 loss=0.0407
    batch  400/603 loss=0.0592
    batch  500/603 loss=0.0190
    batch  600/603 loss=0.0283
Epoch 41/50 | train=0.0583 | Dice=0.8411 | IoU=0.7506 | HD95=20.01 | B-IoU=0.2986
    batch    0/603 loss=0.0396
    batch  100/603 loss=0.0702
    batch  200/603 loss=0.0499
    batch  300/603 loss=0.0210
    batch  400/603 loss=0.0559
    batch  500/603 loss=0.0384
    batch  600/603 loss=0.0684
Epoch 42/50 | train=0.0516 | Dice=0.8350 | IoU=0.7439 | HD95=20.81 | B-IoU=0.2983
    batch    0/603 loss=0.0628
    batch  100/603 loss=0.0450
    batch  200/603 loss=0.0603
    batch  300/603 loss=0.0738
    batch  400/603 loss=0.0845
    batch  500/603 loss=0.0643
    batch  600/603 loss=0.0507
Epoch 43/50 | train=0.0505 | Dice=0.8392 | IoU=0.7470 | HD95=21.92 | B-IoU=0.2924
    batch    0/603 loss=0.0378
    batch  100/603 loss=0.0599
    batch  200/603 loss=0.0207
    batch  300/603 loss=0.0282
    batch  400/603 loss=0.0432
    batch  500/603 loss=0.0549
    batch  600/603 loss=0.0188
Epoch 44/50 | train=0.0516 | Dice=0.8317 | IoU=0.7403 | HD95=20.76 | B-IoU=0.2978
    batch    0/603 loss=0.0310
    batch  100/603 loss=0.0140
    batch  200/603 loss=0.1028
    batch  300/603 loss=0.1240
    batch  400/603 loss=0.0594
    batch  500/603 loss=0.0495
    batch  600/603 loss=0.0101
Epoch 45/50 | train=0.0492 | Dice=0.8323 | IoU=0.7389 | HD95=22.88 | B-IoU=0.2908
    batch    0/603 loss=0.0366
    batch  100/603 loss=0.0270
    batch  200/603 loss=0.0489
    batch  300/603 loss=0.1137
    batch  400/603 loss=0.0510
    batch  500/603 loss=0.0297
    batch  600/603 loss=0.0274
Epoch 46/50 | train=0.0476 | Dice=0.8392 | IoU=0.7482 | HD95=20.77 | B-IoU=0.3000
    batch    0/603 loss=0.0089
    batch  100/603 loss=0.0129
    batch  200/603 loss=0.0405
    batch  300/603 loss=0.0415
    batch  400/603 loss=0.0389
    batch  500/603 loss=0.0574
    batch  600/603 loss=0.0263
Epoch 47/50 | train=0.0491 | Dice=0.8409 | IoU=0.7497 | HD95=19.88 | B-IoU=0.3018
    batch    0/603 loss=0.0619
    batch  100/603 loss=0.0453
    batch  200/603 loss=0.1036
    batch  300/603 loss=0.0843
    batch  400/603 loss=0.0186
    batch  500/603 loss=0.0220
    batch  600/603 loss=0.0234
Epoch 48/50 | train=0.0490 | Dice=0.8446 | IoU=0.7544 | HD95=19.81 | B-IoU=0.3038
    batch    0/603 loss=0.0736
    batch  100/603 loss=0.0239
    batch  200/603 loss=0.0704
    batch  300/603 loss=0.0455
    batch  400/603 loss=0.0812
    batch  500/603 loss=0.0090
    batch  600/603 loss=0.0976
Epoch 49/50 | train=0.0457 | Dice=0.8430 | IoU=0.7520 | HD95=21.29 | B-IoU=0.2983
    batch    0/603 loss=0.0618
    batch  100/603 loss=0.0318
    batch  200/603 loss=0.0178
    batch  300/603 loss=0.0904
    batch  400/603 loss=0.0339
    batch  500/603 loss=0.0265
    batch  600/603 loss=0.0364
Epoch 50/50 | train=0.0440 | Dice=0.8465 | IoU=0.7572 | HD95=19.40 | B-IoU=0.3061
{
  "fold": 3,
  "Dice checkpoint epoch": 50,
  "Boundary checkpoint epoch": 50,
  "CABLE-Dice test Dice": 0.8560734212557157,
  "CABLE-Dice test HD95": 17.445600337616604,
  "CABLE-Boundary test Dice": 0.8560734212557157,
  "CABLE-Boundary test HD95": 17.445600337616604
}

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

====================================================================================================
TRAIN CABLE ONLY | BUS-BRA | fold=4
====================================================================================================
    batch    0/605 loss=0.6949
    batch  100/605 loss=0.2238
    batch  200/605 loss=0.1584
    batch  300/605 loss=0.9008
    batch  400/605 loss=0.2810
    batch  500/605 loss=0.2990
    batch  600/605 loss=0.1409
Epoch 01/50 | train=0.2378 | Dice=0.3798 | IoU=0.2631 | HD95=65.09 | B-IoU=0.0471
    batch    0/605 loss=0.1492
    batch  100/605 loss=0.2117
    batch  200/605 loss=0.4923
    batch  300/605 loss=0.1047
    batch  400/605 loss=0.1661
    batch  500/605 loss=0.0375
    batch  600/605 loss=0.2558
Epoch 02/50 | train=0.1954 | Dice=0.4391 | IoU=0.3177 | HD95=51.41 | B-IoU=0.0584
    batch    0/605 loss=0.2293
    batch  100/605 loss=0.0787
    batch  200/605 loss=0.0976
    batch  300/605 loss=0.2412
    batch  400/605 loss=0.1039
    batch  500/605 loss=0.1526
    batch  600/605 loss=0.2161
Epoch 03/50 | train=0.1685 | Dice=0.6667 | IoU=0.5419 | HD95=47.73 | B-IoU=0.1489
    batch    0/605 loss=0.0813
    batch  100/605 loss=0.0715
    batch  200/605 loss=0.1175
    batch  300/605 loss=0.2053
    batch  400/605 loss=0.0671
    batch  500/605 loss=0.0773
    batch  600/605 loss=0.1785
Epoch 04/50 | train=0.1504 | Dice=0.6480 | IoU=0.5250 | HD95=41.58 | B-IoU=0.1491
    batch    0/605 loss=0.0624
    batch  100/605 loss=0.0545
    batch  200/605 loss=0.1206
    batch  300/605 loss=0.1472
    batch  400/605 loss=0.0881
    batch  500/605 loss=0.1030
    batch  600/605 loss=0.1246
Epoch 05/50 | train=0.1398 | Dice=0.7083 | IoU=0.5912 | HD95=34.42 | B-IoU=0.1866
    batch    0/605 loss=0.0605
    batch  100/605 loss=0.1669
    batch  200/605 loss=0.0869
    batch  300/605 loss=0.1619
    batch  400/605 loss=0.1780
    batch  500/605 loss=0.0618
    batch  600/605 loss=0.0696
Epoch 06/50 | train=0.1292 | Dice=0.7630 | IoU=0.6381 | HD95=40.96 | B-IoU=0.1922
    batch    0/605 loss=0.0467
    batch  100/605 loss=0.0648
    batch  200/605 loss=0.1623
    batch  300/605 loss=0.0474
    batch  400/605 loss=0.0476
    batch  500/605 loss=0.1930
    batch  600/605 loss=0.0420
Epoch 07/50 | train=0.1241 | Dice=0.7295 | IoU=0.6139 | HD95=28.21 | B-IoU=0.1929
    batch    0/605 loss=0.0473
    batch  100/605 loss=0.0458
    batch  200/605 loss=0.8311
    batch  300/605 loss=0.2182
    batch  400/605 loss=0.1110
    batch  500/605 loss=0.0913
    batch  600/605 loss=0.1228
Epoch 08/50 | train=0.1502 | Dice=0.7724 | IoU=0.6573 | HD95=25.86 | B-IoU=0.2066
    batch    0/605 loss=0.2076
    batch  100/605 loss=0.0482
    batch  200/605 loss=0.1631
    batch  300/605 loss=0.2205
    batch  400/605 loss=0.0813
    batch  500/605 loss=0.0635
    batch  600/605 loss=0.0515
Epoch 09/50 | train=0.1187 | Dice=0.7763 | IoU=0.6628 | HD95=27.79 | B-IoU=0.1976
    batch    0/605 loss=0.2725
    batch  100/605 loss=0.1499
    batch  200/605 loss=0.2123
    batch  300/605 loss=0.1148
    batch  400/605 loss=0.0446
    batch  500/605 loss=0.1176
    batch  600/605 loss=0.0789
Epoch 10/50 | train=0.1134 | Dice=0.7830 | IoU=0.6699 | HD95=35.18 | B-IoU=0.2065
    batch    0/605 loss=0.0976
    batch  100/605 loss=0.0629
    batch  200/605 loss=0.0414
    batch  300/605 loss=0.0756
    batch  400/605 loss=0.0626
    batch  500/605 loss=0.0506
    batch  600/605 loss=0.0436
Epoch 11/50 | train=0.1130 | Dice=0.8115 | IoU=0.7039 | HD95=28.42 | B-IoU=0.2349
    batch    0/605 loss=0.1464
    batch  100/605 loss=0.0801
    batch  200/605 loss=0.0901
    batch  300/605 loss=0.1190
    batch  400/605 loss=0.2031
    batch  500/605 loss=0.0681
    batch  600/605 loss=0.0794
Epoch 12/50 | train=0.1100 | Dice=0.7453 | IoU=0.6254 | HD95=37.92 | B-IoU=0.1934
    batch    0/605 loss=0.1129
    batch  100/605 loss=0.0390
    batch  200/605 loss=0.0309
    batch  300/605 loss=0.0954
    batch  400/605 loss=0.0936
    batch  500/605 loss=0.0798
    batch  600/605 loss=0.2365
Epoch 13/50 | train=0.1006 | Dice=0.8131 | IoU=0.7069 | HD95=24.59 | B-IoU=0.2403
    batch    0/605 loss=0.2306
    batch  100/605 loss=0.0384
    batch  200/605 loss=0.0531
    batch  300/605 loss=0.0385
    batch  400/605 loss=0.0640
    batch  500/605 loss=0.0389
    batch  600/605 loss=0.0179
Epoch 14/50 | train=0.1001 | Dice=0.8225 | IoU=0.7179 | HD95=23.07 | B-IoU=0.2448
    batch    0/605 loss=0.0542
    batch  100/605 loss=0.0507
    batch  200/605 loss=0.3267
    batch  300/605 loss=0.0275
    batch  400/605 loss=0.0716
    batch  500/605 loss=0.0284
    batch  600/605 loss=0.0619
Epoch 15/50 | train=0.0953 | Dice=0.8159 | IoU=0.7127 | HD95=25.25 | B-IoU=0.2492
    batch    0/605 loss=0.1102
    batch  100/605 loss=0.0441
    batch  200/605 loss=0.0414
    batch  300/605 loss=0.1093
    batch  400/605 loss=0.0875
    batch  500/605 loss=0.0923
    batch  600/605 loss=0.0738
Epoch 16/50 | train=0.0977 | Dice=0.8271 | IoU=0.7240 | HD95=21.66 | B-IoU=0.2566
    batch    0/605 loss=0.0382
    batch  100/605 loss=0.0496
    batch  200/605 loss=0.0966
    batch  300/605 loss=0.0410
    batch  400/605 loss=0.0874
    batch  500/605 loss=0.0462
    batch  600/605 loss=0.1349
Epoch 17/50 | train=0.0957 | Dice=0.8174 | IoU=0.7113 | HD95=32.31 | B-IoU=0.2533
    batch    0/605 loss=0.0249
    batch  100/605 loss=0.0553
    batch  200/605 loss=0.2117
    batch  300/605 loss=0.0915
    batch  400/605 loss=0.1142
    batch  500/605 loss=0.0748
    batch  600/605 loss=0.0959
Epoch 18/50 | train=0.0888 | Dice=0.8318 | IoU=0.7307 | HD95=27.64 | B-IoU=0.2608
    batch    0/605 loss=0.0638
    batch  100/605 loss=0.0997
    batch  200/605 loss=0.0462
    batch  300/605 loss=0.0713
    batch  400/605 loss=0.0976
    batch  500/605 loss=0.0418
    batch  600/605 loss=0.0657
Epoch 19/50 | train=0.0907 | Dice=0.7761 | IoU=0.6633 | HD95=46.91 | B-IoU=0.2269
    batch    0/605 loss=0.0529
    batch  100/605 loss=0.0556
    batch  200/605 loss=0.0597
    batch  300/605 loss=0.0625
    batch  400/605 loss=0.0413
    batch  500/605 loss=0.1047
    batch  600/605 loss=0.1271
Epoch 20/50 | train=0.0914 | Dice=0.8370 | IoU=0.7383 | HD95=23.34 | B-IoU=0.2663
    batch    0/605 loss=0.1055
    batch  100/605 loss=0.0273
    batch  200/605 loss=0.0472
    batch  300/605 loss=0.1659
    batch  400/605 loss=0.0498
    batch  500/605 loss=0.2481
    batch  600/605 loss=0.0410
Epoch 21/50 | train=0.0791 | Dice=0.8494 | IoU=0.7555 | HD95=21.61 | B-IoU=0.2832
    batch    0/605 loss=0.0969
    batch  100/605 loss=0.0305
    batch  200/605 loss=0.0484
    batch  300/605 loss=0.0562
    batch  400/605 loss=0.0909
    batch  500/605 loss=0.0195
    batch  600/605 loss=0.0992
Epoch 22/50 | train=0.0731 | Dice=0.8406 | IoU=0.7417 | HD95=16.60 | B-IoU=0.2703
    batch    0/605 loss=0.0119
    batch  100/605 loss=0.0517
    batch  200/605 loss=0.0870
    batch  300/605 loss=0.0360
    batch  400/605 loss=0.0226
    batch  500/605 loss=0.1149
    batch  600/605 loss=0.0244
Epoch 23/50 | train=0.0710 | Dice=0.8361 | IoU=0.7378 | HD95=22.06 | B-IoU=0.2795
    batch    0/605 loss=0.0353
    batch  100/605 loss=0.0263
    batch  200/605 loss=0.0458
    batch  300/605 loss=0.0680
    batch  400/605 loss=0.0805
    batch  500/605 loss=0.0397
    batch  600/605 loss=0.1226
Epoch 24/50 | train=0.0727 | Dice=0.8216 | IoU=0.7212 | HD95=23.77 | B-IoU=0.2654
    batch    0/605 loss=0.0651
    batch  100/605 loss=0.0554
    batch  200/605 loss=0.0404
    batch  300/605 loss=0.0260
    batch  400/605 loss=0.0350
    batch  500/605 loss=0.0343
    batch  600/605 loss=0.0435
Epoch 25/50 | train=0.0712 | Dice=0.8439 | IoU=0.7482 | HD95=23.18 | B-IoU=0.2757
    batch    0/605 loss=0.0611
    batch  100/605 loss=0.0228
    batch  200/605 loss=0.0230
    batch  300/605 loss=0.0096
    batch  400/605 loss=0.0962
    batch  500/605 loss=0.0096
    batch  600/605 loss=0.0473
Epoch 26/50 | train=0.0656 | Dice=0.8526 | IoU=0.7609 | HD95=18.70 | B-IoU=0.2928
    batch    0/605 loss=0.0718
    batch  100/605 loss=0.0088
    batch  200/605 loss=0.0266
    batch  300/605 loss=0.0769
    batch  400/605 loss=0.1169
    batch  500/605 loss=0.1003
    batch  600/605 loss=0.0332
Epoch 27/50 | train=0.0619 | Dice=0.8506 | IoU=0.7589 | HD95=18.32 | B-IoU=0.2915
    batch    0/605 loss=0.0865
    batch  100/605 loss=0.0458
    batch  200/605 loss=0.0741
    batch  300/605 loss=0.0554
    batch  400/605 loss=0.0505
    batch  500/605 loss=0.0806
    batch  600/605 loss=0.0391
Epoch 28/50 | train=0.0628 | Dice=0.8434 | IoU=0.7482 | HD95=21.52 | B-IoU=0.2859
    batch    0/605 loss=0.0553
    batch  100/605 loss=0.0979
    batch  200/605 loss=0.0592
    batch  300/605 loss=0.0444
    batch  400/605 loss=0.0170
    batch  500/605 loss=0.0497
    batch  600/605 loss=0.0241
Epoch 29/50 | train=0.0593 | Dice=0.8418 | IoU=0.7499 | HD95=20.46 | B-IoU=0.2932
    batch    0/605 loss=0.0604
    batch  100/605 loss=0.0379
    batch  200/605 loss=0.2024
    batch  300/605 loss=0.0554
    batch  400/605 loss=0.0151
    batch  500/605 loss=0.0117
    batch  600/605 loss=0.0306
Epoch 30/50 | train=0.0585 | Dice=0.8507 | IoU=0.7569 | HD95=16.58 | B-IoU=0.2951
    batch    0/605 loss=0.0286
    batch  100/605 loss=0.0545
    batch  200/605 loss=0.1421
    batch  300/605 loss=0.0557
    batch  400/605 loss=0.0829
    batch  500/605 loss=0.0986
    batch  600/605 loss=0.3345
Epoch 31/50 | train=0.0586 | Dice=0.8473 | IoU=0.7558 | HD95=21.94 | B-IoU=0.2930
    batch    0/605 loss=0.0252
    batch  100/605 loss=0.0354
    batch  200/605 loss=0.1206
    batch  300/605 loss=0.0208
    batch  400/605 loss=0.0259
    batch  500/605 loss=0.0557
    batch  600/605 loss=0.0802
Epoch 32/50 | train=0.0557 | Dice=0.8556 | IoU=0.7640 | HD95=20.10 | B-IoU=0.2956
    batch    0/605 loss=0.0282
    batch  100/605 loss=0.0438
    batch  200/605 loss=0.0825
    batch  300/605 loss=0.0237
    batch  400/605 loss=0.0466
    batch  500/605 loss=0.0686
    batch  600/605 loss=0.0411
Epoch 33/50 | train=0.0554 | Dice=0.8462 | IoU=0.7534 | HD95=21.25 | B-IoU=0.2861
    batch    0/605 loss=0.0460
    batch  100/605 loss=0.0621
    batch  200/605 loss=0.0360
    batch  300/605 loss=0.1932
    batch  400/605 loss=0.0362
    batch  500/605 loss=0.0423
    batch  600/605 loss=0.0306
Epoch 34/50 | train=0.0536 | Dice=0.8491 | IoU=0.7571 | HD95=19.95 | B-IoU=0.2914
    batch    0/605 loss=0.0450
    batch  100/605 loss=0.0244
    batch  200/605 loss=0.0578
    batch  300/605 loss=0.1217
    batch  400/605 loss=0.0431
    batch  500/605 loss=0.0450
    batch  600/605 loss=0.0157
Epoch 35/50 | train=0.0558 | Dice=0.8488 | IoU=0.7581 | HD95=19.65 | B-IoU=0.2938
    batch    0/605 loss=0.0202
    batch  100/605 loss=0.0668
    batch  200/605 loss=0.0368
    batch  300/605 loss=0.0749
    batch  400/605 loss=0.0383
    batch  500/605 loss=0.0395
    batch  600/605 loss=0.0079
Epoch 36/50 | train=0.0530 | Dice=0.8519 | IoU=0.7607 | HD95=19.48 | B-IoU=0.2940
    batch    0/605 loss=0.1288
    batch  100/605 loss=0.0293
    batch  200/605 loss=0.0284
    batch  300/605 loss=0.0914
    batch  400/605 loss=0.0170
    batch  500/605 loss=0.0235
    batch  600/605 loss=0.0207
Epoch 37/50 | train=0.0537 | Dice=0.8537 | IoU=0.7628 | HD95=18.86 | B-IoU=0.2999
    batch    0/605 loss=0.0332
    batch  100/605 loss=0.0301
    batch  200/605 loss=0.0357
    batch  300/605 loss=0.0488
    batch  400/605 loss=0.0708
    batch  500/605 loss=0.0255
    batch  600/605 loss=0.0643
Epoch 38/50 | train=0.0509 | Dice=0.8505 | IoU=0.7588 | HD95=19.29 | B-IoU=0.2945
    batch    0/605 loss=0.0437
    batch  100/605 loss=0.0620
    batch  200/605 loss=0.0234
    batch  300/605 loss=0.0307
    batch  400/605 loss=0.0140
    batch  500/605 loss=0.0367
    batch  600/605 loss=0.0158
Epoch 39/50 | train=0.0499 | Dice=0.8542 | IoU=0.7630 | HD95=18.87 | B-IoU=0.2979
    batch    0/605 loss=0.0073
    batch  100/605 loss=0.0418
    batch  200/605 loss=0.0606
    batch  300/605 loss=0.0766
    batch  400/605 loss=0.0234
    batch  500/605 loss=0.0452
    batch  600/605 loss=0.0355
Epoch 40/50 | train=0.0536 | Dice=0.8529 | IoU=0.7615 | HD95=19.27 | B-IoU=0.2972
    batch    0/605 loss=0.0234
    batch  100/605 loss=0.0261
    batch  200/605 loss=0.0248
    batch  300/605 loss=0.0365
    batch  400/605 loss=0.0426
    batch  500/605 loss=0.0442
    batch  600/605 loss=0.0475
Epoch 41/50 | train=0.0517 | Dice=0.8525 | IoU=0.7613 | HD95=19.65 | B-IoU=0.2958
    batch    0/605 loss=0.0596
    batch  100/605 loss=0.0067
    batch  200/605 loss=0.0495
    batch  300/605 loss=0.0106
    batch  400/605 loss=0.0541
    batch  500/605 loss=0.0167
    batch  600/605 loss=0.2842
Epoch 42/50 | train=0.0494 | Dice=0.8526 | IoU=0.7608 | HD95=19.03 | B-IoU=0.2962
    batch    0/605 loss=0.0293
    batch  100/605 loss=0.1318
    batch  200/605 loss=0.1226
    batch  300/605 loss=0.0365
    batch  400/605 loss=0.0799
    batch  500/605 loss=0.0504
    batch  600/605 loss=0.0234
Epoch 43/50 | train=0.0491 | Dice=0.8524 | IoU=0.7606 | HD95=18.70 | B-IoU=0.2962
    batch    0/605 loss=0.0588
    batch  100/605 loss=0.0725
    batch  200/605 loss=0.0159
    batch  300/605 loss=0.0159
    batch  400/605 loss=0.1194
    batch  500/605 loss=0.0724
    batch  600/605 loss=0.0372
Epoch 44/50 | train=0.0503 | Dice=0.8534 | IoU=0.7619 | HD95=19.27 | B-IoU=0.2973
    batch    0/605 loss=0.0493
    batch  100/605 loss=0.0492
    batch  200/605 loss=0.0202
    batch  300/605 loss=0.0539
    batch  400/605 loss=0.0961
    batch  500/605 loss=0.0219
    batch  600/605 loss=0.0243
Epoch 45/50 | train=0.0493 | Dice=0.8541 | IoU=0.7624 | HD95=17.89 | B-IoU=0.2971
    batch    0/605 loss=0.0387
    batch  100/605 loss=0.1147
    batch  200/605 loss=0.0254
    batch  300/605 loss=0.0105
    batch  400/605 loss=0.0202
    batch  500/605 loss=0.1450
    batch  600/605 loss=0.1062
Epoch 46/50 | train=0.0497 | Dice=0.8539 | IoU=0.7628 | HD95=18.94 | B-IoU=0.2973
    batch    0/605 loss=0.0584
    batch  100/605 loss=0.0355
    batch  200/605 loss=0.0435
    batch  300/605 loss=0.0504
    batch  400/605 loss=0.0125
    batch  500/605 loss=0.0236
    batch  600/605 loss=0.0782
Epoch 47/50 | train=0.0492 | Dice=0.8549 | IoU=0.7639 | HD95=18.50 | B-IoU=0.2991
    batch    0/605 loss=0.0188
    batch  100/605 loss=0.0979
    batch  200/605 loss=0.0345
    batch  300/605 loss=0.0512
    batch  400/605 loss=0.0162
    batch  500/605 loss=0.0275
    batch  600/605 loss=0.0749
Epoch 48/50 | train=0.0494 | Dice=0.8550 | IoU=0.7641 | HD95=18.39 | B-IoU=0.2982
    batch    0/605 loss=0.0190
    batch  100/605 loss=0.0123
    batch  200/605 loss=0.0650
    batch  300/605 loss=0.0262
    batch  400/605 loss=0.0217
    batch  500/605 loss=0.0115
    batch  600/605 loss=0.0196
Epoch 49/50 | train=0.0490 | Dice=0.8542 | IoU=0.7630 | HD95=19.33 | B-IoU=0.2972
    batch    0/605 loss=0.0540
    batch  100/605 loss=0.0416
    batch  200/605 loss=0.0670
    batch  300/605 loss=0.0134
    batch  400/605 loss=0.0165
    batch  500/605 loss=0.0219
    batch  600/605 loss=0.0654
Epoch 50/50 | train=0.0500 | Dice=0.8536 | IoU=0.7624 | HD95=19.38 | B-IoU=0.2975
{
  "fold": 4,
  "Dice checkpoint epoch": 32,
  "Boundary checkpoint epoch": 30,
  "CABLE-Dice test Dice": 0.845699523916081,
  "CABLE-Dice test HD95": 20.106434442838037,
  "CABLE-Boundary test Dice": 0.8377178533123831,
  "CABLE-Boundary test HD95": 18.354039660104153
}

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] SegformerModel LOAD REPORT from: nvidia/mit-b0
Key               | Status     |  |
------------------+------------+--+-
classifier.weight | UNEXPECTED |  |
classifier.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

====================================================================================================
TRAIN CABLE ONLY | BUS-BRA | fold=5
====================================================================================================
    batch    0/597 loss=0.6991
    batch  100/597 loss=0.3072
    batch  200/597 loss=0.1217
    batch  300/597 loss=0.3127
    batch  400/597 loss=0.1276
    batch  500/597 loss=0.1684
Epoch 01/50 | train=0.2374 | Dice=0.0083 | IoU=0.0045 | HD95=300.51 | B-IoU=0.0012
    batch    0/597 loss=0.4046
    batch  100/597 loss=0.3430
    batch  200/597 loss=0.2837
    batch  300/597 loss=0.0960
    batch  400/597 loss=0.1511
    batch  500/597 loss=0.1541
Epoch 02/50 | train=0.1927 | Dice=0.1433 | IoU=0.0960 | HD95=191.56 | B-IoU=0.0196
    batch    0/597 loss=0.2296
    batch  100/597 loss=0.1508
    batch  200/597 loss=0.1358
    batch  300/597 loss=0.1285
    batch  400/597 loss=0.1360
    batch  500/597 loss=0.1823
Epoch 03/50 | train=0.2125 | Dice=0.0047 | IoU=0.0026 | HD95=340.54 | B-IoU=0.0002
    batch    0/597 loss=0.3368
    batch  100/597 loss=0.1181
    batch  200/597 loss=0.1512
    batch  300/597 loss=0.0992
    batch  400/597 loss=0.1445
    batch  500/597 loss=0.1120
Epoch 04/50 | train=0.2000 | Dice=0.5102 | IoU=0.3701 | HD95=76.41 | B-IoU=0.0720
    batch    0/597 loss=0.2016
    batch  100/597 loss=0.1845
    batch  200/597 loss=0.1537
    batch  300/597 loss=0.0924
    batch  400/597 loss=0.0920
    batch  500/597 loss=0.1297
Epoch 05/50 | train=0.1841 | Dice=0.3888 | IoU=0.2893 | HD95=81.48 | B-IoU=0.0719
    batch    0/597 loss=0.0837
    batch  100/597 loss=0.1503
    batch  200/597 loss=0.1312
    batch  300/597 loss=0.0819
    batch  400/597 loss=0.2425
    batch  500/597 loss=0.1123
Epoch 06/50 | train=0.1591 | Dice=0.5666 | IoU=0.4376 | HD95=47.33 | B-IoU=0.1028
    batch    0/597 loss=0.1117
    batch  100/597 loss=0.0857
    batch  200/597 loss=0.2589
    batch  300/597 loss=0.0750
    batch  400/597 loss=0.0577
    batch  500/597 loss=0.1589
Epoch 07/50 | train=0.1495 | Dice=0.6285 | IoU=0.4934 | HD95=59.34 | B-IoU=0.1215
    batch    0/597 loss=0.0855
    batch  100/597 loss=0.0509
    batch  200/597 loss=0.2540
    batch  300/597 loss=0.1262
    batch  400/597 loss=0.0691
    batch  500/597 loss=0.1080
Epoch 08/50 | train=0.1400 | Dice=0.3427 | IoU=0.2522 | HD95=84.18 | B-IoU=0.0588
    batch    0/597 loss=0.1673
    batch  100/597 loss=0.1121
    batch  200/597 loss=0.0403
    batch  300/597 loss=0.2515
    batch  400/597 loss=0.2453
    batch  500/597 loss=0.4068
Epoch 09/50 | train=0.1339 | Dice=0.6714 | IoU=0.5449 | HD95=52.42 | B-IoU=0.1506
    batch    0/597 loss=0.1486
    batch  100/597 loss=0.0296
    batch  200/597 loss=0.1655
    batch  300/597 loss=0.0542
    batch  400/597 loss=0.0769
    batch  500/597 loss=0.0430
Epoch 10/50 | train=0.1219 | Dice=0.6784 | IoU=0.5545 | HD95=41.48 | B-IoU=0.1604
    batch    0/597 loss=0.2957
    batch  100/597 loss=0.0467
    batch  200/597 loss=0.1031
    batch  300/597 loss=0.0578
    batch  400/597 loss=0.2157
    batch  500/597 loss=0.0629
Epoch 11/50 | train=0.1128 | Dice=0.7617 | IoU=0.6461 | HD95=37.90 | B-IoU=0.1983
    batch    0/597 loss=0.0500
    batch  100/597 loss=0.0784
    batch  200/597 loss=0.0369
    batch  300/597 loss=0.0575
    batch  400/597 loss=0.0807
    batch  500/597 loss=0.0630
Epoch 12/50 | train=0.1126 | Dice=0.7603 | IoU=0.6444 | HD95=35.78 | B-IoU=0.2034
    batch    0/597 loss=0.0405
    batch  100/597 loss=0.0494
    batch  200/597 loss=0.0466
    batch  300/597 loss=0.0765
    batch  400/597 loss=0.0670
    batch  500/597 loss=0.1724
Epoch 13/50 | train=0.1060 | Dice=0.7708 | IoU=0.6576 | HD95=28.58 | B-IoU=0.2107
    batch    0/597 loss=0.0230
    batch  100/597 loss=0.0288
    batch  200/597 loss=0.1252
    batch  300/597 loss=0.0778
    batch  400/597 loss=0.1166
    batch  500/597 loss=0.1084
Epoch 14/50 | train=0.0995 | Dice=0.7717 | IoU=0.6580 | HD95=30.53 | B-IoU=0.1947
    batch    0/597 loss=0.0937
    batch  100/597 loss=0.0276
    batch  200/597 loss=0.0991
    batch  300/597 loss=0.0733
    batch  400/597 loss=0.3311
    batch  500/597 loss=0.1073
Epoch 15/50 | train=0.1040 | Dice=0.7744 | IoU=0.6636 | HD95=34.25 | B-IoU=0.2189
    batch    0/597 loss=0.0277
    batch  100/597 loss=0.0617
    batch  200/597 loss=0.0687
    batch  300/597 loss=0.0567
    batch  400/597 loss=0.0913
    batch  500/597 loss=0.0451
Epoch 16/50 | train=0.0971 | Dice=0.7815 | IoU=0.6741 | HD95=30.90 | B-IoU=0.2268
    batch    0/597 loss=0.0650
    batch  100/597 loss=0.0238
    batch  200/597 loss=0.0923
    batch  300/597 loss=0.0293
    batch  400/597 loss=0.0380
    batch  500/597 loss=0.0357
Epoch 17/50 | train=0.0933 | Dice=0.7796 | IoU=0.6713 | HD95=29.59 | B-IoU=0.2273
    batch    0/597 loss=0.1122
    batch  100/597 loss=0.0772
    batch  200/597 loss=0.2630
    batch  300/597 loss=0.0427
    batch  400/597 loss=0.0306
    batch  500/597 loss=0.0647
Epoch 18/50 | train=0.0939 | Dice=0.7597 | IoU=0.6503 | HD95=25.90 | B-IoU=0.2231
    batch    0/597 loss=0.0873
    batch  100/597 loss=0.0944
    batch  200/597 loss=0.1028
    batch  300/597 loss=0.0589
    batch  400/597 loss=0.1329
    batch  500/597 loss=0.1010
Epoch 19/50 | train=0.0915 | Dice=0.7819 | IoU=0.6748 | HD95=38.54 | B-IoU=0.2388
    batch    0/597 loss=0.0286
    batch  100/597 loss=0.0275
    batch  200/597 loss=0.1363
    batch  300/597 loss=0.0597
    batch  400/597 loss=0.0880
    batch  500/597 loss=0.2992
Epoch 20/50 | train=0.0883 | Dice=0.7847 | IoU=0.6798 | HD95=27.75 | B-IoU=0.2337
    batch    0/597 loss=0.1068
    batch  100/597 loss=0.0897
    batch  200/597 loss=0.1099
    batch  300/597 loss=0.0393
    batch  400/597 loss=0.0177
    batch  500/597 loss=0.1129
Epoch 21/50 | train=0.0793 | Dice=0.8012 | IoU=0.7035 | HD95=24.38 | B-IoU=0.2599
    batch    0/597 loss=0.0533
    batch  100/597 loss=0.0803
    batch  200/597 loss=0.0348
    batch  300/597 loss=0.0466
    batch  400/597 loss=0.0768
    batch  500/597 loss=0.1059
Epoch 22/50 | train=0.0740 | Dice=0.8066 | IoU=0.7074 | HD95=23.07 | B-IoU=0.2600
    batch    0/597 loss=0.0750
    batch  100/597 loss=0.0612
    batch  200/597 loss=0.0525
    batch  300/597 loss=0.0453
    batch  400/597 loss=0.0907
    batch  500/597 loss=0.0707
Epoch 23/50 | train=0.0724 | Dice=0.8171 | IoU=0.7168 | HD95=27.59 | B-IoU=0.2639
    batch    0/597 loss=0.0644
    batch  100/597 loss=0.0755
    batch  200/597 loss=0.0992
    batch  300/597 loss=0.0586
    batch  400/597 loss=0.0529
    batch  500/597 loss=0.0227
Epoch 24/50 | train=0.0727 | Dice=0.8284 | IoU=0.7294 | HD95=22.75 | B-IoU=0.2512
    batch    0/597 loss=0.0275
    batch  100/597 loss=0.0343
    batch  200/597 loss=0.0419
    batch  300/597 loss=0.0409
    batch  400/597 loss=0.0347
    batch  500/597 loss=0.0201
Epoch 25/50 | train=0.0723 | Dice=0.8208 | IoU=0.7232 | HD95=24.22 | B-IoU=0.2702
    batch    0/597 loss=0.0487
    batch  100/597 loss=0.0946
    batch  200/597 loss=0.0581
    batch  300/597 loss=0.0774
    batch  400/597 loss=0.0261
    batch  500/597 loss=0.0460
Epoch 26/50 | train=0.0699 | Dice=0.8239 | IoU=0.7284 | HD95=21.11 | B-IoU=0.2718
    batch    0/597 loss=0.0238
    batch  100/597 loss=0.0346
    batch  200/597 loss=0.0423
    batch  300/597 loss=0.0363
    batch  400/597 loss=0.0561
    batch  500/597 loss=0.0625
Epoch 27/50 | train=0.0692 | Dice=0.8291 | IoU=0.7330 | HD95=20.71 | B-IoU=0.2754
    batch    0/597 loss=0.0119
    batch  100/597 loss=0.1976
    batch  200/597 loss=0.0560
    batch  300/597 loss=0.0851
    batch  400/597 loss=0.0258
    batch  500/597 loss=0.0736
Epoch 28/50 | train=0.0683 | Dice=0.8206 | IoU=0.7201 | HD95=22.67 | B-IoU=0.2658
    batch    0/597 loss=0.0217
    batch  100/597 loss=0.0371
    batch  200/597 loss=0.0750
    batch  300/597 loss=0.0146
    batch  400/597 loss=0.0544
    batch  500/597 loss=0.2497
Epoch 29/50 | train=0.0658 | Dice=0.8302 | IoU=0.7344 | HD95=21.31 | B-IoU=0.2771
    batch    0/597 loss=0.0210
    batch  100/597 loss=0.0588
    batch  200/597 loss=0.0358
    batch  300/597 loss=0.0807
    batch  400/597 loss=0.0340
    batch  500/597 loss=0.0113
Epoch 30/50 | train=0.0653 | Dice=0.8191 | IoU=0.7213 | HD95=20.76 | B-IoU=0.2731
    batch    0/597 loss=0.0947
    batch  100/597 loss=0.0407
    batch  200/597 loss=0.0604
    batch  300/597 loss=0.0428
    batch  400/597 loss=0.0285
    batch  500/597 loss=0.0445
Epoch 31/50 | train=0.0658 | Dice=0.8320 | IoU=0.7366 | HD95=19.64 | B-IoU=0.2799
    batch    0/597 loss=0.0429
    batch  100/597 loss=0.0751
    batch  200/597 loss=0.0348
    batch  300/597 loss=0.0434
    batch  400/597 loss=0.1405
    batch  500/597 loss=0.0403
Epoch 32/50 | train=0.0653 | Dice=0.8162 | IoU=0.7207 | HD95=18.97 | B-IoU=0.2755
    batch    0/597 loss=0.1300
    batch  100/597 loss=0.0217
    batch  200/597 loss=0.0637
    batch  300/597 loss=0.0314
    batch  400/597 loss=0.0478
    batch  500/597 loss=0.0579
Epoch 33/50 | train=0.0615 | Dice=0.8211 | IoU=0.7261 | HD95=18.10 | B-IoU=0.2777
    batch    0/597 loss=0.0139
    batch  100/597 loss=0.0356
    batch  200/597 loss=0.0120
    batch  300/597 loss=0.0289
    batch  400/597 loss=0.0280
    batch  500/597 loss=0.0327
Epoch 34/50 | train=0.0562 | Dice=0.8402 | IoU=0.7473 | HD95=19.32 | B-IoU=0.2893
    batch    0/597 loss=0.0284
    batch  100/597 loss=0.0334
    batch  200/597 loss=0.0572
    batch  300/597 loss=0.0866
    batch  400/597 loss=0.0256
    batch  500/597 loss=0.0213
Epoch 35/50 | train=0.0541 | Dice=0.8360 | IoU=0.7419 | HD95=19.54 | B-IoU=0.2848
    batch    0/597 loss=0.0202
    batch  100/597 loss=0.1023
    batch  200/597 loss=0.1077
    batch  300/597 loss=0.0266
    batch  400/597 loss=0.0376
    batch  500/597 loss=0.0307
Epoch 36/50 | train=0.0548 | Dice=0.8334 | IoU=0.7372 | HD95=18.69 | B-IoU=0.2730
    batch    0/597 loss=0.0323
    batch  100/597 loss=0.0414
    batch  200/597 loss=0.0975
    batch  300/597 loss=0.0920
    batch  400/597 loss=0.0201
    batch  500/597 loss=0.0742
Epoch 37/50 | train=0.0534 | Dice=0.8407 | IoU=0.7490 | HD95=18.29 | B-IoU=0.2900
    batch    0/597 loss=0.0136
    batch  100/597 loss=0.0517
    batch  200/597 loss=0.0709
    batch  300/597 loss=0.0999
    batch  400/597 loss=0.0168
    batch  500/597 loss=0.0566
Epoch 38/50 | train=0.0538 | Dice=0.8456 | IoU=0.7538 | HD95=18.98 | B-IoU=0.2907
    batch    0/597 loss=0.0155
    batch  100/597 loss=0.0153
    batch  200/597 loss=0.0485
    batch  300/597 loss=0.0355
    batch  400/597 loss=0.1050
    batch  500/597 loss=0.0267
Epoch 39/50 | train=0.0522 | Dice=0.8380 | IoU=0.7456 | HD95=17.84 | B-IoU=0.2859
    batch    0/597 loss=0.0226
    batch  100/597 loss=0.0143
    batch  200/597 loss=0.0254
    batch  300/597 loss=0.1046
    batch  400/597 loss=0.0704
    batch  500/597 loss=0.0784
Epoch 40/50 | train=0.0549 | Dice=0.8371 | IoU=0.7432 | HD95=20.92 | B-IoU=0.2878
    batch    0/597 loss=0.0378
    batch  100/597 loss=0.0340
    batch  200/597 loss=0.0545
    batch  300/597 loss=0.0406
    batch  400/597 loss=0.0199
    batch  500/597 loss=0.0123
Epoch 41/50 | train=0.0546 | Dice=0.8385 | IoU=0.7467 | HD95=19.64 | B-IoU=0.2912
    batch    0/597 loss=0.0380
    batch  100/597 loss=0.0613
    batch  200/597 loss=0.1284
    batch  300/597 loss=0.0434
    batch  400/597 loss=0.1102
    batch  500/597 loss=0.0443
Epoch 42/50 | train=0.0539 | Dice=0.8441 | IoU=0.7522 | HD95=18.37 | B-IoU=0.2883
    batch    0/597 loss=0.0322
    batch  100/597 loss=0.0576
    batch  200/597 loss=0.0440
    batch  300/597 loss=0.0368
    batch  400/597 loss=0.0331
    batch  500/597 loss=0.0212
Epoch 43/50 | train=0.0521 | Dice=0.8418 | IoU=0.7493 | HD95=19.04 | B-IoU=0.2875
    batch    0/597 loss=0.0757
    batch  100/597 loss=0.0236
    batch  200/597 loss=0.0313
    batch  300/597 loss=0.0133
    batch  400/597 loss=0.0226
    batch  500/597 loss=0.0250
Epoch 44/50 | train=0.0487 | Dice=0.8413 | IoU=0.7487 | HD95=18.01 | B-IoU=0.2901
    batch    0/597 loss=0.0299
    batch  100/597 loss=0.0367
    batch  200/597 loss=0.0103
    batch  300/597 loss=0.0303
    batch  400/597 loss=0.0177
    batch  500/597 loss=0.1054
Epoch 45/50 | train=0.0503 | Dice=0.8398 | IoU=0.7476 | HD95=17.34 | B-IoU=0.2888
    batch    0/597 loss=0.0256
    batch  100/597 loss=0.0717
    batch  200/597 loss=0.0179
    batch  300/597 loss=0.0462
    batch  400/597 loss=0.0281
    batch  500/597 loss=0.0745
Epoch 46/50 | train=0.0458 | Dice=0.8428 | IoU=0.7518 | HD95=18.07 | B-IoU=0.2945
    batch    0/597 loss=0.0328
    batch  100/597 loss=0.0563
    batch  200/597 loss=0.0165
    batch  300/597 loss=0.0587
    batch  400/597 loss=0.0492
    batch  500/597 loss=0.0990
Epoch 47/50 | train=0.0476 | Dice=0.8429 | IoU=0.7509 | HD95=17.48 | B-IoU=0.2899
    batch    0/597 loss=0.0700
    batch  100/597 loss=0.0358
    batch  200/597 loss=0.0180
    batch  300/597 loss=0.0474
    batch  400/597 loss=0.0777
    batch  500/597 loss=0.0409
Epoch 48/50 | train=0.0472 | Dice=0.8451 | IoU=0.7541 | HD95=17.45 | B-IoU=0.2946
    batch    0/597 loss=0.0405
    batch  100/597 loss=0.0639
    batch  200/597 loss=0.0185
    batch  300/597 loss=0.0904
    batch  400/597 loss=0.0086
    batch  500/597 loss=0.0471
Epoch 49/50 | train=0.0443 | Dice=0.8467 | IoU=0.7570 | HD95=17.45 | B-IoU=0.2983
    batch    0/597 loss=0.0235
    batch  100/597 loss=0.0167
    batch  200/597 loss=0.0178
    batch  300/597 loss=0.1582
    batch  400/597 loss=0.0293
    batch  500/597 loss=0.0677
Epoch 50/50 | train=0.0445 | Dice=0.8469 | IoU=0.7570 | HD95=17.99 | B-IoU=0.2959
{
  "fold": 5,
  "Dice checkpoint epoch": 50,
  "Boundary checkpoint epoch": 48,
  "CABLE-Dice test Dice": 0.8474687950573674,
  "CABLE-Dice test HD95": 19.520114650753936,
  "CABLE-Boundary test Dice": 0.8446677781109263,
  "CABLE-Boundary test HD95": 19.228618242865608
}

,fold,dice_checkpoint_epoch,boundary_checkpoint_epoch,selected_differs_from_best_dice,dice_test_dice,dice_test_hd95,boundary_test_dice,boundary_test_hd95
0,1,45,48,True,0.855043,17.635295,0.857781,16.108930
1,2,39,49,True,0.838175,20.051138,0.840221,20.301026
2,3,50,50,False,0.856073,17.445600,0.856073,17.445600
3,4,32,30,True,0.845700,20.106434,0.837718,18.354040
4,5,50,48,True,0.847469,19.520115,0.844668,19.228618

# Part B — BUS-UCLM: five new CABLE trainings

In [52]:

# ============================================================
# 17. BUS-UCLM DATA CACHE
# ============================================================

BUSUCLM_DRIVE = (
    DRIVE_ROOT
    / "BUS_UCLM"
)

BUSUCLM_ZIP = (
    BUSUCLM_DRIVE
    / "7fvgj4jsp7-1.zip"
)

BUSUCLM_LOCAL = (
    LOCAL_ROOT
    / "BUS_UCLM_DATA"
)

if RUN_BUSUCLM:
    assert BUSUCLM_ZIP.exists(), (
        "Place official BUS-UCLM ZIP at:\n"
        f"{BUSUCLM_ZIP}"
    )

    already_extracted = (
        BUSUCLM_LOCAL.exists()
        and any(
            BUSUCLM_LOCAL.rglob(
                "*.png"
            )
        )
    )

    if not already_extracted:
        BUSUCLM_LOCAL.mkdir(
            parents=True,
            exist_ok=True,
        )

        with zipfile.ZipFile(
            BUSUCLM_ZIP,
            "r",
        ) as zf:
            bad = zf.testzip()

            if bad is not None:
                raise RuntimeError(
                    f"ZIP integrity failure: {bad}"
                )

            zf.extractall(
                BUSUCLM_LOCAL
            )

    print(
        "BUS-UCLM available at:",
        BUSUCLM_LOCAL,
    )


UCLM_FINAL_ROOT = (
    FINAL_ROOT
    / "BUS_UCLM"
)

UCLM_FINAL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

BUS-UCLM available at: /content/MHTM_MEDICAL/BUS_UCLM_DATA

In [53]:

# ============================================================
# 18. BUS-UCLM PUBLIC MANIFEST
# ============================================================

def candidate_named_dirs(
    root,
    target_name,
):
    return [
        p
        for p in root.rglob("*")
        if p.is_dir()
        and p.name.lower()
        == target_name.lower()
    ]


image_dirs = candidate_named_dirs(
    BUSUCLM_LOCAL,
    "images",
)

mask_dirs = candidate_named_dirs(
    BUSUCLM_LOCAL,
    "masks",
)

if (
    not image_dirs
    or not mask_dirs
):
    raise FileNotFoundError(
        "Could not find BUS-UCLM images/ and masks/ directories."
    )


best = None

for idir in image_dirs:
    image_files = {
        p.stem: p
        for p in idir.glob("*.png")
    }

    for mdir in mask_dirs:
        mask_files = {
            p.stem: p
            for p in mdir.glob("*.png")
        }

        common = (
            set(image_files)
            & set(mask_files)
        )

        score = len(common)

        if (
            best is None
            or score > best[0]
        ):
            best = (
                score,
                idir,
                mdir,
                image_files,
                mask_files,
            )


(
    score,
    IMAGES_DIR,
    MASKS_DIR,
    image_files,
    mask_files,
) = best

assert score == 683, (
    f"Expected 683 matched image/mask filenames, found {score}"
)


def inspect_rgb_mask(
    mask_path,
):
    bgr = cv2.imread(
        str(mask_path),
        cv2.IMREAD_COLOR,
    )

    if bgr is None:
        raise RuntimeError(
            f"Could not read mask: {mask_path}"
        )

    rgb = cv2.cvtColor(
        bgr,
        cv2.COLOR_BGR2RGB,
    )

    R = rgb[..., 0].astype(np.int16)
    G = rgb[..., 1].astype(np.int16)
    B = rgb[..., 2].astype(np.int16)

    lesion = (
        (R > 0)
        | (G > 0)
        | (B > 0)
    )

    if not lesion.any():
        pathology = "normal"

    else:
        red_score = int(
            np.logical_and(
                R > G,
                R > B,
            ).sum()
        )

        green_score = int(
            np.logical_and(
                G > R,
                G > B,
            ).sum()
        )

        if red_score > green_score:
            pathology = "malignant"

        elif green_score > red_score:
            pathology = "benign"

        else:
            raise RuntimeError(
                f"Cannot infer mask pathology: {mask_path}"
            )

    return (
        pathology,
        int(
            lesion.sum()
        ),
    )


manifest_rows = []

for stem in sorted(
    set(image_files)
    & set(mask_files)
):
    pathology, lesion_pixels = (
        inspect_rgb_mask(
            mask_files[stem]
        )
    )

    patient = (
        stem.split("_")[0]
    )

    manifest_rows.append({
        "id": stem,
        "patient": patient,
        "pathology": pathology,
        "image_path": str(
            image_files[stem]
        ),
        "mask_path": str(
            mask_files[stem]
        ),
        "lesion_pixels_original": lesion_pixels,
    })


manifest_public = pd.DataFrame(
    manifest_rows
)

assert len(manifest_public) == 683
assert manifest_public.patient.nunique() == 38

public_counts = (
    manifest_public.pathology
    .value_counts()
    .to_dict()
)

assert public_counts == {
    "normal": 419,
    "benign": 174,
    "malignant": 90,
}, public_counts

print(
    "Public BUS-UCLM manifest: PASS"
)

display(
    manifest_public.groupby(
        "pathology"
    ).agg(
        images=("id", "size"),
        patients=("patient", "nunique"),
    )
)

Public BUS-UCLM manifest: PASS

           images  patients
pathology
benign        174        24
malignant      90        17
normal        419        35

In [54]:

# ============================================================
# 19. BUS-UCLM GEOMETRY AUDIT
# ============================================================

shape_rows = []

for row in manifest_public.itertuples(
    index=False
):
    image = cv2.imread(
        row.image_path,
        cv2.IMREAD_COLOR,
    )

    mask = cv2.imread(
        row.mask_path,
        cv2.IMREAD_COLOR,
    )

    if (
        image is None
        or mask is None
    ):
        raise RuntimeError(
            f"Read failure: {row.id}"
        )

    ih, iw = image.shape[:2]
    mh, mw = mask.shape[:2]

    shape_rows.append({
        "id": row.id,
        "image_h": ih,
        "image_w": iw,
        "mask_h": mh,
        "mask_w": mw,
        "same_shape": (
            ih == mh
            and iw == mw
        ),
    })


shape_audit = pd.DataFrame(
    shape_rows
)

manifest_full = (
    manifest_public
    .merge(
        shape_audit,
        on="id",
        how="left",
        validate="one_to_one",
    )
)

excluded_geometry = (
    manifest_full[
        ~manifest_full.same_shape
    ]
    .copy()
    .reset_index(drop=True)
)

manifest = (
    manifest_full[
        manifest_full.same_shape
    ]
    .copy()
    .reset_index(drop=True)
)


assert len(excluded_geometry) == 13
assert len(manifest) == 670
assert manifest.patient.nunique() == 37

counts = (
    manifest.pathology
    .value_counts()
    .to_dict()
)

assert counts == {
    "normal": 410,
    "benign": 170,
    "malignant": 90,
}, counts


print(
    "Geometry-valid evaluation/training pool: PASS"
)

print(
    "Retained:",
    len(manifest),
    "images from",
    manifest.patient.nunique(),
    "patients",
)

print(
    "Excluded:",
    len(excluded_geometry),
    "incompatible public pairs",
)

display(
    manifest.groupby(
        "pathology"
    ).agg(
        images=("id", "size"),
        patients=("patient", "nunique"),
    )
)


manifest.to_csv(
    UCLM_FINAL_ROOT
    / "BUSUCLM_GEOMETRY_VALID_MANIFEST_670.csv",
    index=False,
)

excluded_geometry.to_csv(
    UCLM_FINAL_ROOT
    / "BUSUCLM_EXCLUDED_GEOMETRY_MISMATCHES.csv",
    index=False,
)

Geometry-valid evaluation/training pool: PASS
Retained: 670 images from 37 patients
Excluded: 13 incompatible public pairs

           images  patients
pathology
benign        170        23
malignant      90        17
normal        410        34

In [55]:

# ============================================================
# 20. BUS-UCLM — LOAD EXACT PREVIOUS OUTER-FOLD ASSIGNMENT
# ============================================================

saved_assignment = pd.read_csv(
    OLD_UCLM_ASSIGNMENT
)

manifest = manifest.copy()

manifest[
    "id"
] = manifest[
    "id"
].astype(
    str
)

saved_assignment[
    "id"
] = saved_assignment[
    "id"
].astype(
    str
)


required_saved_cols = {
    "id",
    "outer_fold",
}

assert required_saved_cols.issubset(
    saved_assignment.columns
)


manifest = (
    manifest.drop(
        columns=[
            "outer_fold",
        ],
        errors="ignore",
    )
    .merge(
        saved_assignment[
            [
                "id",
                "outer_fold",
            ]
        ],
        on="id",
        how="left",
        validate="one_to_one",
    )
)


assert len(
    manifest
) == 670

assert manifest[
    "outer_fold"
].notna().all()

manifest[
    "outer_fold"
] = manifest[
    "outer_fold"
].astype(
    int
)

assert manifest[
    "outer_fold"
].between(
    1,
    5,
).all()


patient_fold_count = (
    manifest.groupby(
        "patient"
    )[
        "outer_fold"
    ]
    .nunique()
)

assert patient_fold_count.max() == 1


outer_fold_audit = (
    manifest.groupby(
        "outer_fold"
    )
    .agg(
        images=("id", "size"),
        patients=("patient", "nunique"),
        benign=(
            "pathology",
            lambda s: (
                s == "benign"
            ).sum(),
        ),
        malignant=(
            "pathology",
            lambda s: (
                s == "malignant"
            ).sum(),
        ),
        normal=(
            "pathology",
            lambda s: (
                s == "normal"
            ).sum(),
        ),
    )
)


display(
    outer_fold_audit
)

print(
    "PASS: exact saved BUS-UCLM outer folds from the "
    "authoritative baseline experiment were reused."
)


manifest.to_csv(
    UCLM_FINAL_ROOT
    / "BUSUCLM_OUTER_FOLD_ASSIGNMENT_REUSED.csv",
    index=False,
)

            images  patients  benign  malignant  normal
outer_fold
1              123         8      37         13      73
2              165         7      47         25      93
3              151         8      50         19      82
4              110         7      29          6      75
5              121         7       7         27      87

PASS: exact saved BUS-UCLM outer folds from the authoritative baseline experiment were reused.

In [56]:

# ============================================================
# 21. BUS-UCLM INNER VALIDATION SPLIT
# ============================================================

def make_split(
    outer_fold,
):
    outer_fold = int(
        outer_fold
    )

    test_all = (
        manifest[
            manifest.outer_fold
            == outer_fold
        ]
        .copy()
        .reset_index(drop=True)
    )

    dev_all = (
        manifest[
            manifest.outer_fold
            != outer_fold
        ]
        .copy()
        .reset_index(drop=True)
    )


    # Primary training task is lesion segmentation.
    dev_lesion = (
        dev_all[
            dev_all.pathology
            .isin(
                [
                    "benign",
                    "malignant",
                ]
            )
        ]
        .copy()
        .reset_index(drop=True)
    )


    inner = StratifiedGroupKFold(
        n_splits=5,
        shuffle=True,
        random_state=(
            cfg.uclm_inner_val_seed
            + outer_fold
        ),
    )


    # Choose a deterministic candidate split using labels/counts only.
    # This is not model-performance selection.
    candidates = []

    overall_prop = (
        dev_lesion.pathology
        .value_counts(
            normalize=True
        )
    )

    for split_idx, (
        train_idx,
        val_idx,
    ) in enumerate(
        inner.split(
            X=dev_lesion,
            y=dev_lesion.pathology,
            groups=dev_lesion.patient,
        )
    ):
        tr = (
            dev_lesion.iloc[
                train_idx
            ]
            .copy()
        )

        va = (
            dev_lesion.iloc[
                val_idx
            ]
            .copy()
        )

        # Require both lesion pathologies in train and validation.
        if (
            tr.pathology.nunique()
            < 2
            or va.pathology.nunique()
            < 2
        ):
            continue

        val_prop = (
            va.pathology
            .value_counts(
                normalize=True
            )
        )

        balance_penalty = sum(
            abs(
                float(
                    val_prop.get(
                        cls,
                        0.0,
                    )
                )
                - float(
                    overall_prop.get(
                        cls,
                        0.0,
                    )
                )
            )
            for cls in [
                "benign",
                "malignant",
            ]
        )

        size_penalty = abs(
            len(va)
            / len(dev_lesion)
            - 0.20
        )

        candidates.append(
            (
                balance_penalty
                + size_penalty,
                split_idx,
                train_idx,
                val_idx,
            )
        )


    if not candidates:
        raise RuntimeError(
            f"No valid inner split for outer fold {outer_fold}"
        )


    candidates.sort(
        key=lambda x: (
            x[0],
            x[1],
        )
    )

    _, selected_idx, train_idx, val_idx = (
        candidates[0]
    )


    train_df = (
        dev_lesion.iloc[
            train_idx
        ]
        .copy()
        .reset_index(drop=True)
    )

    val_df = (
        dev_lesion.iloc[
            val_idx
        ]
        .copy()
        .reset_index(drop=True)
    )

    test_lesion = (
        test_all[
            test_all.pathology
            .isin(
                [
                    "benign",
                    "malignant",
                ]
            )
        ]
        .copy()
        .reset_index(drop=True)
    )

    test_normal = (
        test_all[
            test_all.pathology
            == "normal"
        ]
        .copy()
        .reset_index(drop=True)
    )


    tr_pat = set(
        train_df.patient
    )
    va_pat = set(
        val_df.patient
    )
    te_pat = set(
        test_all.patient
    )

    assert tr_pat.isdisjoint(
        va_pat
    )

    assert tr_pat.isdisjoint(
        te_pat
    )

    assert va_pat.isdisjoint(
        te_pat
    )

    assert len(
        test_lesion
    ) > 0

    assert len(
        test_normal
    ) > 0


    return {
        "train": train_df,
        "val": val_df,
        "test_lesion": test_lesion,
        "test_normal": test_normal,
        "test_all": test_all,
        "inner_split_index": int(
            selected_idx
        ),
    }


split_rows = []

for fold in OUTER_FOLDS:
    s = make_split(
        fold
    )

    split_rows.append({
        "fold": fold,
        "inner_split_index": s[
            "inner_split_index"
        ],

        "train_lesion_images": len(
            s["train"]
        ),
        "train_patients": s[
            "train"
        ].patient.nunique(),

        "val_lesion_images": len(
            s["val"]
        ),
        "val_patients": s[
            "val"
        ].patient.nunique(),

        "test_lesion_images": len(
            s["test_lesion"]
        ),
        "test_normal_images": len(
            s["test_normal"]
        ),
        "test_patients_all": s[
            "test_all"
        ].patient.nunique(),

        "train_malignant": int(
            (
                s["train"].pathology
                == "malignant"
            ).sum()
        ),
        "val_malignant": int(
            (
                s["val"].pathology
                == "malignant"
            ).sum()
        ),
        "test_malignant": int(
            (
                s["test_lesion"].pathology
                == "malignant"
            ).sum()
        ),
    })


split_audit = pd.DataFrame(
    split_rows
)

display(
    split_audit
)

split_audit.to_csv(
    UCLM_FINAL_ROOT
    / "BUSUCLM_SUPERVISED_SPLIT_AUDIT.csv",
    index=False,
)

,fold,inner_split_index,train_lesion_images,train_patients,val_lesion_images,val_patients,test_lesion_images,test_normal_images,test_patients_all,train_malignant,val_malignant,test_malignant
0,1,1,173,22,37,5,50,73,8,63,14,13
1,2,1,150,21,38,7,72,93,7,53,12,25
2,3,3,136,21,55,6,69,82,8,53,18,19
3,4,3,159,24,66,6,35,75,7,56,28,6
4,5,1,192,23,34,5,34,87,7,55,8,27

In [57]:

# ============================================================
# 22. BUS-UCLM DATASET + LOADERS
# ============================================================

UCLM_TRAIN_TRANSFORM = A.Compose([
    A.Resize(
        cfg.image_size,
        cfg.image_size,
    ),
    A.HorizontalFlip(
        p=0.5
    ),
    A.RandomRotate90(
        p=0.5
    ),
    A.Normalize(
        mean=(
            0.485,
            0.456,
            0.406,
        ),
        std=(
            0.229,
            0.224,
            0.225,
        ),
    ),
    ToTensorV2(),
])


UCLM_EVAL_TRANSFORM = A.Compose([
    A.Resize(
        cfg.image_size,
        cfg.image_size,
    ),
    A.Normalize(
        mean=(
            0.485,
            0.456,
            0.406,
        ),
        std=(
            0.229,
            0.224,
            0.225,
        ),
    ),
    ToTensorV2(),
])


class BUSUCLMDataset(Dataset):
    def __init__(
        self,
        df,
        train=False,
    ):
        self.df = (
            df
            .reset_index(
                drop=True
            )
        )

        self.transform = (
            UCLM_TRAIN_TRANSFORM
            if train
            else UCLM_EVAL_TRANSFORM
        )

    def __len__(
        self
    ):
        return len(
            self.df
        )

    def __getitem__(
        self,
        idx,
    ):
        row = self.df.iloc[
            idx
        ]

        image = cv2.imread(
            row.image_path,
            cv2.IMREAD_COLOR,
        )

        mask_rgb = cv2.imread(
            row.mask_path,
            cv2.IMREAD_COLOR,
        )

        if (
            image is None
            or mask_rgb is None
        ):
            raise RuntimeError(
                f"Read failure: {row.id}"
            )

        image = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB,
        )

        mask_rgb = cv2.cvtColor(
            mask_rgb,
            cv2.COLOR_BGR2RGB,
        )

        assert (
            image.shape[:2]
            == mask_rgb.shape[:2]
        )

        mask = (
            np.any(
                mask_rgb > 0,
                axis=-1,
            )
        ).astype(
            np.uint8
        )

        aug = self.transform(
            image=image,
            mask=mask,
        )

        return (
            aug["image"].float(),
            aug["mask"].long(),
            {
                "id": str(
                    row.id
                ),
                "patient": str(
                    row.patient
                ),
                "pathology": str(
                    row.pathology
                ),
            },
        )


def make_uclm_loaders(
    split,
    run_seed,
):
    train_ds = BUSUCLMDataset(
        split[
            "train"
        ],
        train=True,
    )

    val_ds = BUSUCLMDataset(
        split[
            "val"
        ],
        train=False,
    )

    test_lesion_ds = BUSUCLMDataset(
        split[
            "test_lesion"
        ],
        train=False,
    )

    test_normal_ds = BUSUCLMDataset(
        split[
            "test_normal"
        ],
        train=False,
    )

    g = torch.Generator()
    g.manual_seed(
        run_seed
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=cfg.uclm_num_workers,
        pin_memory=(
            DEVICE.type == "cuda"
        ),
        drop_last=True,
        generator=g,
        worker_init_fn=seed_worker,
    )

    eval_kwargs = dict(
        batch_size=cfg.eval_batch_size,
        shuffle=False,
        num_workers=cfg.uclm_num_workers,
        pin_memory=(
            DEVICE.type == "cuda"
        ),
        drop_last=False,
        worker_init_fn=seed_worker,
    )

    return (
        train_loader,
        DataLoader(
            val_ds,
            **eval_kwargs,
        ),
        DataLoader(
            test_lesion_ds,
            **eval_kwargs,
        ),
        DataLoader(
            test_normal_ds,
            **eval_kwargs,
        ),
    )

In [58]:

# ============================================================
# 22B. BUS-UCLM PRE-FLIGHT INTERFACE CHECK
# ============================================================

_pre_split = make_split(
    OUTER_FOLDS[0]
)

(
    _pre_train_loader,
    _pre_val_loader,
    _pre_test_lesion_loader,
    _pre_test_normal_loader,
) = make_uclm_loaders(
    _pre_split,
    cfg.train_seed,
)

_pre_images, _pre_masks, _pre_meta = next(
    iter(
        _pre_val_loader
    )
)

assert _pre_images.ndim == 4
assert _pre_images.shape[1] == 3
assert _pre_masks.ndim == 3

assert set(
    _pre_meta.keys()
) == {
    "id",
    "patient",
    "pathology",
}, _pre_meta.keys()

print(
    "PASS: BUS-UCLM loader/evaluator interface is consistent."
)

print(
    "Example metadata:",
    {
        key: _pre_meta[key][0]
        for key in _pre_meta
    },
)

del (
    _pre_train_loader,
    _pre_val_loader,
    _pre_test_lesion_loader,
    _pre_test_normal_loader,
    _pre_images,
    _pre_masks,
    _pre_meta,
    _pre_split,
)

PASS: BUS-UCLM loader/evaluator interface is consistent.
Example metadata: {'id': 'CHSP_006', 'patient': 'CHSP', 'pathology': 'malignant'}

In [59]:

# ============================================================
# 23. BUS-UCLM CABLE-ONLY FINAL RUN
# ============================================================

def uclm_cable_run_dir(
    fold,
):
    return (
        UCLM_FINAL_ROOT
        / f"fold_{fold}"
        / f"seed_{cfg.train_seed}"
        / CABLE_VARIANT
    )


def run_uclm_cable_fold(
    fold,
):
    out_dir = uclm_cable_run_dir(
        fold
    )

    out_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    result_path = (
        out_dir
        / "result_two_operating_points.json"
    )

    history_path = (
        out_dir
        / "history.csv"
    )

    selection_path = (
        out_dir
        / "selection.json"
    )

    best_dice_ckpt = (
        out_dir
        / "best_val_dice.pt"
    )

    boundary_ckpt = (
        out_dir
        / "selected_dice_constrained_boundary.pt"
    )

    dice_lesion_path = (
        out_dir
        / "per_image_test_lesion_dice.csv"
    )

    boundary_lesion_path = (
        out_dir
        / "per_image_test_lesion_boundary.csv"
    )

    dice_normal_path = (
        out_dir
        / "per_image_test_normal_dice.csv"
    )

    boundary_normal_path = (
        out_dir
        / "per_image_test_normal_boundary.csv"
    )

    dice_lesion_mask = (
        out_dir
        / "pred_masks_test_lesion_dice_256.npz"
    )

    boundary_lesion_mask = (
        out_dir
        / "pred_masks_test_lesion_boundary_256.npz"
    )

    dice_normal_mask = (
        out_dir
        / "pred_masks_test_normal_dice_256.npz"
    )

    boundary_normal_mask = (
        out_dir
        / "pred_masks_test_normal_boundary_256.npz"
    )

    complete = all(
        p.exists()
        for p in [
            result_path,
            history_path,
            selection_path,
            best_dice_ckpt,
            boundary_ckpt,
            dice_lesion_path,
            boundary_lesion_path,
            dice_normal_path,
            boundary_normal_path,
            dice_lesion_mask,
            boundary_lesion_mask,
            dice_normal_mask,
            boundary_normal_mask,
        ]
    )

    if (
        complete
        and not FORCE_RERUN
    ):
        print(
            f"REUSE BUS-UCLM CABLE | fold={fold}"
        )

        with open(
            result_path,
            "r",
        ) as f:
            return json.load(
                f
            )


    split = make_split(
        fold
    )

    set_seed(
        cfg.train_seed
    )

    (
        train_loader,
        val_loader,
        test_lesion_loader,
        test_normal_loader,
    ) = make_uclm_loaders(
        split,
        cfg.train_seed,
    )

    model = SwiftMSegFamily(
        variant=CABLE_VARIANT,
        num_classes=cfg.num_classes,
    ).to(
        DEVICE
    )

    run_metadata = {
        "dataset": "BUS-UCLM",
        "outer_fold": int(
            fold
        ),
        "variant": CABLE_VARIANT,
        "train_seed": int(
            cfg.train_seed
        ),
    }

    print(
        "\n"
        + "=" * 100
    )

    print(
        f"TRAIN CABLE ONLY | BUS-UCLM | fold={fold}"
    )

    print(
        "=" * 100
    )

    (
        history_df,
        selection,
        best_dice_path,
        boundary_path,
    ) = train_cable_save_two_checkpoints(
        model,
        train_loader,
        val_loader,
        out_dir,
        run_metadata,
    )

    history_df.to_csv(
        history_path,
        index=False,
    )

    with open(
        selection_path,
        "w",
    ) as f:
        json.dump(
            selection,
            f,
            indent=2,
        )


    # --------------------------------------------------------
    # CABLE-Dice
    # --------------------------------------------------------
    payload_dice = load_model_checkpoint(
        model,
        best_dice_path,
    )

    dice_lesion_summary, dice_lesion_details = evaluate_lesion_loader(
        model,
        test_lesion_loader,
        save_masks_path=dice_lesion_mask,
    )

    dice_normal_summary, dice_normal_details = evaluate_normal_loader(
        model,
        test_normal_loader,
        save_masks_path=dice_normal_mask,
    )

    dice_lesion_details = dice_lesion_details.assign(
        dataset="BUS-UCLM",
        fold=int(
            fold
        ),
        train_seed=int(
            cfg.train_seed
        ),
        variant=CABLE_VARIANT,
        operating_point="dice",
    )

    dice_normal_details = dice_normal_details.assign(
        dataset="BUS-UCLM",
        fold=int(
            fold
        ),
        train_seed=int(
            cfg.train_seed
        ),
        variant=CABLE_VARIANT,
        operating_point="dice",
    )

    dice_lesion_details.to_csv(
        dice_lesion_path,
        index=False,
    )

    dice_normal_details.to_csv(
        dice_normal_path,
        index=False,
    )


    # --------------------------------------------------------
    # CABLE-Boundary
    # --------------------------------------------------------
    payload_boundary = load_model_checkpoint(
        model,
        boundary_path,
    )

    boundary_lesion_summary, boundary_lesion_details = evaluate_lesion_loader(
        model,
        test_lesion_loader,
        save_masks_path=boundary_lesion_mask,
    )

    boundary_normal_summary, boundary_normal_details = evaluate_normal_loader(
        model,
        test_normal_loader,
        save_masks_path=boundary_normal_mask,
    )

    boundary_lesion_details = boundary_lesion_details.assign(
        dataset="BUS-UCLM",
        fold=int(
            fold
        ),
        train_seed=int(
            cfg.train_seed
        ),
        variant=CABLE_VARIANT,
        operating_point="boundary",
    )

    boundary_normal_details = boundary_normal_details.assign(
        dataset="BUS-UCLM",
        fold=int(
            fold
        ),
        train_seed=int(
            cfg.train_seed
        ),
        variant=CABLE_VARIANT,
        operating_point="boundary",
    )

    boundary_lesion_details.to_csv(
        boundary_lesion_path,
        index=False,
    )

    boundary_normal_details.to_csv(
        boundary_normal_path,
        index=False,
    )


    result = {
        "dataset": "BUS-UCLM",
        "fold": int(
            fold
        ),
        "variant": CABLE_VARIANT,
        "train_seed": int(
            cfg.train_seed
        ),

        "n_train_lesion_images": int(
            len(
                split[
                    "train"
                ]
            )
        ),
        "n_val_lesion_images": int(
            len(
                split[
                    "val"
                ]
            )
        ),
        "n_test_lesion_images": int(
            len(
                split[
                    "test_lesion"
                ]
            )
        ),
        "n_test_normal_images": int(
            len(
                split[
                    "test_normal"
                ]
            )
        ),

        **selection,

        "dice_checkpoint_epoch": int(
            payload_dice[
                "epoch"
            ]
        ),

        "boundary_checkpoint_epoch": int(
            payload_boundary[
                "epoch"
            ]
        ),

        "dice_test_dice": dice_lesion_summary[
            "dice"
        ],
        "dice_test_iou": dice_lesion_summary[
            "iou"
        ],
        "dice_test_hd95": dice_lesion_summary[
            "hd95"
        ],
        "dice_test_boundary_iou": dice_lesion_summary[
            "boundary_iou"
        ],
        "dice_normal_fp_area_mean": dice_normal_summary[
            "normal_fp_area_mean"
        ],
        "dice_normal_any_lesion_rate": dice_normal_summary[
            "normal_any_lesion_rate"
        ],

        "boundary_test_dice": boundary_lesion_summary[
            "dice"
        ],
        "boundary_test_iou": boundary_lesion_summary[
            "iou"
        ],
        "boundary_test_hd95": boundary_lesion_summary[
            "hd95"
        ],
        "boundary_test_boundary_iou": boundary_lesion_summary[
            "boundary_iou"
        ],
        "boundary_normal_fp_area_mean": boundary_normal_summary[
            "normal_fp_area_mean"
        ],
        "boundary_normal_any_lesion_rate": boundary_normal_summary[
            "normal_any_lesion_rate"
        ],

        "params_M": float(
            architecture_audit.loc[
                architecture_audit.variant
                == CABLE_VARIANT,
                "params_M",
            ].iloc[
                0
            ]
        ),

        "aggregator_GMACs": float(
            complexity_lookup[
                CABLE_VARIANT
            ]
        ),

        "best_dice_checkpoint": str(
            best_dice_path
        ),

        "boundary_checkpoint": str(
            boundary_path
        ),
    }


    with open(
        result_path,
        "w",
    ) as f:
        json.dump(
            result,
            f,
            indent=2,
        )


    print(
        json.dumps(
            {
                "fold": fold,
                "Dice checkpoint epoch": result[
                    "dice_checkpoint_epoch"
                ],
                "Boundary checkpoint epoch": result[
                    "boundary_checkpoint_epoch"
                ],
                "CABLE-Dice test Dice": result[
                    "dice_test_dice"
                ],
                "CABLE-Dice test HD95": result[
                    "dice_test_hd95"
                ],
                "CABLE-Boundary test Dice": result[
                    "boundary_test_dice"
                ],
                "CABLE-Boundary test HD95": result[
                    "boundary_test_hd95"
                ],
            },
            indent=2,
        )
    )


    del (
        model,
        train_loader,
        val_loader,
        test_lesion_loader,
        test_normal_loader,
        payload_dice,
        payload_boundary,
    )

    gc.collect()

    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()


    return result

In [60]:

# ============================================================
# 24. RUN THE FIVE BUS-UCLM CABLE FOLDS
# ============================================================

uclm_cable_results = []

if RUN_BUSUCLM:
    for fold in OUTER_FOLDS:
        uclm_cable_results.append(
            run_uclm_cable_fold(
                fold
            )
        )

    uclm_cable_results_df = (
        pd.DataFrame(
            uclm_cable_results
        )
        .sort_values(
            "fold"
        )
        .reset_index(
            drop=True
        )
    )

    assert len(
        uclm_cable_results_df
    ) == 5

    uclm_cable_results_df.to_csv(
        UCLM_FINAL_ROOT
        / "CABLE_ALL_FOLD_RESULTS.csv",
        index=False,
    )

    display(
        uclm_cable_results_df[
            [
                "fold",
                "dice_checkpoint_epoch",
                "boundary_checkpoint_epoch",
                "selected_differs_from_best_dice",
                "dice_test_dice",
                "dice_test_hd95",
                "boundary_test_dice",
                "boundary_test_hd95",
                "dice_normal_fp_area_mean",
                "boundary_normal_fp_area_mean",
            ]
        ]
    )

REUSE BUS-UCLM CABLE | fold=1
REUSE BUS-UCLM CABLE | fold=2
REUSE BUS-UCLM CABLE | fold=3
REUSE BUS-UCLM CABLE | fold=4
REUSE BUS-UCLM CABLE | fold=5

,fold,dice_checkpoint_epoch,boundary_checkpoint_epoch,selected_differs_from_best_dice,dice_test_dice,dice_test_hd95,boundary_test_dice,boundary_test_hd95,dice_normal_fp_area_mean,boundary_normal_fp_area_mean
0,1,41,41,False,0.468128,65.350091,0.468128,65.350091,0.029093,0.029093
1,2,27,27,False,0.515709,67.241483,0.515709,67.241483,0.031277,0.031277
2,3,33,33,False,0.666837,48.948862,0.666837,48.948862,0.040971,0.040971
3,4,41,34,True,0.592831,56.527867,0.558833,58.457723,0.039720,0.032006
4,5,22,37,True,0.423918,60.833389,0.383575,53.005032,0.029320,0.018006


# Part C — paper-facing analysis

The main architecture table uses the **existing authoritative best-Dice baselines** and the
new **CABLE-Dice** result. CABLE-Boundary is reported separately as an operating-point
analysis and is never presented as an apples-to-apples architecture-baseline comparison.

In [61]:

# ============================================================
# 25. LOAD AUTHORITATIVE BASELINES + NEW CABLE RESULTS
# ============================================================

def load_json(
    path,
):
    with open(
        path,
        "r",
    ) as f:
        return json.load(
            f
        )


baseline_fold_rows = []


# ------------------------------------------------------------
# BUS-BRA: authoritative CLEAN checkpoint audit
# ------------------------------------------------------------
for fold in OUTER_FOLDS:
    for variant in BASELINE_VARIANTS:
        r = load_json(
            bra_baseline_dir(
                fold,
                variant,
            )
            / "result_clean.json"
        )

        baseline_fold_rows.append({
            "dataset": "BUS-BRA",
            "fold": int(
                fold
            ),
            "variant": variant,
            "operating_point": "dice",
            "test_dice": float(
                r[
                    "dice_fg_image_mean"
                ]
            ),
            "test_iou": float(
                r[
                    "iou_fg_image_mean"
                ]
            ),
            "test_hd95": float(
                r[
                    "hd95_image_mean"
                ]
            ),
            "test_boundary_iou": float(
                r[
                    "boundary_iou_image_mean"
                ]
            ),
            "normal_fp_area_mean": np.nan,
            "normal_any_lesion_rate": np.nan,
        })


# ------------------------------------------------------------
# BUS-UCLM: completed supervised patient-disjoint CV
# ------------------------------------------------------------
for fold in OUTER_FOLDS:
    for variant in BASELINE_VARIANTS:
        r = load_json(
            uclm_baseline_dir(
                fold,
                variant,
            )
            / "result.json"
        )

        baseline_fold_rows.append({
            "dataset": "BUS-UCLM",
            "fold": int(
                fold
            ),
            "variant": variant,
            "operating_point": "dice",
            "test_dice": float(
                r[
                    "test_dice"
                ]
            ),
            "test_iou": float(
                r[
                    "test_iou"
                ]
            ),
            "test_hd95": float(
                r[
                    "test_hd95"
                ]
            ),
            "test_boundary_iou": float(
                r[
                    "test_boundary_iou"
                ]
            ),
            "normal_fp_area_mean": float(
                r[
                    "normal_fp_area_mean"
                ]
            ),
            "normal_any_lesion_rate": float(
                r[
                    "normal_any_lesion_rate"
                ]
            ),
        })


baseline_fold_df = pd.DataFrame(
    baseline_fold_rows
)


# ------------------------------------------------------------
# New CABLE-Dice + CABLE-Boundary rows
# ------------------------------------------------------------
cable_fold_rows = []


if RUN_BUSBRA:
    for r in busbra_cable_results:
        for op in [
            "dice",
            "boundary",
        ]:
            cable_fold_rows.append({
                "dataset": "BUS-BRA",
                "fold": int(
                    r[
                        "fold"
                    ]
                ),
                "variant": CABLE_VARIANT,
                "operating_point": op,
                "test_dice": float(
                    r[
                        f"{op}_test_dice"
                    ]
                ),
                "test_iou": float(
                    r[
                        f"{op}_test_iou"
                    ]
                ),
                "test_hd95": float(
                    r[
                        f"{op}_test_hd95"
                    ]
                ),
                "test_boundary_iou": float(
                    r[
                        f"{op}_test_boundary_iou"
                    ]
                ),
                "normal_fp_area_mean": np.nan,
                "normal_any_lesion_rate": np.nan,
            })


if RUN_BUSUCLM:
    for r in uclm_cable_results:
        for op in [
            "dice",
            "boundary",
        ]:
            cable_fold_rows.append({
                "dataset": "BUS-UCLM",
                "fold": int(
                    r[
                        "fold"
                    ]
                ),
                "variant": CABLE_VARIANT,
                "operating_point": op,
                "test_dice": float(
                    r[
                        f"{op}_test_dice"
                    ]
                ),
                "test_iou": float(
                    r[
                        f"{op}_test_iou"
                    ]
                ),
                "test_hd95": float(
                    r[
                        f"{op}_test_hd95"
                    ]
                ),
                "test_boundary_iou": float(
                    r[
                        f"{op}_test_boundary_iou"
                    ]
                ),
                "normal_fp_area_mean": float(
                    r[
                        f"{op}_normal_fp_area_mean"
                    ]
                ),
                "normal_any_lesion_rate": float(
                    r[
                        f"{op}_normal_any_lesion_rate"
                    ]
                ),
            })


cable_fold_df = pd.DataFrame(
    cable_fold_rows
)


all_fold_df = pd.concat(
    [
        baseline_fold_df,
        cable_fold_df,
    ],
    ignore_index=True,
)


all_fold_df.to_csv(
    FINAL_ROOT
    / "ALL_METHODS_ALL_OPERATING_POINTS_FOLD_RESULTS.csv",
    index=False,
)


# Main fair architecture comparison:
main_fold_df = all_fold_df[
    all_fold_df[
        "operating_point"
    ]
    == "dice"
].copy()


assert (
    main_fold_df.groupby(
        [
            "dataset",
            "variant",
        ]
    )[
        "fold"
    ]
    .nunique()
    == 5
).all()


display(
    main_fold_df.sort_values(
        [
            "dataset",
            "fold",
            "variant",
        ]
    )
)

,dataset,fold,variant,operating_point,test_dice,test_iou,test_hd95,test_boundary_iou,normal_fp_area_mean,normal_any_lesion_rate
20,BUS-BRA,1,cable_s1,dice,0.855043,0.768337,17.635295,0.311087,NaN,NaN
1,BUS-BRA,1,mhtm_hybrid_final,dice,0.852776,0.765015,18.771803,0.301415,NaN,NaN
0,BUS-BRA,1,swift_lgl,dice,0.858946,0.772448,16.728889,0.309644,NaN,NaN
22,BUS-BRA,2,cable_s1,dice,0.838175,0.748393,20.051138,0.298238,NaN,NaN
3,BUS-BRA,2,mhtm_hybrid_final,dice,0.831522,0.738712,21.767122,0.287388,NaN,NaN
2,BUS-BRA,2,swift_lgl,dice,0.839043,0.751184,18.371030,0.304459,NaN,NaN
24,BUS-BRA,3,cable_s1,dice,0.856073,0.768018,17.445600,0.306027,NaN,NaN
5,BUS-BRA,3,mhtm_hybrid_final,dice,0.852770,0.764623,18.857680,0.304917,NaN,NaN
4,BUS-BRA,3,swift_lgl,dice,0.852965,0.763085,18.072275,0.304560,NaN,NaN
26,BUS-BRA,4,cable_s1,dice,0.845700,0.757963,20.106434,0.292923,NaN,NaN
7,BUS-BRA,4,mhtm_hybrid_final,dice,0.843763,0.755612,19.772945,0.295355,NaN,NaN
6,BUS-BRA,4,swift_lgl,dice,0.847693,0.761332,18.067780,0.298668,NaN,NaN
28,BUS-BRA,5,cable_s1,dice,0.847469,0.758494,19.520115,0.296142,NaN,NaN
9,BUS-BRA,5,mhtm_hybrid_final,dice,0.851137,0.763987,19.263610,0.297994,NaN,NaN
8,BUS-BRA,5,swift_lgl,dice,0.868677,0.789190,16.311729,0.319118,NaN,NaN
30,BUS-UCLM,1,cable_s1,dice,0.468128,0.345112,65.350091,0.075421,0.029093,0.712329
11,BUS-UCLM,1,mhtm_hybrid_final,dice,0.500767,0.381966,56.716819,0.093920,0.034190,0.821918
10,BUS-UCLM,1,swift_lgl,dice,0.509882,0.385163,50.151650,0.091319,0.039884,0.863014
32,BUS-UCLM,2,cable_s1,dice,0.515709,0.409840,67.241483,0.099939,0.031277,0.741935
13,BUS-UCLM,2,mhtm_hybrid_final,dice,0.604344,0.486187,51.843926,0.116734,0.038313,0.849462
12,BUS-UCLM,2,swift_lgl,dice,0.618294,0.496541,45.625107,0.117258,0.044964,0.892473
34,BUS-UCLM,3,cable_s1,dice,0.666837,0.536042,48.948862,0.110497,0.040971,0.975610
15,BUS-UCLM,3,mhtm_hybrid_final,dice,0.635001,0.506200,66.579114,0.116417,0.025701,0.878049
14,BUS-UCLM,3,swift_lgl,dice,0.560557,0.437741,79.317012,0.108076,0.030333,0.804878
36,BUS-UCLM,4,cable_s1,dice,0.592831,0.467238,56.527867,0.124478,0.039720,0.893333
17,BUS-UCLM,4,mhtm_hybrid_final,dice,0.662909,0.544896,53.015468,0.125033,0.027583,0.800000
16,BUS-UCLM,4,swift_lgl,dice,0.408533,0.292019,85.214759,0.042559,0.047174,0.893333
38,BUS-UCLM,5,cable_s1,dice,0.423918,0.300125,60.833389,0.048868,0.029320,0.793103
19,BUS-UCLM,5,mhtm_hybrid_final,dice,0.619100,0.483890,52.652301,0.075875,0.046958,0.988506
18,BUS-UCLM,5,swift_lgl,dice,0.627381,0.498258,40.006338,0.078298,0.023829,0.827586

In [62]:

# ============================================================
# 26. MAIN ARCHITECTURE TABLE + CABLE OPERATING-POINT TABLE
# ============================================================

def summarize_folds(
    df,
):
    rows = []

    for (
        dataset,
        variant,
        op,
    ), g in df.groupby(
        [
            "dataset",
            "variant",
            "operating_point",
        ]
    ):
        rows.append({
            "dataset": dataset,
            "variant": variant,
            "operating_point": op,
            "folds": int(
                g.fold.nunique()
            ),
            "dice_mean": float(
                g.test_dice.mean()
            ),
            "dice_sd": float(
                g.test_dice.std(
                    ddof=1
                )
            ),
            "iou_mean": float(
                g.test_iou.mean()
            ),
            "iou_sd": float(
                g.test_iou.std(
                    ddof=1
                )
            ),
            "hd95_mean": float(
                g.test_hd95.mean()
            ),
            "hd95_sd": float(
                g.test_hd95.std(
                    ddof=1
                )
            ),
            "boundary_iou_mean": float(
                g.test_boundary_iou.mean()
            ),
            "boundary_iou_sd": float(
                g.test_boundary_iou.std(
                    ddof=1
                )
            ),
            "normal_fp_area_mean": (
                float(
                    g.normal_fp_area_mean.mean()
                )
                if g.normal_fp_area_mean.notna().any()
                else np.nan
            ),
            "normal_any_lesion_rate_mean": (
                float(
                    g.normal_any_lesion_rate.mean()
                )
                if g.normal_any_lesion_rate.notna().any()
                else np.nan
            ),
        })

    return pd.DataFrame(
        rows
    )


main_summary = summarize_folds(
    main_fold_df
)

cable_op_summary = summarize_folds(
    cable_fold_df
)


eff = efficiency_df.set_index(
    "variant"
)

for table in [
    main_summary,
    cable_op_summary,
]:
    for col in [
        "params_M",
        "aggregator_GMACs",
        "latency_ms_median",
        "peak_inference_memory_mb",
    ]:
        table[
            col
        ] = table.variant.map(
            eff[
                col
            ]
        )


print(
    "MAIN FAIR ARCHITECTURE COMPARISON "
    "(all methods selected by validation Dice)"
)

display(
    main_summary.sort_values(
        [
            "dataset",
            "variant",
        ]
    )
)


print(
    "\nCABLE OPERATING-POINT ANALYSIS"
)

display(
    cable_op_summary.sort_values(
        [
            "dataset",
            "operating_point",
        ]
    )
)


main_summary.to_csv(
    FINAL_ROOT
    / "MAIN_ARCHITECTURE_TABLE.csv",
    index=False,
)

cable_op_summary.to_csv(
    FINAL_ROOT
    / "CABLE_OPERATING_POINT_TABLE.csv",
    index=False,
)

MAIN FAIR ARCHITECTURE COMPARISON (all methods selected by validation Dice)

,dataset,variant,operating_point,folds,dice_mean,dice_sd,iou_mean,iou_sd,hd95_mean,hd95_sd,boundary_iou_mean,boundary_iou_sd,normal_fp_area_mean,normal_any_lesion_rate_mean,params_M,aggregator_GMACs,latency_ms_median,peak_inference_memory_mb
0,BUS-BRA,cable_s1,dice,5,0.848492,0.007343,0.760241,0.008286,18.951716,1.310203,0.300883,0.007474,NaN,NaN,4.487235,0.231195,12.685904,47.681641
1,BUS-BRA,mhtm_hybrid_final,dice,5,0.846394,0.009110,0.757590,0.011245,19.686632,1.228710,0.297414,0.006659,NaN,NaN,4.481858,0.225690,13.944832,47.658691
2,BUS-BRA,swift_lgl,dice,5,0.853465,0.011214,0.767448,0.014306,17.510341,0.923936,0.307290,0.007669,NaN,NaN,4.485282,1.312145,13.921840,47.674805
3,BUS-UCLM,cable_s1,dice,5,0.533485,0.097336,0.411671,0.094117,59.780338,7.343351,0.091841,0.029980,0.034076,0.823262,4.487235,0.231195,12.685904,47.681641
4,BUS-UCLM,mhtm_hybrid_final,dice,5,0.604424,0.061878,0.480628,0.060332,56.161526,6.117363,0.105596,0.020240,0.034549,0.867587,4.481858,0.225690,13.944832,47.658691
5,BUS-UCLM,swift_lgl,dice,5,0.544929,0.089801,0.421944,0.086417,60.062973,20.689885,0.087502,0.029274,0.037237,0.856257,4.485282,1.312145,13.921840,47.674805

CABLE OPERATING-POINT ANALYSIS

,dataset,variant,operating_point,folds,dice_mean,dice_sd,iou_mean,iou_sd,hd95_mean,hd95_sd,boundary_iou_mean,boundary_iou_sd,normal_fp_area_mean,normal_any_lesion_rate_mean,params_M,aggregator_GMACs,latency_ms_median,peak_inference_memory_mb
0,BUS-BRA,cable_s1,boundary,5,0.847292,0.009161,0.758957,0.010411,18.287643,1.612403,0.301730,0.009707,NaN,NaN,4.487235,0.231195,12.685904,47.681641
1,BUS-BRA,cable_s1,dice,5,0.848492,0.007343,0.760241,0.008286,18.951716,1.310203,0.300883,0.007474,NaN,NaN,4.487235,0.231195,12.685904,47.681641
2,BUS-UCLM,cable_s1,boundary,5,0.518616,0.105333,0.400784,0.098193,58.600638,7.821562,0.089907,0.029799,0.030271,0.827492,4.487235,0.231195,12.685904,47.681641
3,BUS-UCLM,cable_s1,dice,5,0.533485,0.097336,0.411671,0.094117,59.780338,7.343351,0.091841,0.029980,0.034076,0.823262,4.487235,0.231195,12.685904,47.681641

In [63]:

# ============================================================
# 27. NORMALIZE + AUDIT ALL OOF PER-IMAGE RESULTS
# ============================================================

def normalize_bra_baseline_details(
    df,
):
    out = pd.DataFrame({
        "id": df[
            "id"
        ].astype(
            str
        ),
        "patient": df[
            "case"
        ].astype(
            str
        ),
        "pathology": df[
            "pathology"
        ].astype(
            str
        ),
        "dice": df[
            "dice_fg"
        ].astype(
            float
        ),
        "iou": df[
            "iou_fg"
        ].astype(
            float
        ),
        "hd95": df[
            "hd95"
        ].astype(
            float
        ),
        "boundary_iou": df[
            "boundary_iou"
        ].astype(
            float
        ),
        "gt_area_fraction": df[
            "target_area_fraction"
        ].astype(
            float
        ),
        "pred_area_fraction": df[
            "pred_area_fraction"
        ].astype(
            float
        ),
        "fold": df[
            "fold"
        ].astype(
            int
        ),
        "variant": df[
            "variant"
        ].astype(
            str
        ),
    })

    out[
        "operating_point"
    ] = "dice"

    out[
        "dataset"
    ] = "BUS-BRA"

    return out


def normalize_uclm_baseline_details(
    df,
):
    out = df[
        [
            "id",
            "patient",
            "pathology",
            "dice",
            "iou",
            "hd95",
            "boundary_iou",
            "gt_area_fraction",
            "pred_area_fraction",
            "fold",
            "variant",
        ]
    ].copy()

    out[
        "id"
    ] = out[
        "id"
    ].astype(
        str
    )

    out[
        "patient"
    ] = out[
        "patient"
    ].astype(
        str
    )

    out[
        "operating_point"
    ] = "dice"

    out[
        "dataset"
    ] = "BUS-UCLM"

    return out


oof_frames = []
normal_frames = []


# Existing BUS-BRA clean audit.
for fold in OUTER_FOLDS:
    for variant in BASELINE_VARIANTS:
        d = pd.read_csv(
            bra_baseline_dir(
                fold,
                variant,
            )
            / "per_image_test_clean.csv"
        )

        oof_frames.append(
            normalize_bra_baseline_details(
                d
            )
        )


# Existing BUS-UCLM supervised baselines.
for fold in OUTER_FOLDS:
    for variant in BASELINE_VARIANTS:
        d = pd.read_csv(
            uclm_baseline_dir(
                fold,
                variant,
            )
            / "per_image_test_lesion.csv"
        )

        oof_frames.append(
            normalize_uclm_baseline_details(
                d
            )
        )

        n = pd.read_csv(
            uclm_baseline_dir(
                fold,
                variant,
            )
            / "per_image_test_normal.csv"
        )

        n[
            "dataset"
        ] = "BUS-UCLM"

        n[
            "operating_point"
        ] = "dice"

        normal_frames.append(
            n
        )


# New CABLE operating points.
if RUN_BUSBRA:
    for fold in OUTER_FOLDS:
        out_dir = busbra_cable_run_dir(
            fold
        )

        for op in [
            "dice",
            "boundary",
        ]:
            d = pd.read_csv(
                out_dir
                / f"per_image_test_{op}.csv"
            )

            oof_frames.append(
                d
            )


if RUN_BUSUCLM:
    for fold in OUTER_FOLDS:
        out_dir = uclm_cable_run_dir(
            fold
        )

        for op in [
            "dice",
            "boundary",
        ]:
            d = pd.read_csv(
                out_dir
                / f"per_image_test_lesion_{op}.csv"
            )

            n = pd.read_csv(
                out_dir
                / f"per_image_test_normal_{op}.csv"
            )

            oof_frames.append(
                d
            )

            normal_frames.append(
                n
            )


all_oof = pd.concat(
    oof_frames,
    ignore_index=True,
)

all_normal_oof = pd.concat(
    normal_frames,
    ignore_index=True,
)


# ------------------------------------------------------------
# Hard OOF coverage gates
# ------------------------------------------------------------

expected_lesion_rows = {
    (
        "BUS-BRA",
        "swift_lgl",
        "dice",
    ): 1875,
    (
        "BUS-BRA",
        "mhtm_hybrid_final",
        "dice",
    ): 1875,
    (
        "BUS-BRA",
        "cable_s1",
        "dice",
    ): 1875,
    (
        "BUS-BRA",
        "cable_s1",
        "boundary",
    ): 1875,

    (
        "BUS-UCLM",
        "swift_lgl",
        "dice",
    ): 260,
    (
        "BUS-UCLM",
        "mhtm_hybrid_final",
        "dice",
    ): 260,
    (
        "BUS-UCLM",
        "cable_s1",
        "dice",
    ): 260,
    (
        "BUS-UCLM",
        "cable_s1",
        "boundary",
    ): 260,
}


for key, expected in expected_lesion_rows.items():
    dataset, variant, op = key

    g = all_oof[
        (
            all_oof.dataset
            == dataset
        )
        & (
            all_oof.variant
            == variant
        )
        & (
            all_oof.operating_point
            == op
        )
    ]

    assert len(
        g
    ) == expected, (
        key,
        len(
            g
        ),
        expected,
    )

    assert g[
        "id"
    ].nunique() == expected


for op in [
    "dice",
    "boundary",
]:
    g = all_normal_oof[
        (
            all_normal_oof.variant
            == "cable_s1"
        )
        & (
            all_normal_oof.operating_point
            == op
        )
    ]

    assert len(
        g
    ) == 410

    assert g[
        "id"
    ].nunique() == 410


print(
    "PASS: authoritative baselines + both CABLE operating points "
    "have complete OOF coverage."
)


all_oof.to_csv(
    FINAL_ROOT
    / "ALL_OOF_LESION_RESULTS.csv",
    index=False,
)

all_normal_oof.to_csv(
    FINAL_ROOT
    / "ALL_OOF_NORMAL_RESULTS.csv",
    index=False,
)

PASS: authoritative baselines + both CABLE operating points have complete OOF coverage.

In [64]:

# ============================================================
# 28. PATIENT-CLUSTERED PAIRED BOOTSTRAP
# ============================================================

def patient_bootstrap_delta(
    reference_df,
    comparison_df,
    metric,
    n_boot=5000,
    seed=2026,
):
    a = (
        reference_df[
            [
                "id",
                "patient",
                metric,
            ]
        ]
        .rename(
            columns={
                metric: "reference"
            }
        )
    )

    b = (
        comparison_df[
            [
                "id",
                "patient",
                metric,
            ]
        ]
        .rename(
            columns={
                metric: "comparison"
            }
        )
    )

    paired = a.merge(
        b,
        on=[
            "id",
            "patient",
        ],
        validate="one_to_one",
    )

    paired[
        "delta"
    ] = (
        paired.comparison
        - paired.reference
    )

    patient_delta = (
        paired.groupby(
            "patient"
        )[
            "delta"
        ]
        .mean()
    )

    values = patient_delta.to_numpy(
        dtype=float
    )

    rng = np.random.default_rng(
        seed
    )

    boots = np.empty(
        n_boot,
        dtype=float,
    )

    for i in range(
        n_boot
    ):
        idx = rng.integers(
            0,
            len(
                values
            ),
            size=len(
                values
            ),
        )

        boots[
            i
        ] = values[
            idx
        ].mean()

    lo, hi = np.percentile(
        boots,
        [
            2.5,
            97.5,
        ],
    )

    return {
        "metric": metric,
        "delta_comparison_minus_reference": float(
            values.mean()
        ),
        "ci95_low": float(
            lo
        ),
        "ci95_high": float(
            hi
        ),
        "n_patients": int(
            len(
                values
            )
        ),
        "n_images": int(
            len(
                paired
            )
        ),
    }


bootstrap_rows = []


# ------------------------------------------------------------
# Main fair architecture comparison:
# CABLE-Dice vs each best-Dice baseline.
# ------------------------------------------------------------
for dataset in [
    "BUS-BRA",
    "BUS-UCLM",
]:
    cable_dice = all_oof[
        (
            all_oof.dataset
            == dataset
        )
        & (
            all_oof.variant
            == CABLE_VARIANT
        )
        & (
            all_oof.operating_point
            == "dice"
        )
    ]

    for ref_variant in BASELINE_VARIANTS:
        ref = all_oof[
            (
                all_oof.dataset
                == dataset
            )
            & (
                all_oof.variant
                == ref_variant
            )
            & (
                all_oof.operating_point
                == "dice"
            )
        ]

        for metric in [
            "dice",
            "iou",
            "hd95",
            "boundary_iou",
        ]:
            row = patient_bootstrap_delta(
                ref,
                cable_dice,
                metric,
            )

            row.update({
                "dataset": dataset,
                "analysis": "main_architecture",
                "reference": ref_variant,
                "comparison": "cable_s1_dice",
            })

            bootstrap_rows.append(
                row
            )


# ------------------------------------------------------------
# Secondary operating-point comparison:
# CABLE-Boundary vs CABLE-Dice.
# ------------------------------------------------------------
for dataset in [
    "BUS-BRA",
    "BUS-UCLM",
]:
    cable_dice = all_oof[
        (
            all_oof.dataset
            == dataset
        )
        & (
            all_oof.variant
            == CABLE_VARIANT
        )
        & (
            all_oof.operating_point
            == "dice"
        )
    ]

    cable_boundary = all_oof[
        (
            all_oof.dataset
            == dataset
        )
        & (
            all_oof.variant
            == CABLE_VARIANT
        )
        & (
            all_oof.operating_point
            == "boundary"
        )
    ]

    for metric in [
        "dice",
        "iou",
        "hd95",
        "boundary_iou",
    ]:
        row = patient_bootstrap_delta(
            cable_dice,
            cable_boundary,
            metric,
        )

        row.update({
            "dataset": dataset,
            "analysis": "cable_operating_point",
            "reference": "cable_s1_dice",
            "comparison": "cable_s1_boundary",
        })

        bootstrap_rows.append(
            row
        )


bootstrap_df = pd.DataFrame(
    bootstrap_rows
)

display(
    bootstrap_df
)

bootstrap_df.to_csv(
    FINAL_ROOT
    / "PATIENT_CLUSTERED_BOOTSTRAP.csv",
    index=False,
)

,metric,delta_comparison_minus_reference,ci95_low,ci95_high,n_patients,n_images,dataset,analysis,reference,comparison
0,dice,-0.005278,-0.009500,-0.000810,1064,1875,BUS-BRA,main_architecture,swift_lgl,cable_s1_dice
1,iou,-0.007452,-0.012537,-0.002155,1064,1875,BUS-BRA,main_architecture,swift_lgl,cable_s1_dice
2,hd95,1.579305,0.751226,2.423623,1064,1875,BUS-BRA,main_architecture,swift_lgl,cable_s1_dice
3,boundary_iou,-0.005991,-0.009988,-0.001968,1064,1875,BUS-BRA,main_architecture,swift_lgl,cable_s1_dice
4,dice,0.002313,-0.001752,0.006413,1064,1875,BUS-BRA,main_architecture,mhtm_hybrid_final,cable_s1_dice
5,iou,0.002892,-0.001974,0.007830,1064,1875,BUS-BRA,main_architecture,mhtm_hybrid_final,cable_s1_dice
6,hd95,-0.650446,-1.499459,0.173298,1064,1875,BUS-BRA,main_architecture,mhtm_hybrid_final,cable_s1_dice
7,boundary_iou,0.004345,0.000462,0.008125,1064,1875,BUS-BRA,main_architecture,mhtm_hybrid_final,cable_s1_dice
8,dice,-0.022527,-0.068239,0.023928,35,260,BUS-UCLM,main_architecture,swift_lgl,cable_s1_dice
9,iou,-0.024233,-0.065755,0.017831,35,260,BUS-UCLM,main_architecture,swift_lgl,cable_s1_dice
10,hd95,3.110931,-8.733642,17.430740,35,260,BUS-UCLM,main_architecture,swift_lgl,cable_s1_dice
11,boundary_iou,-0.008449,-0.021501,0.005496,35,260,BUS-UCLM,main_architecture,swift_lgl,cable_s1_dice
12,dice,-0.058827,-0.093268,-0.024803,35,260,BUS-UCLM,main_architecture,mhtm_hybrid_final,cable_s1_dice
13,iou,-0.058698,-0.091053,-0.027233,35,260,BUS-UCLM,main_architecture,mhtm_hybrid_final,cable_s1_dice
14,hd95,4.490579,-6.749142,18.301647,35,260,BUS-UCLM,main_architecture,mhtm_hybrid_final,cable_s1_dice
15,boundary_iou,-0.015418,-0.027620,-0.004385,35,260,BUS-UCLM,main_architecture,mhtm_hybrid_final,cable_s1_dice
16,dice,-0.000890,-0.002815,0.001004,1064,1875,BUS-BRA,cable_operating_point,cable_s1_dice,cable_s1_boundary
17,iou,-0.000811,-0.003094,0.001452,1064,1875,BUS-BRA,cable_operating_point,cable_s1_dice,cable_s1_boundary
18,hd95,-0.806794,-1.311659,-0.349819,1064,1875,BUS-BRA,cable_operating_point,cable_s1_dice,cable_s1_boundary
19,boundary_iou,0.000816,-0.001123,0.002789,1064,1875,BUS-BRA,cable_operating_point,cable_s1_dice,cable_s1_boundary
20,dice,-0.012143,-0.028459,0.000174,35,260,BUS-UCLM,cable_operating_point,cable_s1_dice,cable_s1_boundary
21,iou,-0.008607,-0.019531,-0.000192,35,260,BUS-UCLM,cable_operating_point,cable_s1_dice,cable_s1_boundary
22,hd95,0.010512,-3.812844,3.324700,35,260,BUS-UCLM,cable_operating_point,cable_s1_dice,cable_s1_boundary
23,boundary_iou,-0.001054,-0.003736,0.000717,35,260,BUS-UCLM,cable_operating_point,cable_s1_dice,cable_s1_boundary

In [65]:

# ============================================================
# 29. CABLE CHECKPOINT BEHAVIOR + SUBGROUP ANALYSIS
# ============================================================

selection_rows = []

if RUN_BUSBRA:
    for r in busbra_cable_results:
        selection_rows.append({
            "dataset": "BUS-BRA",
            "fold": int(
                r[
                    "fold"
                ]
            ),
            "best_dice_epoch": int(
                r[
                    "dice_checkpoint_epoch"
                ]
            ),
            "boundary_epoch": int(
                r[
                    "boundary_checkpoint_epoch"
                ]
            ),
            "changed": bool(
                r[
                    "selected_differs_from_best_dice"
                ]
            ),
            "val_max_dice": float(
                r[
                    "max_val_dice"
                ]
            ),
            "boundary_selected_val_dice": float(
                r[
                    "selected_val_dice"
                ]
            ),
            "boundary_selected_val_hd95": float(
                r[
                    "selected_val_hd95"
                ]
            ),
        })


if RUN_BUSUCLM:
    for r in uclm_cable_results:
        selection_rows.append({
            "dataset": "BUS-UCLM",
            "fold": int(
                r[
                    "fold"
                ]
            ),
            "best_dice_epoch": int(
                r[
                    "dice_checkpoint_epoch"
                ]
            ),
            "boundary_epoch": int(
                r[
                    "boundary_checkpoint_epoch"
                ]
            ),
            "changed": bool(
                r[
                    "selected_differs_from_best_dice"
                ]
            ),
            "val_max_dice": float(
                r[
                    "max_val_dice"
                ]
            ),
            "boundary_selected_val_dice": float(
                r[
                    "selected_val_dice"
                ]
            ),
            "boundary_selected_val_hd95": float(
                r[
                    "selected_val_hd95"
                ]
            ),
        })


selection_df = pd.DataFrame(
    selection_rows
)

display(
    selection_df
)

print(
    "\nFraction of folds where the boundary-aware selector "
    "chooses a different epoch:"
)

display(
    selection_df.groupby(
        "dataset"
    )[
        "changed"
    ].mean()
)


selection_df.to_csv(
    FINAL_ROOT
    / "CABLE_CHECKPOINT_SELECTION_AUDIT.csv",
    index=False,
)


# ------------------------------------------------------------
# Pathology subgroup
# ------------------------------------------------------------
pathology_summary = (
    all_oof.groupby(
        [
            "dataset",
            "variant",
            "operating_point",
            "pathology",
        ],
        as_index=False,
    )
    .agg(
        n_images=("id", "nunique"),
        n_patients=("patient", "nunique"),
        dice=("dice", "mean"),
        iou=("iou", "mean"),
        hd95=("hd95", "mean"),
        boundary_iou=("boundary_iou", "mean"),
    )
)

display(
    pathology_summary
)

pathology_summary.to_csv(
    FINAL_ROOT
    / "PATHOLOGY_SUMMARY.csv",
    index=False,
)


# ------------------------------------------------------------
# Lesion-size sensitivity
# ------------------------------------------------------------
size_frames = []

for dataset in [
    "BUS-BRA",
    "BUS-UCLM",
]:
    ref = all_oof[
        (
            all_oof.dataset
            == dataset
        )
        & (
            all_oof.variant
            == "swift_lgl"
        )
        & (
            all_oof.operating_point
            == "dice"
        )
    ][
        [
            "id",
            "gt_area_fraction",
        ]
    ].drop_duplicates(
        "id"
    )

    q25, q75 = np.quantile(
        ref[
            "gt_area_fraction"
        ],
        [
            0.25,
            0.75,
        ],
    )

    tmp = all_oof[
        all_oof.dataset
        == dataset
    ].copy()

    tmp[
        "size_group"
    ] = np.where(
        tmp[
            "gt_area_fraction"
        ]
        <= q25,
        "small_Q1",
        np.where(
            tmp[
                "gt_area_fraction"
            ]
            >= q75,
            "large_Q4",
            "middle_Q2_Q3",
        ),
    )

    s = (
        tmp.groupby(
            [
                "dataset",
                "variant",
                "operating_point",
                "size_group",
            ],
            as_index=False,
        )
        .agg(
            n_images=("id", "nunique"),
            dice=("dice", "mean"),
            iou=("iou", "mean"),
            hd95=("hd95", "mean"),
            boundary_iou=("boundary_iou", "mean"),
        )
    )

    s[
        "q25_area_fraction"
    ] = q25

    s[
        "q75_area_fraction"
    ] = q75

    size_frames.append(
        s
    )


size_summary = pd.concat(
    size_frames,
    ignore_index=True,
)

display(
    size_summary
)

size_summary.to_csv(
    FINAL_ROOT
    / "LESION_SIZE_SUMMARY.csv",
    index=False,
)

,dataset,fold,best_dice_epoch,boundary_epoch,changed,val_max_dice,boundary_selected_val_dice,boundary_selected_val_hd95
0,BUS-BRA,1,45,48,True,0.850690,0.848090,18.002196
1,BUS-BRA,2,39,49,True,0.862048,0.860732,16.505384
2,BUS-BRA,3,50,50,False,0.846514,0.846514,19.403443
3,BUS-BRA,4,32,30,True,0.855565,0.850709,16.584896
4,BUS-BRA,5,50,48,True,0.846939,0.845077,17.445541
5,BUS-UCLM,1,41,41,False,0.538294,0.538294,76.555743
6,BUS-UCLM,2,27,27,False,0.470408,0.470408,69.409920
7,BUS-UCLM,3,33,33,False,0.579934,0.579934,59.319464
8,BUS-UCLM,4,41,34,True,0.489127,0.488309,84.549874
9,BUS-UCLM,5,22,37,True,0.558952,0.556466,45.180606

Fraction of folds where the boundary-aware selector chooses a different epoch:

dataset
BUS-BRA     0.8
BUS-UCLM    0.4
Name: changed, dtype: float64

,dataset,variant,operating_point,pathology,n_images,n_patients,dice,iou,hd95,boundary_iou
0,BUS-BRA,cable_s1,boundary,benign,1268,722,0.860811,0.778026,15.815559,0.338016
1,BUS-BRA,cable_s1,boundary,malignant,607,342,0.818947,0.718990,23.505104,0.225994
2,BUS-BRA,cable_s1,dice,benign,1268,722,0.860387,0.777132,16.571032,0.335083
3,BUS-BRA,cable_s1,dice,malignant,607,342,0.823406,0.724673,23.951620,0.229408
4,BUS-BRA,mhtm_hybrid_final,dice,benign,1268,722,0.857787,0.774255,17.625595,0.331315
5,BUS-BRA,mhtm_hybrid_final,dice,malignant,607,342,0.822371,0.722492,24.030121,0.226367
6,BUS-BRA,swift_lgl,dice,benign,1268,722,0.865963,0.786051,15.061526,0.344294
7,BUS-BRA,swift_lgl,dice,malignant,607,342,0.827430,0.728778,22.605401,0.230285
8,BUS-UCLM,cable_s1,boundary,benign,170,23,0.546315,0.428814,59.586241,0.110967
9,BUS-UCLM,cable_s1,boundary,malignant,90,17,0.514182,0.394774,57.832147,0.060112
10,BUS-UCLM,cable_s1,dice,benign,170,23,0.549871,0.432538,60.830094,0.112724
11,BUS-UCLM,cable_s1,dice,malignant,90,17,0.535926,0.408634,57.689526,0.060513
12,BUS-UCLM,mhtm_hybrid_final,dice,benign,170,23,0.595480,0.475561,59.636541,0.119805
13,BUS-UCLM,mhtm_hybrid_final,dice,malignant,90,17,0.615397,0.485664,51.889668,0.085806
14,BUS-UCLM,swift_lgl,dice,benign,170,23,0.541836,0.420528,63.843991,0.103043
15,BUS-UCLM,swift_lgl,dice,malignant,90,17,0.580079,0.454276,52.830196,0.078890

,dataset,variant,operating_point,size_group,n_images,dice,iou,hd95,boundary_iou,q25_area_fraction,q75_area_fraction
0,BUS-BRA,cable_s1,boundary,large_Q4,469,0.844498,0.759294,24.350727,0.231332,0.032997,0.118134
1,BUS-BRA,cable_s1,boundary,middle_Q2_Q3,937,0.857573,0.770053,16.552471,0.302992,0.032997,0.118134
2,BUS-BRA,cable_s1,boundary,small_Q1,469,0.829408,0.736281,15.760278,0.369689,0.032997,0.118134
3,BUS-BRA,cable_s1,dice,large_Q4,469,0.853993,0.770391,23.399147,0.237688,0.032997,0.118134
4,BUS-BRA,cable_s1,dice,middle_Q2_Q3,937,0.858701,0.771281,17.430880,0.303510,0.032997,0.118134
5,BUS-BRA,cable_s1,dice,small_Q1,469,0.822287,0.727669,17.577327,0.358788,0.032997,0.118134
6,BUS-BRA,mhtm_hybrid_final,dice,large_Q4,469,0.855781,0.770231,23.631339,0.229663,0.032997,0.118134
7,BUS-BRA,mhtm_hybrid_final,dice,middle_Q2_Q3,937,0.858397,0.770762,18.179976,0.298947,0.032997,0.118134
8,BUS-BRA,mhtm_hybrid_final,dice,small_Q1,469,0.812737,0.718262,18.801286,0.361806,0.032997,0.118134
9,BUS-BRA,swift_lgl,dice,large_Q4,469,0.860672,0.779206,21.839693,0.239839,0.032997,0.118134
10,BUS-BRA,swift_lgl,dice,middle_Q2_Q3,937,0.862097,0.776561,16.636010,0.306052,0.032997,0.118134
11,BUS-BRA,swift_lgl,dice,small_Q1,469,0.829108,0.737731,14.901357,0.377597,0.032997,0.118134
12,BUS-UCLM,cable_s1,boundary,large_Q4,65,0.589748,0.467588,48.004547,0.070024,0.022636,0.100674
13,BUS-UCLM,cable_s1,boundary,middle_Q2_Q3,130,0.563654,0.444530,60.272318,0.101330,0.022636,0.100674
14,BUS-UCLM,cable_s1,boundary,small_Q1,65,0.423713,0.311476,67.367035,0.100769,0.022636,0.100674
15,BUS-UCLM,cable_s1,dice,large_Q4,65,0.616180,0.486869,43.047077,0.069906,0.022636,0.100674
16,BUS-UCLM,cable_s1,dice,middle_Q2_Q3,130,0.569762,0.448666,61.866004,0.104197,0.022636,0.100674
17,BUS-UCLM,cable_s1,dice,small_Q1,65,0.424472,0.312853,72.192813,0.100303,0.022636,0.100674
18,BUS-UCLM,mhtm_hybrid_final,dice,large_Q4,65,0.635098,0.505801,51.350581,0.071511,0.022636,0.100674
19,BUS-UCLM,mhtm_hybrid_final,dice,middle_Q2_Q3,130,0.661208,0.535309,49.371621,0.121151,0.022636,0.100674
20,BUS-UCLM,mhtm_hybrid_final,dice,small_Q1,65,0.451985,0.339813,77.725902,0.118333,0.022636,0.100674
21,BUS-UCLM,swift_lgl,dice,large_Q4,65,0.616274,0.490752,45.018613,0.074677,0.022636,0.100674
22,BUS-UCLM,swift_lgl,dice,middle_Q2_Q3,130,0.609829,0.477396,54.485857,0.104636,0.022636,0.100674
23,BUS-UCLM,swift_lgl,dice,small_Q1,65,0.384365,0.283297,86.135768,0.094780,0.022636,0.100674

In [66]:

# ============================================================
# 30. LATEX-READY MAIN + OPERATING-POINT TABLES
# ============================================================

LABELS = {
    "swift_lgl": "SwiftMSeg-LGL",
    "mhtm_hybrid_final": "MHTM-Local",
    "cable_s1": "CABLE",
}


def mean_sd(
    mean,
    sd,
    digits=4,
):
    return (
        f"{mean:.{digits}f} "
        f"$\\pm$ "
        f"{sd:.{digits}f}"
    )


main_latex_rows = []

for row in main_summary.sort_values(
    [
        "dataset",
        "variant",
    ]
).itertuples(
    index=False
):
    main_latex_rows.append({
        "Dataset": row.dataset,
        "Method": LABELS[
            row.variant
        ],
        "Dice": mean_sd(
            row.dice_mean,
            row.dice_sd,
        ),
        "IoU": mean_sd(
            row.iou_mean,
            row.iou_sd,
        ),
        "HD95": mean_sd(
            row.hd95_mean,
            row.hd95_sd,
            digits=2,
        ),
        "B-IoU": mean_sd(
            row.boundary_iou_mean,
            row.boundary_iou_sd,
        ),
        "Params (M)": f"{row.params_M:.3f}",
        "Agg. GMACs": f"{row.aggregator_GMACs:.3f}",
        "Latency (ms)": f"{row.latency_ms_median:.2f}",
    })


main_latex_df = pd.DataFrame(
    main_latex_rows
)

print(
    "MAIN FAIR ARCHITECTURE TABLE"
)

display(
    main_latex_df
)

main_latex = main_latex_df.to_latex(
    index=False,
    escape=False,
)

print(
    main_latex
)

with open(
    FINAL_ROOT
    / "MAIN_ARCHITECTURE_TABLE.tex",
    "w",
) as f:
    f.write(
        main_latex
    )


op_latex_rows = []

for row in cable_op_summary.sort_values(
    [
        "dataset",
        "operating_point",
    ]
).itertuples(
    index=False
):
    op_label = (
        "CABLE-Dice"
        if row.operating_point
        == "dice"
        else "CABLE-Boundary"
    )

    op_latex_rows.append({
        "Dataset": row.dataset,
        "Operating point": op_label,
        "Dice": mean_sd(
            row.dice_mean,
            row.dice_sd,
        ),
        "IoU": mean_sd(
            row.iou_mean,
            row.iou_sd,
        ),
        "HD95": mean_sd(
            row.hd95_mean,
            row.hd95_sd,
            digits=2,
        ),
        "B-IoU": mean_sd(
            row.boundary_iou_mean,
            row.boundary_iou_sd,
        ),
    })


op_latex_df = pd.DataFrame(
    op_latex_rows
)

print(
    "\nCABLE OPERATING-POINT TABLE"
)

display(
    op_latex_df
)

op_latex = op_latex_df.to_latex(
    index=False,
    escape=False,
)

print(
    op_latex
)

with open(
    FINAL_ROOT
    / "CABLE_OPERATING_POINT_TABLE.tex",
    "w",
) as f:
    f.write(
        op_latex
    )

MAIN FAIR ARCHITECTURE TABLE

,Dataset,Method,Dice,IoU,HD95,B-IoU,Params (M),Agg. GMACs,Latency (ms)
0,BUS-BRA,CABLE,0.8485 $\pm$ 0.0073,0.7602 $\pm$ 0.0083,18.95 $\pm$ 1.31,0.3009 $\pm$ 0.0075,4.487,0.231,12.69
1,BUS-BRA,MHTM-Local,0.8464 $\pm$ 0.0091,0.7576 $\pm$ 0.0112,19.69 $\pm$ 1.23,0.2974 $\pm$ 0.0067,4.482,0.226,13.94
2,BUS-BRA,SwiftMSeg-LGL,0.8535 $\pm$ 0.0112,0.7674 $\pm$ 0.0143,17.51 $\pm$ 0.92,0.3073 $\pm$ 0.0077,4.485,1.312,13.92
3,BUS-UCLM,CABLE,0.5335 $\pm$ 0.0973,0.4117 $\pm$ 0.0941,59.78 $\pm$ 7.34,0.0918 $\pm$ 0.0300,4.487,0.231,12.69
4,BUS-UCLM,MHTM-Local,0.6044 $\pm$ 0.0619,0.4806 $\pm$ 0.0603,56.16 $\pm$ 6.12,0.1056 $\pm$ 0.0202,4.482,0.226,13.94
5,BUS-UCLM,SwiftMSeg-LGL,0.5449 $\pm$ 0.0898,0.4219 $\pm$ 0.0864,60.06 $\pm$ 20.69,0.0875 $\pm$ 0.0293,4.485,1.312,13.92

\begin{tabular}{lllllllll}
\toprule
Dataset & Method & Dice & IoU & HD95 & B-IoU & Params (M) & Agg. GMACs & Latency (ms) \\
\midrule
BUS-BRA & CABLE & 0.8485 $\pm$ 0.0073 & 0.7602 $\pm$ 0.0083 & 18.95 $\pm$ 1.31 & 0.3009 $\pm$ 0.0075 & 4.487 & 0.231 & 12.69 \\
BUS-BRA & MHTM-Local & 0.8464 $\pm$ 0.0091 & 0.7576 $\pm$ 0.0112 & 19.69 $\pm$ 1.23 & 0.2974 $\pm$ 0.0067 & 4.482 & 0.226 & 13.94 \\
BUS-BRA & SwiftMSeg-LGL & 0.8535 $\pm$ 0.0112 & 0.7674 $\pm$ 0.0143 & 17.51 $\pm$ 0.92 & 0.3073 $\pm$ 0.0077 & 4.485 & 1.312 & 13.92 \\
BUS-UCLM & CABLE & 0.5335 $\pm$ 0.0973 & 0.4117 $\pm$ 0.0941 & 59.78 $\pm$ 7.34 & 0.0918 $\pm$ 0.0300 & 4.487 & 0.231 & 12.69 \\
BUS-UCLM & MHTM-Local & 0.6044 $\pm$ 0.0619 & 0.4806 $\pm$ 0.0603 & 56.16 $\pm$ 6.12 & 0.1056 $\pm$ 0.0202 & 4.482 & 0.226 & 13.94 \\
BUS-UCLM & SwiftMSeg-LGL & 0.5449 $\pm$ 0.0898 & 0.4219 $\pm$ 0.0864 & 60.06 $\pm$ 20.69 & 0.0875 $\pm$ 0.0293 & 4.485 & 1.312 & 13.92 \\
\bottomrule
\end{tabular}


CABLE OPERATING-POINT TABLE

,Dataset,Operating point,Dice,IoU,HD95,B-IoU
0,BUS-BRA,CABLE-Boundary,0.8473 $\pm$ 0.0092,0.7590 $\pm$ 0.0104,18.29 $\pm$ 1.61,0.3017 $\pm$ 0.0097
1,BUS-BRA,CABLE-Dice,0.8485 $\pm$ 0.0073,0.7602 $\pm$ 0.0083,18.95 $\pm$ 1.31,0.3009 $\pm$ 0.0075
2,BUS-UCLM,CABLE-Boundary,0.5186 $\pm$ 0.1053,0.4008 $\pm$ 0.0982,58.60 $\pm$ 7.82,0.0899 $\pm$ 0.0298
3,BUS-UCLM,CABLE-Dice,0.5335 $\pm$ 0.0973,0.4117 $\pm$ 0.0941,59.78 $\pm$ 7.34,0.0918 $\pm$ 0.0300

\begin{tabular}{llllll}
\toprule
Dataset & Operating point & Dice & IoU & HD95 & B-IoU \\
\midrule
BUS-BRA & CABLE-Boundary & 0.8473 $\pm$ 0.0092 & 0.7590 $\pm$ 0.0104 & 18.29 $\pm$ 1.61 & 0.3017 $\pm$ 0.0097 \\
BUS-BRA & CABLE-Dice & 0.8485 $\pm$ 0.0073 & 0.7602 $\pm$ 0.0083 & 18.95 $\pm$ 1.31 & 0.3009 $\pm$ 0.0075 \\
BUS-UCLM & CABLE-Boundary & 0.5186 $\pm$ 0.1053 & 0.4008 $\pm$ 0.0982 & 58.60 $\pm$ 7.82 & 0.0899 $\pm$ 0.0298 \\
BUS-UCLM & CABLE-Dice & 0.5335 $\pm$ 0.0973 & 0.4117 $\pm$ 0.0941 & 59.78 $\pm$ 7.34 & 0.0918 $\pm$ 0.0300 \\
\bottomrule
\end{tabular}

In [67]:

# ============================================================
# 31. FINAL MANIFEST + COMPACT PAPER BUNDLE
# ============================================================

manifest_out = {
    "experiment": "CABLE_PaperReady_Lean10Runs_v1",
    "timestamp": datetime.datetime.now().astimezone().isoformat(),

    "new_training_count": 10,

    "newly_trained_method": "CABLE",

    "reused_baselines": {
        "BUS-BRA": (
            "SWIFT_MHTM_FINAL_OFFICIALCV_CLEAN_AUDIT_V1 "
            "(checkpoint-only clean audit of the frozen best-Dice models)"
        ),
        "BUS-UCLM": (
            "SWIFT_MHTM_BUSUCLM_SUPERVISED_CV_V1 "
            "(completed supervised patient-disjoint five-fold experiment)"
        ),
    },

    "main_architecture_comparison": {
        "selection_rule": "maximum validation foreground Dice for every method",
        "methods": [
            "SwiftMSeg-LGL",
            "MHTM-Local",
            "CABLE-Dice",
        ],
    },

    "cable_boundary_operating_point": {
        "dice_tolerance_absolute": float(
            cfg.dice_tolerance
        ),
        "primary_within_tolerance": "minimum validation HD95",
        "tie_break_1": "maximum validation Boundary-IoU",
        "tie_break_2": "maximum validation Dice",
        "tie_break_3": "earlier epoch",
        "test_set_used_for_selection": False,
    },

    "cable_architecture": {
        "placement": "MiT-B0 Stage 1",
        "local_branch": "MHTM-Local H4 K3",
        "context_resolution": (
            f"{cfg.cable_context_hw}x"
            f"{cfg.cable_context_hw}"
        ),
        "context_heads": int(
            cfg.cable_context_heads
        ),
        "context_scale_init": float(
            cfg.cable_context_scale_init
        ),
        "loss": "cross_entropy",
    },

    "important_interpretation": (
        "CABLE-Boundary is a secondary operating-point analysis. "
        "It is not substituted into the main architecture table against "
        "baselines selected by validation Dice."
    ),
}


with open(
    FINAL_ROOT
    / "EXPERIMENT_MANIFEST.json",
    "w",
) as f:
    json.dump(
        manifest_out,
        f,
        indent=2,
    )


readme = """
CABLE PAPER-READY LEAN 10-RUN EXPERIMENT
========================================

NEW TRAINING
------------
Only CABLE is trained:
- 5 BUS-BRA outer folds
- 5 BUS-UCLM outer folds
Total: 10 trainings.

REUSED BASELINES
----------------
BUS-BRA:
Authoritative clean checkpoint-only audit of the already frozen Swift-LGL
and MHTM best-validation-Dice checkpoints.

BUS-UCLM:
Previously completed supervised patient-disjoint five-fold Swift-LGL and
MHTM experiment.

TWO CABLE CHECKPOINTS FROM EACH TRAINING
----------------------------------------
1. CABLE-Dice:
   maximum validation foreground Dice.

2. CABLE-Boundary:
   among epochs within 0.005 absolute Dice of the maximum, minimum
   validation HD95; tie-break by Boundary-IoU, Dice, then earlier epoch.

PAPER USE
---------
Main architecture table:
Swift-LGL vs MHTM-Local vs CABLE-Dice.

Secondary operating-point analysis:
CABLE-Dice vs CABLE-Boundary.

No test metric is used for checkpoint selection.
""".strip()


with open(
    FINAL_ROOT
    / "README.txt",
    "w",
) as f:
    f.write(
        readme
    )


zip_path = (
    DRIVE_ROOT
    / "CABLE_PaperReady_Lean10Runs_PaperBundle.zip"
)

if zip_path.exists():
    zip_path.unlink()


with zipfile.ZipFile(
    zip_path,
    mode="w",
    compression=zipfile.ZIP_DEFLATED,
    compresslevel=6,
) as zf:

    for p in sorted(
        FINAL_ROOT.rglob("*")
    ):
        if not p.is_file():
            continue

        # Keep trained checkpoints and large mask arrays on Drive.
        if p.suffix.lower() in {
            ".pt",
            ".npz",
        }:
            continue

        zf.write(
            p,
            arcname=p.relative_to(
                FINAL_ROOT
            ),
        )


local_zip = (
    Path("/content")
    / zip_path.name
    if Path("/content").exists()
    else Path.cwd()
    / zip_path.name
)


if (
    local_zip.resolve()
    != zip_path.resolve()
):
    shutil.copy2(
        zip_path,
        local_zip,
    )


print("\n" + "=" * 94)
print("CABLE LEAN 10-RUN PAPER EXPERIMENT: COMPLETE")
print("=" * 94)
print("New trainings : 10 CABLE runs only")
print("Drive output  :", FINAL_ROOT)
print("Drive ZIP     :", zip_path)
print("Local ZIP     :", local_zip)
print("=" * 94)

==============================================================================================
CABLE LEAN 10-RUN PAPER EXPERIMENT: COMPLETE
==============================================================================================
New trainings : 10 CABLE runs only
Drive output  : /content/drive/MyDrive/MHTM_MEDICAL/CABLE_PAPER_READY_LEAN10_V1
Drive ZIP     : /content/drive/MyDrive/MHTM_MEDICAL/CABLE_PaperReady_Lean10Runs_PaperBundle.zip
Local ZIP     : /content/CABLE_PaperReady_Lean10Runs_PaperBundle.zip
==============================================================================================

In [68]:

# ============================================================
# 32. FINAL PROTOCOL ASSERTIONS
# ============================================================

assert CABLE_VARIANT == "cable_s1"

assert BASELINE_VARIANTS == (
    "swift_lgl",
    "mhtm_hybrid_final",
)

assert cfg.dice_tolerance == 0.005

assert len(
    OUTER_FOLDS
) == 5

print(
    "FINAL PROTOCOL PASS:"
)

print(
    " - baselines reused, not retrained"
)

print(
    " - exactly 10 new CABLE trainings"
)

print(
    " - best-Dice + boundary-aware checkpoints saved per fold"
)

print(
    " - main table uses CABLE-Dice for fair baseline comparison"
)

print(
    " - CABLE-Boundary reported only as secondary operating-point analysis"
)

FINAL PROTOCOL PASS:
 - baselines reused, not retrained
 - exactly 10 new CABLE trainings
 - best-Dice + boundary-aware checkpoints saved per fold
 - main table uses CABLE-Dice for fair baseline comparison
 - CABLE-Boundary reported only as secondary operating-point analysis